import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import {
  OFFICIAL_PUBLIC_ACCEPTANCE_REPLAY_SAMPLES,
  buildOfficialPublicAcceptanceReplayCoverageReport,
  collectAcceptancePolicyReplayCalibrationSamples,
  collectOfficialPublicAcceptanceReplayCalibrationSamples,
} from '../services/acceptancePolicyReplayCalibrationService.js'

const serviceSourcePath = fileURLToPath(new URL('../services/acceptancePolicyReplayCalibrationService.ts', import.meta.url))

describe('acceptance policy replay calibration service', () => {
  it('fails closed for default cross-project reads without system-job capability', async () => {
    await expect(collectAcceptancePolicyReplayCalibrationSamples({
      includeOfficialPublicSamples: false,
    })).rejects.toThrow('acceptance policy replay requires systemJob capability')
  })

  it('keeps production replay sampling on approved fixed SQL branches', () => {
    const source = readFileSync(serviceSourcePath, 'utf8')

    expect(source).not.toContain('rawQuery(sql')
    expect(source).toContain('unapproved_acceptance_policy_replay_calibration_sql')
    expect(source).toContain('FROM acceptance_plans')
    expect(source).toContain('FROM acceptance_requirements')
  })

  it('reports replay coverage against every governed acceptance province city profile and formal business type', () => {
    const report = buildOfficialPublicAcceptanceReplayCoverageReport()

    expect(report.seedScope.provinceCount).toBeGreaterThanOrEqual(31)
    expect(report.seedScope.cityProfileCount).toBeGreaterThanOrEqual(50)
    expect(report.seedScope.businessProfileCodes).toEqual([
      'general_civil',
      'hotel',
      'hospital',
      'school',
      'industrial',
      'data_center',
      'transportation_hub',
      'sports_culture',
      'tod_upper_cover',
      'renovation',
      'modular_building',
    ])
    expect(report.serviceProfileSourceCoverage.missingRegionProfileKeys).toEqual([])
    expect(report.publicEvidenceCoverage.missingBusinessTypeCodes).toEqual([])
    expect(report.namedPublicProjectCoverage.sampleCount).toBeGreaterThanOrEqual(65)
    expect(report.namedPublicProjectCoverage.coveredProvinceCount).toBeGreaterThanOrEqual(31)
    expect(report.namedPublicProjectCoverage.missingProvinceCodes).toEqual([])
    expect(report.namedPublicProjectCoverage.coveredCityProfileCount).toBeGreaterThanOrEqual(65)
    expect(report.namedPublicProjectCoverage.strongConstructionCloseoutSampleCount).toBeGreaterThanOrEqual(63)
    expect(report.namedPublicProjectCoverage.strongConstructionCloseoutCoveredCityProfileCount).toBeGreaterThanOrEqual(65)
    expect(report.namedPublicProjectCoverage.housingArchiveStrongCloseoutSampleCount).toBeGreaterThanOrEqual(56)
    expect(report.namedPublicProjectCoverage.housingArchiveStrongCloseoutSampleRate).toBeGreaterThanOrEqual(0.96)
    expect(report.namedPublicProjectCoverage.nonHousingArchiveStrongCloseoutSamples).toEqual([])
    expect(report.namedPublicProjectCoverage.strongConstructionCloseoutCoveredCityProfiles).toEqual(expect.arrayContaining([
      expect.objectContaining({ provinceCode: 'JS', cityCode: 'wuxi' }),
      expect.objectContaining({ provinceCode: 'GZ', cityCode: 'guiyang' }),
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'dongguan' }),
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'zhuhai' }),
      expect.objectContaining({ provinceCode: 'GX', cityCode: 'nanning' }),
      expect.objectContaining({ provinceCode: 'GS', cityCode: 'lanzhou' }),
      expect.objectContaining({ provinceCode: 'AH', cityCode: 'hefei' }),
      expect.objectContaining({ provinceCode: 'JS', cityCode: 'changzhou' }),
      expect.objectContaining({ provinceCode: 'YN', cityCode: 'kunming' }),
      expect.objectContaining({ provinceCode: 'SC', cityCode: 'chengdu' }),
      expect.objectContaining({ provinceCode: 'LN', cityCode: 'dalian' }),
      expect.objectContaining({ provinceCode: 'XJ', cityCode: 'urumqi' }),
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'foshan' }),
      expect.objectContaining({ provinceCode: 'SX', cityCode: 'taiyuan' }),
      expect.objectContaining({ provinceCode: 'SC', cityCode: 'mianyang' }),
      expect.objectContaining({ provinceCode: 'NM', cityCode: 'hohhot' }),
      expect.objectContaining({ provinceCode: 'SC', cityCode: 'yibin' }),
      expect.objectContaining({ provinceCode: 'HLJ', cityCode: 'harbin' }),
      expect.objectContaining({ provinceCode: 'SD', cityCode: 'yantai' }),
      expect.objectContaining({ provinceCode: 'HA', cityCode: 'LY' }),
      expect.objectContaining({ provinceCode: 'HA', cityCode: 'luoyang' }),
      expect.objectContaining({ provinceCode: 'HE', cityCode: 'CD' }),
      expect.objectContaining({ provinceCode: 'HLJ', cityCode: 'QQHE' }),
    ]))
    expect(report.namedPublicProjectCoverage.coveredCityProfiles).toEqual(expect.arrayContaining([
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'GZ' }),
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'shenzhen' }),
      expect.objectContaining({ provinceCode: 'JS', cityCode: 'SZ' }),
      expect.objectContaining({ provinceCode: 'JS', cityCode: 'suzhou' }),
      expect.objectContaining({ provinceCode: 'JS', cityCode: 'wuxi' }),
      expect.objectContaining({ provinceCode: 'ZJ', cityCode: 'ningbo' }),
      expect.objectContaining({ provinceCode: 'FJ', cityCode: 'fuzhou' }),
      expect.objectContaining({ provinceCode: 'JX', cityCode: 'nanchang' }),
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'guangzhou' }),
      expect.objectContaining({ provinceCode: 'HB', cityCode: 'wuhan' }),
      expect.objectContaining({ provinceCode: 'TJ', cityCode: 'tianjin' }),
      expect.objectContaining({ provinceCode: 'CQ', cityCode: 'chongqing' }),
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'ZS' }),
      expect.objectContaining({ provinceCode: 'BJ', cityCode: 'BJ' }),
      expect.objectContaining({ provinceCode: 'BJ', cityCode: 'beijing' }),
      expect.objectContaining({ provinceCode: 'HA', cityCode: 'zhengzhou' }),
      expect.objectContaining({ provinceCode: 'HE', cityCode: 'shijiazhuang' }),
      expect.objectContaining({ provinceCode: 'FJ', cityCode: 'quanzhou' }),
      expect.objectContaining({ provinceCode: 'HA', cityCode: 'ZK' }),
      expect.objectContaining({ provinceCode: 'ZJ', cityCode: 'jiaxing' }),
      expect.objectContaining({ provinceCode: 'SD', cityCode: 'QD' }),
      expect.objectContaining({ provinceCode: 'SD', cityCode: 'qingdao' }),
      expect.objectContaining({ provinceCode: 'LN', cityCode: 'PJ' }),
      expect.objectContaining({ provinceCode: 'SC', cityCode: 'DZ' }),
      expect.objectContaining({ provinceCode: 'SD', cityCode: 'JN' }),
      expect.objectContaining({ provinceCode: 'SD', cityCode: 'jinan' }),
      expect.objectContaining({ provinceCode: 'HN', cityCode: 'changsha' }),
      expect.objectContaining({ provinceCode: 'JS', cityCode: 'nantong' }),
      expect.objectContaining({ provinceCode: 'HB', cityCode: 'xiangyang' }),
      expect.objectContaining({ provinceCode: 'ZJ', cityCode: 'hangzhou' }),
      expect.objectContaining({ provinceCode: 'LN', cityCode: 'shenyang' }),
      expect.objectContaining({ provinceCode: 'JL', cityCode: 'changchun' }),
      expect.objectContaining({ provinceCode: 'HN', cityCode: 'zhuzhou' }),
      expect.objectContaining({ provinceCode: 'SH', cityCode: 'shanghai' }),
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'dongguan' }),
      expect.objectContaining({ provinceCode: 'SN', cityCode: 'xian' }),
      expect.objectContaining({ provinceCode: 'XJ', cityCode: 'urumqi' }),
      expect.objectContaining({ provinceCode: 'SD', cityCode: 'yantai' }),
      expect.objectContaining({ provinceCode: 'SD', cityCode: 'weifang' }),
      expect.objectContaining({ provinceCode: 'JS', cityCode: 'changzhou' }),
      expect.objectContaining({ provinceCode: 'SC', cityCode: 'CD' }),
      expect.objectContaining({ provinceCode: 'SC', cityCode: 'chengdu' }),
      expect.objectContaining({ provinceCode: 'LN', cityCode: 'dalian' }),
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'foshan' }),
      expect.objectContaining({ provinceCode: 'AH', cityCode: 'hefei' }),
      expect.objectContaining({ provinceCode: 'SX', cityCode: 'taiyuan' }),
      expect.objectContaining({ provinceCode: 'HLJ', cityCode: 'harbin' }),
      expect.objectContaining({ provinceCode: 'GD', cityCode: 'zhuhai' }),
      expect.objectContaining({ provinceCode: 'GX', cityCode: 'nanning' }),
      expect.objectContaining({ provinceCode: 'HLJ', cityCode: 'QQHE' }),
      expect.objectContaining({ provinceCode: 'HE', cityCode: 'CD' }),
      expect.objectContaining({ provinceCode: 'HA', cityCode: 'LY' }),
      expect.objectContaining({ provinceCode: 'HA', cityCode: 'luoyang' }),
      expect.objectContaining({ provinceCode: 'YN', cityCode: 'kunming' }),
      expect.objectContaining({ provinceCode: 'NM', cityCode: 'hohhot' }),
      expect.objectContaining({ provinceCode: 'GZ', cityCode: 'guiyang' }),
      expect.objectContaining({ provinceCode: 'GS', cityCode: 'lanzhou' }),
      expect.objectContaining({ provinceCode: 'SC', cityCode: 'yibin' }),
      expect.objectContaining({ provinceCode: 'SC', cityCode: 'mianyang' }),
      expect.objectContaining({ provinceCode: 'HI', cityCode: 'haikou' }),
    ]))
    expect(report.namedPublicProjectCoverage.coveredBusinessTypeCodes).toEqual([
      'general_civil',
      'hotel',
      'hospital',
      'school',
      'industrial',
      'data_center',
      'transportation_hub',
      'sports_culture',
      'tod_upper_cover',
      'renovation',
      'modular_building',
    ])
    expect(report.namedPublicProjectCoverage.missingBusinessTypeCodes).toEqual([])
    expect(report.officialCityEntryCoverage.sampleCount).toBeGreaterThanOrEqual(49)
    const anchoredCityProfileKeys = new Set([
      ...report.namedPublicProjectCoverage.coveredCityProfiles,
      ...report.officialCityEntryCoverage.coveredCityProfiles,
    ].map((profile) => `${profile.provinceCode}:${profile.cityCode}`))
    expect(anchoredCityProfileKeys.size).toBeGreaterThanOrEqual(65)
    expect(report.officialCityEntryCoverage.coveredCityProfiles).toEqual([])
    expect(report.calibrationQueues.cityProfilesNeedingNamedPublicProjectSamples).toEqual([])
    expect(report.calibrationPolicy).toBe('official_service_profile_for_all_regions_named_public_project_replay_expands_by_queue')
  })

  it('converts official public completion filing records into replay samples across governed cities and business profiles', () => {
    const samples = collectOfficialPublicAcceptanceReplayCalibrationSamples({
      maxSamples: OFFICIAL_PUBLIC_ACCEPTANCE_REPLAY_SAMPLES.length,
    })
    const businessTypes = new Set(samples.map((sample) => sample.businessTypeCode).filter(Boolean))
    const cities = new Set(samples.map((sample) => `${sample.provinceCode}:${sample.cityCode}`).filter(Boolean))

    expect(OFFICIAL_PUBLIC_ACCEPTANCE_REPLAY_SAMPLES.length).toBeGreaterThanOrEqual(137)
    expect(businessTypes).toEqual(new Set([
      'data_center',
      'general_civil',
      'hospital',
      'hotel',
      'industrial',
      'modular_building',
      'renovation',
      'school',
      'sports_culture',
      'tod_upper_cover',
      'transportation_hub',
    ]))
    expect(cities.size).toBeGreaterThanOrEqual(10)
    expect(samples).toEqual(expect.arrayContaining([
      expect.objectContaining({
        projectId: 'official-public:SZ:industrial-factory-completion-filing',
        provinceCode: 'GD',
        cityCode: 'SZ',
        businessTypeCode: 'industrial',
        sampleSource: 'official_public_completion_filing',
        evidenceScope: 'completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('zjj.sz.gov.cn/projreg/public/jgys'),
        actualItemCodes: expect.arrayContaining(['completion_filing']),
      }),
      expect.objectContaining({
        provinceCode: 'BJ',
        cityCode: 'BJ',
        businessTypeCode: 'hotel',
        actualItemCodes: expect.arrayContaining(['public_assembly_fire_safety_check']),
      }),
      expect.objectContaining({
        projectId: 'official-public:WX:general-civil-joint-acceptance-replay',
        provinceCode: 'JS',
        cityCode: 'wuxi',
        businessTypeCode: 'general_civil',
        evidenceScope: 'delivery_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('js.wuxi.gov.cn/doc/2021/08/27/3445839.shtml'),
        actualItemCodes: expect.arrayContaining(['delivery_filing', 'planning_acceptance', 'fire_acceptance', 'power_acceptance']),
      }),
      expect.objectContaining({
        projectId: 'official-public:WX:industrial-huishan-energy-storage-manufacturing-hq-completion-filing-202511',
        provinceCode: 'JS',
        cityCode: 'wuxi',
        businessTypeCode: 'industrial',
        evidenceScope: 'completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('huishan.gov.cn/uploadfiles/202512/02/2025120209333394639541.xlsx'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:CZ:general-civil-hubin-jiayuan-phase2-delivery-filing-202110',
        provinceCode: 'JS',
        cityCode: 'changzhou',
        businessTypeCode: 'general_civil',
        evidenceScope: 'delivery_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('wj.gov.cn/html/czwj/2021/BCPPQENA_1104/69127.html'),
        actualItemCodes: expect.arrayContaining(['delivery_filing', 'completion_filing']),
      }),
      expect.objectContaining({
        projectId: 'official-public:GY:general-civil-vanke-lushan-e3-e5-completion-filing-202503',
        provinceCode: 'GZ',
        cityCode: 'guiyang',
        businessTypeCode: 'general_civil',
        evidenceScope: 'completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('zhujianju.guiyang.gov.cn/zfxxgk_5618855/fdzdgknr_5618858/gsgg_5618880/jgbaxxgs/202504/t20250415_87522689.html'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:SZ:industrial-xiaomo-auto-park-factory-completion-filing-202606',
        provinceCode: 'GD',
        cityCode: 'shenzhen',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('zjj.sz.gov.cn/projreg/webService/getJgysLogList.json'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:GZ:school-huanan-normal-knowledge-city-completion-filing-202606',
        provinceCode: 'GD',
        cityCode: 'GZ',
        businessTypeCode: 'school',
        sourceUrl: expect.stringContaining('zfcj.gz.gov.cn/ysqgk/Api/WebApi/gcjgysxxlb.ashx'),
        actualItemCodes: ['comprehensive_acceptance', 'completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:SUZ:transportation-suzhou-rail-line-2-extension-civil-completion-filing-201812',
        provinceCode: 'JS',
        cityCode: 'suzhou',
        businessTypeCode: 'transportation_hub',
        sourceUrl: expect.stringContaining('zfcjj.suzhou.gov.cn/szszjj/zdjsxm/201812'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:NB:industrial-fenghua-dabu-park-completion-filing-202412',
        provinceCode: 'ZJ',
        cityCode: 'ningbo',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('fh.gov.cn/art/2025/1/9'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:NC:general-civil-wanli-changchun-huayuan-completion-filing-202306',
        provinceCode: 'JX',
        cityCode: 'nanchang',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('wl.nc.gov.cn/ncswlglj/czzjzdjc/202307'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:TJ:hospital-xiqing-tcm-hospital-completion-filing-202301',
        provinceCode: 'TJ',
        cityCode: 'tianjin',
        businessTypeCode: 'hospital',
        sourceUrl: expect.stringContaining('tjxq.gov.cn/zwgk'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:FZ:hotel-international-convention-center-hotel-completion-filing-201910',
        provinceCode: 'FJ',
        cityCode: 'fuzhou',
        businessTypeCode: 'hotel',
        sourceUrl: expect.stringContaining('zjj.fuzhou.gov.cn/zwgk/xzsp/jgysbags/201911'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:WH:data-center-cicc-wuhan-big-data-room-completion-filing-202306',
        provinceCode: 'HB',
        cityCode: 'wuhan',
        businessTypeCode: 'data_center',
        sourceUrl: expect.stringContaining('P020230721582223320809.pdf'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:CQ:transportation-hub-jinxinyuan-bus-yard-completion-filing-202411',
        provinceCode: 'CQ',
        cityCode: 'chongqing',
        businessTypeCode: 'transportation_hub',
        sourceUrl: expect.stringContaining('beibei.gov.cn'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:CQ:general-civil-changshou-emergency-rescue-base-archive-acceptance-202508',
        provinceCode: 'CQ',
        cityCode: 'chongqing',
        businessTypeCode: 'general_civil',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('zfcxjw.cq.gov.cn/cqcjdag/days/202509/t20250924_15037868.html'),
        actualItemCodes: ['archive_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:WH:sports-culture-dongxihu-culture-center-theater-completion-filing-202308',
        provinceCode: 'HB',
        cityCode: 'wuhan',
        businessTypeCode: 'sports_culture',
        sourceUrl: expect.stringContaining('P020230912312859121515.pdf'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:WH:tod-sanjintan-vehicle-depot-upper-cover-completion-filing-202210',
        provinceCode: 'HB',
        cityCode: 'wuhan',
        businessTypeCode: 'tod_upper_cover',
        sourceUrl: expect.stringContaining('P020230103339936118644.pdf'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:TJ:renovation-yuantian-building-fire-decoration-completion-filing-202208',
        provinceCode: 'TJ',
        cityCode: 'tianjin',
        businessTypeCode: 'renovation',
        sourceUrl: expect.stringContaining('tjhp.gov.cn'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:TJ:modular-building-xiqing-bingshui-commercial-assembly-completion-filing-202212',
        provinceCode: 'TJ',
        cityCode: 'tianjin',
        businessTypeCode: 'modular_building',
        sourceUrl: expect.stringContaining('tjxq.gov.cn/zwgk'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:ZS:industrial-huaxing-park-factory-13-joint-acceptance-202504',
        provinceCode: 'GD',
        cityCode: 'ZS',
        businessTypeCode: 'industrial',
        evidenceScope: 'joint_acceptance_and_completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('zs.gov.cn/attachment/0/542/542112/2530168.pdf'),
        actualItemCodes: ['comprehensive_acceptance', 'completion_filing', 'fire_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:ZZ:general-civil-wanbolong-commercial-plaza-joint-acceptance-202205',
        provinceCode: 'HN',
        cityCode: 'zhuzhou',
        businessTypeCode: 'general_civil',
        evidenceScope: 'joint_acceptance_and_completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('hunan.gov.cn/topic/yjsycb/ymjj/202205'),
        actualItemCodes: ['comprehensive_acceptance', 'completion_filing', 'public_assembly_fire_safety_check'],
      }),
      expect.objectContaining({
        projectId: 'official-public:SH:renovation-hejian-road-interior-decoration-completion-filing-201203',
        provinceCode: 'SH',
        cityCode: 'shanghai',
        businessTypeCode: 'renovation',
        evidenceScope: 'completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('shyp.gov.cn/yp-zwgk/zwgk/buffersInformation/details'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:DG:industrial-jinglue-factory-water-conservation-acceptance-filing-202507',
        provinceCode: 'GD',
        cityCode: 'dongguan',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('dgwater.dg.gov.cn/gkmlpt/content/4/4419/post_4419554.html'),
        actualItemCodes: ['water_conservation_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:DG:industrial-huisheng-wool-textile-factory-completion-filing-202606',
        provinceCode: 'GD',
        cityCode: 'dongguan',
        businessTypeCode: 'industrial',
        evidenceScope: 'completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('zjj.dg.gov.cn/mware_cms/xxgs/finishRecordList.action'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:ZH:industrial-pingsha-shucheng-industrial-park-joint-acceptance-202605',
        provinceCode: 'GD',
        cityCode: 'zhuhai',
        businessTypeCode: 'industrial',
        evidenceScope: 'joint_acceptance_and_completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('zjj.zhuhai.gov.cn/wafdirectionipv4'),
        actualItemCodes: ['comprehensive_acceptance', 'completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:NN:general-civil-asean-digital-economy-park-rd-center-completion-filing-202606',
        provinceCode: 'GX',
        cityCode: 'nanning',
        businessTypeCode: 'general_civil',
        evidenceScope: 'completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('116.10.194.120/JGService/api/JGCenter/getProjRecordInfoList'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:LZ:general-civil-poly-lingxiushan-b9-joint-acceptance-202511',
        provinceCode: 'GS',
        cityCode: 'lanzhou',
        businessTypeCode: 'general_civil',
        evidenceScope: 'joint_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('zjj.lanzhou.gov.cn/art/2025/11/24/art_11415_1576181.html'),
        actualItemCodes: ['comprehensive_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:FS:general-civil-foshan-municipal-eldercare-home-completion-acceptance-202212',
        provinceCode: 'GD',
        cityCode: 'foshan',
        businessTypeCode: 'general_civil',
        evidenceScope: 'completion_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('fszj.foshan.gov.cn/zwgk/ghjh/content/post_5484171.html'),
        actualItemCodes: ['completion_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:XA:general-civil-zhonghai-xueshili-completion-registration-202412',
        provinceCode: 'SN',
        cityCode: 'xian',
        businessTypeCode: 'general_civil',
        evidenceScope: 'completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('zrzyt.shaanxi.gov.cn/news/sxxx/xa/202412'),
        actualItemCodes: ['planning_acceptance', 'completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:URUMQI:data-center-fengyun-4-ground-system-environment-acceptance-202303',
        provinceCode: 'XJ',
        cityCode: 'urumqi',
        businessTypeCode: 'data_center',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('nsmc.org.cn/nsmc/cn/news/123033.html'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:URUMQI:renovation-petrochina-hetian-street-gas-station-completion-acceptance-202410',
        provinceCode: 'XJ',
        cityCode: 'urumqi',
        businessTypeCode: 'renovation',
        evidenceScope: 'completion_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('zwfw.wlmq.gov.cn/themes/icity/engineering/projectchart/progress'),
        actualItemCodes: ['completion_acceptance', 'fire_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:YT:industrial-shandong-bandao-south-3-offshore-wind-environment-acceptance-202206',
        provinceCode: 'SD',
        cityCode: 'yantai',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('yantai.gov.cn/art/2022/6/6/art_43294_2978497.html'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:WF:general-civil-linqu-planned-roads-completion-certificate-202412',
        provinceCode: 'SD',
        cityCode: 'weifang',
        businessTypeCode: 'general_civil',
        evidenceScope: 'completion_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('linqu.gov.cn/102/7466/1873540126324428800.html'),
        actualItemCodes: ['completion_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:CZ:industrial-qiangli-electronic-materials-environment-acceptance-201804',
        provinceCode: 'JS',
        cityCode: 'changzhou',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('sthjj.changzhou.gov.cn/uploadfile/hbj/2018/0427/20180427153516_36500.pdf'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:CD:industrial-faw-volkswagen-chengdu-environment-acceptance-201203',
        provinceCode: 'SC',
        cityCode: 'chengdu',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/ywgz/hjyxpj/jsxmhjyxpj/ypzxmgg/201605/t20160522_340930.shtml'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:DL:industrial-dalian-lng-environment-acceptance-201307',
        provinceCode: 'LN',
        cityCode: 'dalian',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/ywgz/hjyxpj/jsxmhjyxpj/ypzxmgg/201605/t20160522_340932.shtml'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:FS:industrial-nanhai-power-plant-environment-acceptance-201209',
        provinceCode: 'GD',
        cityCode: 'foshan',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/ywgz/hjyxpj/jsxmhjyxpj/ypzxmgg/201605/t20160522_340917.shtml'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:HF:general-civil-steady-high-magnetic-field-environment-acceptance-201707',
        provinceCode: 'AH',
        cityCode: 'hefei',
        businessTypeCode: 'general_civil',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201707/t20170728_418684.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:TY:industrial-longquan-coal-mine-environment-acceptance-201609',
        provinceCode: 'SX',
        cityCode: 'taiyuan',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201609/t20160922_364524.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:HRB:industrial-harbin-500kv-transmission-environment-acceptance-201407',
        provinceCode: 'HLJ',
        cityCode: 'harbin',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201407/t20140708_278396.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:ZH:transportation-zhuhai-port-coal-terminal-environment-acceptance-201609',
        provinceCode: 'GD',
        cityCode: 'zhuhai',
        businessTypeCode: 'transportation_hub',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201609/t20160920_364392.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:NN:transportation-nanning-wuxu-airport-environment-acceptance-201412',
        provinceCode: 'GX',
        cityCode: 'nanning',
        businessTypeCode: 'transportation_hub',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201412/t20141212_292932.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:QQHE:general-civil-nierji-water-conservancy-environment-acceptance-201402',
        provinceCode: 'HLJ',
        cityCode: 'QQHE',
        businessTypeCode: 'general_civil',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201402/t20140213_267696.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:CHENGDE:industrial-hanhai-guyuan-pingancheng-transmission-environment-acceptance-201605',
        provinceCode: 'HE',
        cityCode: 'CD',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201605/t20160518_337842.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:LUOYANG:industrial-sinopec-sulfur-recovery-environment-acceptance-201409',
        provinceCode: 'HA',
        cityCode: 'luoyang',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201409/t20140930_289809.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:KM:industrial-yunnan-salt-vacuum-salt-environment-acceptance-201408',
        provinceCode: 'YN',
        cityCode: 'kunming',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201408/t20140821_288062.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:HHHT:industrial-fengtai-power-phase-2-environment-acceptance-201410',
        provinceCode: 'NM',
        cityCode: 'hohhot',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201410/t20141030_290898.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:GY:industrial-hazardous-medical-waste-center-environment-acceptance-201402',
        provinceCode: 'GZ',
        cityCode: 'guiyang',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201402/t20140213_267694.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:LZ:industrial-lanzhou-petrochemical-ethylene-revamp-environment-acceptance-201612',
        provinceCode: 'GS',
        cityCode: 'lanzhou',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201612/t20161222_369428.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:YB:industrial-fuxi-power-plant-environment-acceptance-201402',
        provinceCode: 'SC',
        cityCode: 'yibin',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201402/t20140219_267925.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:MY:industrial-mianyang-south-500kv-substation-environment-acceptance-202202',
        provinceCode: 'SC',
        cityCode: 'mianyang',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('sthjt.sc.gov.cn/sthjt/c103940/2025/11/10'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:HK:industrial-haikou-waste-to-energy-final-acceptance-201711',
        provinceCode: 'HI',
        cityCode: 'haikou',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('hainan.gov.cn/hainan/zysthjxxgk/201908'),
        actualItemCodes: ['environment_acceptance', 'completion_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:XZ:industrial-jiama-copper-polymetallic-environment-acceptance-201411',
        provinceCode: 'XZ',
        cityCode: 'lhasa',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201411/t20141105_291157.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:QH:industrial-kunlun-soda-ash-environment-acceptance-201409',
        provinceCode: 'QH',
        cityCode: 'haixi',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201409/t20140930_289810.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:NX:industrial-yipin-corn-processing-environment-acceptance-201501',
        provinceCode: 'NX',
        cityCode: 'yinchuan',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('mee.gov.cn/gkml/sthjbgw/spwj1/201501/t20150123_294752.htm'),
        actualItemCodes: ['environment_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:NJ:industrial-huadian-technology-park-completion-filing-202312',
        provinceCode: 'JS',
        cityCode: 'nanjing',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('njqxq.gov.cn/qxqrmzf/202312'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:XM:industrial-tianma-display-line-8-6-completion-filing-202505',
        provinceCode: 'FJ',
        cityCode: 'xiamen',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('szjj.xm.gov.cn/zwgk/tzgg/202505'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:WZ:hospital-wenzhou-development-zone-hospital-renovation-completion-filing-202505',
        provinceCode: 'ZJ',
        cityCode: 'wenzhou',
        businessTypeCode: 'hospital',
        sourceUrl: expect.stringContaining('zjjcmspublic.oss-cn-hangzhou-zwynet-d01-a.internet.cloud.zj.gov.cn'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:HF:industrial-gongtou-chuangzhi-a5-1-factory-archive-acceptance-202506',
        provinceCode: 'AH',
        cityCode: 'hefei',
        businessTypeCode: 'industrial',
        evidenceScope: 'specialty_acceptance_occurrence_check',
        sourceUrl: expect.stringContaining('anhuitushen.com/xinxigongshi/217.html'),
        actualItemCodes: ['archive_acceptance'],
      }),
      expect.objectContaining({
        projectId: 'official-public:BJ:general-civil-dougezhuang-resettlement-completion-filing-202602',
        provinceCode: 'BJ',
        cityCode: 'BJ',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('bjdch.gov.cn/zwgk'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:ZZ:industrial-east-environmental-energy-completion-filing-202103',
        provinceCode: 'HA',
        cityCode: 'zhengzhou',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('public.zhongmu.gov.cn/D49Y'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:SJZ:school-hebei-engineering-technical-college-expansion-completion-filing-202601',
        provinceCode: 'HE',
        cityCode: 'shijiazhuang',
        businessTypeCode: 'school',
        sourceUrl: expect.stringContaining('xzspj.sjz.gov.cn/columns'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:QZ:industrial-yayi-printing-factory-completion-filing-202512',
        provinceCode: 'FJ',
        cityCode: 'quanzhou',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('jinjiang.gov.cn/xxgk/zdxxgk'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:ZK:general-civil-country-garden-tianxiwan-completion-filing-202311',
        provinceCode: 'HA',
        cityCode: 'ZK',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('zfcxjs.zhoukou.gov.cn/sitesources'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:JXG:general-civil-pinghu-youlinc-center-completion-filing-202209',
        provinceCode: 'ZJ',
        cityCode: 'jiaxing',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('zjjcmspublic.oss-cn-hangzhou-zwynet-d01-a.internet.cloud.zj.gov.cn'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:QD:general-civil-licang-qingyin-expressway-east-residential-completion-filing-202501',
        provinceCode: 'SD',
        cityCode: 'QD',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('sjw.qingdao.gov.cn/cxjsj8/cxjsj65/202507'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:PJ:industrial-north-new-material-gas-office-completion-filing-202210',
        provinceCode: 'LN',
        cityCode: 'PJ',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('panshan.gov.cn/2022_11/01_14'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:DZ:hospital-dazhou-central-hospital-underground-parking-completion-filing-202502',
        provinceCode: 'SC',
        cityCode: 'DZ',
        businessTypeCode: 'hospital',
        sourceUrl: expect.stringContaining('zjj.dazhou.gov.cn/news-show-9420'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:JN:industrial-new-material-park-factory-completion-filing-202112',
        provinceCode: 'SD',
        cityCode: 'JN',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('jnzwfw.jinan.gov.cn/art/2021/12/24'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:CS:general-civil-tiancheng-rongyuan-completion-filing-201409',
        provinceCode: 'HN',
        cityCode: 'changsha',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('zjt.hunan.gov.cn/zjt/xxgk/xinxigongkaimulu/tzgg/tzgg2jzgl/202508'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:NT:general-civil-university-city-supporting-service-completion-filing-201809',
        provinceCode: 'JS',
        cityCode: 'nantong',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('nantong.gov.cn/ntsrmzf/xmjg'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:XY:transportation-garden-avenue-phase-1-joint-completion-filing-202512',
        provinceCode: 'HB',
        cityCode: 'xiangyang',
        businessTypeCode: 'transportation_hub',
        sourceUrl: expect.stringContaining('szjj.xiangyang.gov.cn/zwgk/zc/qtzdgkwj/gsgg/202512'),
        actualItemCodes: ['comprehensive_acceptance', 'completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:HZ:industrial-semiconductor-wafer-completion-filing-202302',
        provinceCode: 'ZJ',
        cityCode: 'hangzhou',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('hangzhou.gov.cn/art/2023/3/17'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:SY:hospital-china-medical-university-regional-center-completion-filing-202503',
        provinceCode: 'LN',
        cityCode: 'shenyang',
        businessTypeCode: 'hospital',
        sourceUrl: expect.stringContaining('jw.shenyang.gov.cn/xmxx/jgbaxx/202510'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:CC:industrial-changde-industrial-park-factory-completion-filing-202509',
        provinceCode: 'JL',
        cityCode: 'changchun',
        businessTypeCode: 'industrial',
        sourceUrl: expect.stringContaining('zhsfq.jl.gov.cn/zw/zjgs/fwjzhszjcssgcjgysba'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:KM:general-civil-boyicheng-a3-completion-filing-201912',
        provinceCode: 'YN',
        cityCode: 'kunming',
        businessTypeCode: 'general_civil',
        evidenceScope: 'completion_filing_occurrence_check',
        sourceUrl: expect.stringContaining('leaders.people.com.cn/n1/2020/0110/c178291-31542472.html'),
        actualItemCodes: ['completion_filing'],
      }),
      expect.objectContaining({
        projectId: 'official-public:URUMQI:general-civil-joint-acceptance-service-profile-202109',
        provinceCode: 'XJ',
        cityCode: 'urumqi',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('wlmq.gov.cn/wlmqs/c119201/202109'),
        actualItemCodes: expect.arrayContaining(['fire_acceptance', 'planning_acceptance', 'archive_acceptance', 'completion_filing']),
      }),
      expect.objectContaining({
        projectId: 'official-public:LY:general-civil-joint-acceptance-service-profile-202603',
        provinceCode: 'HA',
        cityCode: 'LY',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('oss.ly.gov.cn/upload-file/files/20260330'),
        actualItemCodes: expect.arrayContaining(['comprehensive_acceptance', 'completion_filing', 'gas_acceptance', 'landscape_acceptance']),
      }),
      expect.objectContaining({
        projectId: 'official-public:LUOYANG:general-civil-joint-acceptance-service-profile-202603',
        provinceCode: 'HA',
        cityCode: 'luoyang',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('oss.ly.gov.cn/upload-file/files/20260330'),
        actualItemCodes: expect.arrayContaining(['comprehensive_acceptance', 'completion_filing', 'gas_acceptance', 'landscape_acceptance']),
      }),
      expect.objectContaining({
        projectId: 'official-public:DG:general-civil-joint-acceptance-service-profile-202308',
        provinceCode: 'GD',
        cityCode: 'dongguan',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('zjj.dg.gov.cn/zjj_mgr/itemmanage/itemSecond'),
        actualItemCodes: expect.arrayContaining(['comprehensive_acceptance', 'completion_filing', 'fire_acceptance', 'telecom_acceptance']),
      }),
      expect.objectContaining({
        projectId: 'official-public:NN:general-civil-completion-filing-service-profile',
        provinceCode: 'GX',
        cityCode: 'nanning',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('zxsp.fgw.gxzf.gov.cn/metters/guid.jspx'),
        actualItemCodes: expect.arrayContaining(['completion_filing', 'planning_acceptance', 'fire_acceptance', 'civil_defense_acceptance']),
      }),
      expect.objectContaining({
        projectId: 'official-public:ZH:general-civil-joint-acceptance-service-profile-202306',
        provinceCode: 'GD',
        cityCode: 'zhuhai',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('zhsme.org.cn/newWebchatService/toTextPolicy'),
        actualItemCodes: expect.arrayContaining(['comprehensive_acceptance', 'completion_filing', 'gas_acceptance', 'lightning_acceptance']),
      }),
      expect.objectContaining({
        projectId: 'official-public:LZ:general-civil-joint-acceptance-service-profile-202412',
        provinceCode: 'GS',
        cityCode: 'lanzhou',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('qinan.gov.cn/info/12012/1369272'),
        actualItemCodes: expect.arrayContaining(['comprehensive_acceptance', 'completion_filing', 'archive_acceptance', 'fire_acceptance']),
      }),
      expect.objectContaining({
        projectId: 'official-public:GY:general-civil-qingzhen-completion-filing-service-profile',
        provinceCode: 'GZ',
        cityCode: 'guiyang',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('zwfw.guizhou.gov.cn/bsznindex.do'),
        actualItemCodes: expect.arrayContaining(['completion_filing', 'planning_acceptance', 'fire_acceptance', 'quality_supervision_report']),
      }),
      expect.objectContaining({
        projectId: 'official-public:CD:general-civil-yuelin-completion-filing-202507',
        provinceCode: 'SC',
        cityCode: 'chengdu',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('cds.sczwfw.gov.cn/wwdt/epointcdzwfw/pages/bjgs/handlepublicity.html'),
        actualItemCodes: expect.arrayContaining(['completion_filing']),
      }),
      expect.objectContaining({
        projectId: 'official-public:DL:general-civil-modern-agriculture-market-joint-acceptance-202211',
        provinceCode: 'LN',
        cityCode: 'dalian',
        businessTypeCode: 'general_civil',
        sourceUrl: expect.stringContaining('dljp.gov.cn/dt/001003/20221208'),
        actualItemCodes: expect.arrayContaining(['comprehensive_acceptance', 'archive_acceptance', 'completion_filing']),
      }),
    ]))
  })

  it('falls back to official public replay samples when local accepted plans are not available yet', async () => {
    const samples = await collectAcceptancePolicyReplayCalibrationSamples({
      maxSamples: 5,
      queryRows: async () => [],
      includeOfficialPublicSamples: true,
    })

    expect(samples).toHaveLength(5)
    expect(samples.every((sample) => sample.sampleSource === 'official_public_completion_filing')).toBe(true)
    expect(samples.map((sample) => sample.itemCode)).toEqual(expect.arrayContaining([
      'completion_filing',
      'comprehensive_acceptance',
    ]))
  })

  it('builds replay samples from passed acceptance plans, result requirements, and project static location facts', async () => {
    const seenSql: string[] = []
    const queryRows = async <T = Record<string, unknown>>(sql: string): Promise<T[]> => {
      seenSql.push(sql)
      if (sql.includes('FROM acceptance_plans')) {
        return [
          {
            id: 'plan-comprehensive',
            project_id: 'project-1',
            type_id: 'comprehensive_acceptance',
            acceptance_type: 'comprehensive_acceptance',
            plan_name: '综合验收',
            acceptance_name: '综合验收',
            status: 'passed',
            inspection_authority: '北京市联合验收牵头部门',
            updated_at: '2026-05-20T08:00:00.000Z',
          },
          {
            id: 'plan-fire',
            project_id: 'project-1',
            type_id: 'fire_acceptance',
            acceptance_type: 'fire_acceptance',
            plan_name: '消防验收',
            acceptance_name: '消防验收',
            status: 'passed',
            inspection_authority: '北京市住建消防验收机构',
            updated_at: '2026-05-19T08:00:00.000Z',
          },
          {
            id: 'plan-draft',
            project_id: 'project-1',
            type_id: 'internal_note',
            plan_name: '内部准备会',
            status: 'draft',
            inspection_authority: '内部',
            updated_at: '2026-05-18T08:00:00.000Z',
          },
        ] as T[]
      }
      if (sql.includes('FROM projects')) {
        return [
          {
            id: 'project-1',
            location: '北京 北京市',
            metadata: {
              projectGenerationFacts: {
                projectFeatures: {
                  locationFacts: {
                    provinceCode: 'BJ',
                    cityCode: 'BJ',
                  },
                },
              },
            },
          },
        ] as T[]
      }
      if (sql.includes('FROM acceptance_requirements')) {
        return [
          {
            id: 'req-result-1',
            project_id: 'project-1',
            plan_id: 'plan-comprehensive',
            requirement_type: 'result_document',
            source_entity_type: 'template_result_document',
            source_entity_id: 'comprehensive_acceptance:result:1',
            description: '联合验收意见书',
            status: 'met',
            is_satisfied: true,
          },
          {
            id: 'req-result-2',
            project_id: 'project-1',
            plan_id: 'plan-comprehensive',
            requirement_type: 'result_document',
            source_entity_type: 'template_result_document',
            source_entity_id: 'comprehensive_acceptance:result:2',
            description: '综合验收合格意见',
            status: 'met',
            is_satisfied: true,
          },
          {
            id: 'req-open',
            project_id: 'project-1',
            plan_id: 'plan-comprehensive',
            requirement_type: 'material',
            source_entity_type: 'template_material',
            source_entity_id: 'comprehensive_acceptance:1',
            description: '未完成材料',
            status: 'open',
            is_satisfied: false,
          },
        ] as T[]
      }
      return []
    }

    const samples = await collectAcceptancePolicyReplayCalibrationSamples({
      maxSamples: 5,
      queryRows,
      previewBuilder: async () => ({
        regionProfile: {
          provinceCode: 'BJ',
          cityCode: 'BJ',
        },
        items: [
          {
            itemCode: 'comprehensive_acceptance',
            canonicalType: 'comprehensive_acceptance',
            itemName: '综合验收',
            authority: '北京市联合验收牵头部门',
            resultDocuments: ['联合验收意见书', '综合验收合格意见'],
          },
          {
            itemCode: 'fire_acceptance',
            canonicalType: 'fire_acceptance',
            itemName: '消防验收',
            authority: '北京市住建消防验收机构',
            resultDocuments: ['消防验收意见书'],
          },
        ],
      }),
    })

    expect(samples).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          projectId: 'project-1',
          provinceCode: 'BJ',
          cityCode: 'BJ',
          itemCode: 'comprehensive_acceptance',
          expectedItemNames: ['综合验收'],
          actualItemNames: ['综合验收'],
          expectedResultDocumentNames: ['联合验收意见书', '综合验收合格意见'],
          actualResultDocumentNames: ['联合验收意见书', '综合验收合格意见'],
          expectedAuthority: '北京市联合验收牵头部门',
          actualAuthority: '北京市联合验收牵头部门',
        }),
      ]),
    )
    expect(samples.map((sample) => sample.actualItemNames ?? []).flat()).not.toContain('内部准备会')
    expect(seenSql.some((sql) => sql.includes('FROM acceptance_requirements'))).toBe(true)
  })
})
