import { readFileSync } from 'node:fs'
import { resolve, sep } from 'node:path'

import { describe, expect, it } from 'vitest'

const workspaceRoot = process.cwd().endsWith(`${sep}server`)
  ? resolve(process.cwd(), '..')
  : process.cwd()

describe('deploy workflow contract', () => {
  it('pins node 20, node24-compatible actions, explicit quality gates, and self-hosted server deployment', () => {
    const workflow = readFileSync(resolve(workspaceRoot, '.github', 'workflows', 'deploy.yml'), 'utf8')

    expect(workflow).toContain('concurrency:')
    expect(workflow).toContain('cancel-in-progress: true')
    expect(workflow).toContain('FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true')
    expect(workflow).toContain('actions/checkout@v6')
    expect(workflow).toContain('actions/setup-node@v6')
    expect(workflow).toContain('actions/upload-artifact@v7')
    expect(workflow).toContain('actions/download-artifact@v7')
    expect(workflow).toContain('actions/cache@v5')
    expect(workflow).toContain("node-version: '20'")

    expect(workflow).toContain('Enable pnpm via Corepack')
    expect(workflow).toContain('corepack prepare pnpm@9 --activate')
    expect(workflow).toContain('pnpm --dir client run lint')
    expect(workflow).toContain('pnpm --dir client run test:run')
    expect(workflow).toContain('Browser Checks (${{ matrix.suite.name }})')
    expect(workflow).toContain('fail-fast: false')
    expect(workflow).toContain('verify:browser-suite:shell-and-collab')
    expect(workflow).toContain('verify:browser-suite:project-chains')
    expect(workflow).toContain('verify:browser-suite:planning-and-tooling')
    expect(workflow).toContain('npm run ${{ matrix.suite.script }}')
    expect(workflow).toContain('BROWSER_SUITE_KEY: ${{ matrix.suite.key }}')
    expect(workflow).toContain('npx playwright install --with-deps chromium')
    expect(workflow).toContain('Publish browser suite summary')
    expect(workflow).toContain('write-browser-suite-summary.mjs')
    expect(workflow).toContain('$GITHUB_STEP_SUMMARY')
    expect(workflow).toContain('browser-checks-summary:')
    expect(workflow).toContain('name: Browser Checks Overview')
    expect(workflow).toContain('pattern: browser-check-*')
    expect(workflow).toContain('merge-multiple: false')
    expect(workflow).toContain('write-browser-overview-summary.mjs')
    expect(workflow).toContain('browser-checks:')
    expect(workflow).toContain('name: Browser Checks (${{ matrix.suite.name }})')
    expect(workflow).toContain('~/.cache/ms-playwright')
    expect(workflow).toContain('if-no-files-found: error')
    expect(workflow).toContain('retention-days: 5')
    expect(workflow).toContain('working-directory: server')
    expect(workflow).toContain('npm ci --workspaces=false')
    expect(workflow).toContain('npm run typecheck')
    expect(workflow).toContain('Check migration connection secret')
    expect(workflow).toContain('SUPABASE_MIGRATION_URL')
    expect(workflow).toContain('Database migration skipped')
    expect(workflow).toContain('deploy-server:')
    expect(workflow).toContain('Deploy To Self-hosted Server')
    expect(workflow).toContain('Check server deployment credentials')
    expect(workflow).toContain('DEPLOY_HOST')
    expect(workflow).toContain('DEPLOY_USER')
    expect(workflow).toContain('DEPLOY_PATH')
    expect(workflow).toContain('DEPLOY_SSH_PRIVATE_KEY')
    expect(workflow).toContain('DEPLOY_KNOWN_HOSTS')
    expect(workflow).toContain('DEPLOY_HEALTH_URL')
    expect(workflow).toContain('Configure SSH')
    expect(workflow).toContain('ssh-keyscan')
    expect(workflow).toContain('Deploy to self-hosted server')
    expect(workflow).toContain('scripts/deploy-lighthouse-server.sh')
    expect(workflow).toContain('RELEASE_SHA: ${{ github.sha }}')
    expect(workflow).toContain("github.event.inputs.environment != 'preview'")
    expect(workflow).toContain('can_deploy=true')
    expect(workflow).toContain('exit 1')
    expect(workflow).toContain('steps.deployment-eligibility.outputs.can_deploy == \'true\'')
    expect(workflow).toContain("needs.database-migration.result == 'skipped'")

    expect(workflow).not.toContain('passWithNoTests')
    expect(workflow).toContain('npm run migrate:pending')
    expect(workflow).not.toContain('npm ci --prefix server')
    expect(workflow).not.toContain('npm run typecheck --prefix server')
    expect(workflow).not.toContain('-f 001_initial_schema.sql')
    expect(workflow).not.toContain('deploy-vercel:')
    expect(workflow).not.toContain('vercel-action@')
    expect(workflow).not.toContain('VERCEL_TOKEN')
    expect(workflow).not.toContain('VERCEL_ORG_ID')
    expect(workflow).not.toContain('VERCEL_PROJECT_ID')
    expect(workflow).not.toContain('deploy-cloudbase:')
    expect(workflow).not.toContain('tcb hosting:deploy dist')
    expect(workflow).not.toContain('deploy-cloudbase-backend.mjs')
    expect(workflow).not.toContain('CLOUDBASE_BACKEND_PORT')
    expect(workflow).not.toContain('functions:deploy api')
    expect(workflow).not.toContain('server/functions/api')
    expect(workflow).not.toContain('name: company-cockpit-browser-check')
    expect(workflow).not.toContain('name: responsibility-browser-check')
    expect(workflow).not.toContain('name: project-pages-browser-check')
  })

  it('keeps an independent workflow guard for deploy workflow drift', () => {
    const workflowGuard = readFileSync(resolve(workspaceRoot, '.github', 'workflows', 'workflow-guard.yml'), 'utf8')

    expect(workflowGuard).toContain('name: Workflow Guard')
    expect(workflowGuard).toContain('pull_request:')
    expect(workflowGuard).toContain('.github/workflows/deploy.yml')
    expect(workflowGuard).toContain('FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true')
    expect(workflowGuard).toContain('actions/checkout@v6')
    expect(workflowGuard).toContain('actions/setup-node@v6')
    expect(workflowGuard).toContain("node-version: '20'")
    expect(workflowGuard).toContain('scripts/deploy-lighthouse-server.sh')
    expect(workflowGuard).toContain('npm ci --workspaces=false')
    expect(workflowGuard).toContain('npm test -- src/__tests__/deployWorkflowContract.test.ts')
  })
})
