// v1.4.22.1 section 6: maps canonical engineering feature facts to template packs.

export type FeatureCode = string

export interface FeatureToItemPackEntry {
  featureCode: FeatureCode
  label: string
  description: string
  /** Template item packs triggered by this feature. */
  triggers: string[]
  /** Milestones triggered by this feature. */
  milestones: string[]
  /** Danger-control items triggered by this feature. */
  dangerItems: string[]
  /** Template item packs suppressed by this feature. */
  suppressionRules: string[]
  /** Whether this feature accepts a numeric value. */
  hasNumericValue: boolean
  numericLabel?: string
  numericDefault?: number
}

function entry(item: FeatureToItemPackEntry): FeatureToItemPackEntry {
  return item
}

export const FEATURE_TO_ITEM_PACK_MAP: Record<FeatureCode, FeatureToItemPackEntry> = {
  hasCivilDefense: entry({
    featureCode: 'hasCivilDefense',
    label: 'Civil defense works',
    description: 'Civil-defense physical works and acceptance workflow',
    triggers: [
      'china-civil-defense-specialty',
      'CDF-01-01-01',
      'CDF-01-01-02',
      'CDF-02-01-01',
      'CDF-02-01-02',
      'CDF-03-01-01',
    ],
    milestones: ['civil_defense_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  has_helipad: entry({
    featureCode: 'has_helipad',
    label: 'Helipad',
    description: 'Rooftop helipad and aviation suitability handover',
    triggers: [
      'china-building-fine-detail',
      'BDT-05-01-01',
      'BDT-05-01-02',
      'BDT-05-01-03',
      'BDT-05-01-04',
      'BDT-07-01-04',
      'china-gb55032-2022',
      '04-05-09',
      '04-05-10',
      '04-05-11',
    ],
    milestones: ['aviation_suitability_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  has_pool: entry({
    featureCode: 'has_pool',
    label: 'Pool',
    description: 'Pool construction and decoration scope',
    triggers: [
      'china-gb55032-2022',
      '05-11-01',
      '05-11-02',
      '05-11-03',
      '05-11-04',
      '05-11-05',
      'china-jgj-tianjin-decoration',
      'DEC-08-01-01',
      'china-plumbing-heating-system',
      'PLU-01-01-01',
      'PLU-01-01-02',
      'PLU-02-01-01',
      'PLU-02-01-02',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'count',
    numericDefault: 1,
  }),
  has_spa: entry({
    featureCode: 'has_spa',
    label: 'SPA',
    description: 'SPA zone fit-out and plumbing scope',
    triggers: [
      'china-jgj-tianjin-decoration',
      'DEC-08-01-01',
      'china-plumbing-heating-system',
      'PLU-01-01-01',
      'PLU-01-01-02',
      'PLU-02-01-01',
      'PLU-02-01-02',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  has_central_kitchen: entry({
    featureCode: 'has_central_kitchen',
    label: 'Central kitchen',
    description: 'Central kitchen facilities and food-safety acceptance',
    triggers: [
      'china-hvac-system',
      'HVA-04-01-01',
      'china-plumbing-heating-system',
      'PLU-05-01-01',
      'PLU-06-01-01',
    ],
    milestones: ['food_safety_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  near_metro: entry({
    featureCode: 'near_metro',
    label: 'Adjacent metro operation',
    description: 'Interface with operating metro line',
    triggers: [
      'china-tod-upper-cover-specialty',
      'TOD-01-01-01',
      'TOD-01-01-02',
      'TOD-04-01-01',
      'TOD-04-01-02',
      'TOD-04-01-08',
      'TOD-04-01-09',
      'china-foundation-pit-pile',
      'FND-06-01-04',
    ],
    milestones: ['metro_operator_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'm',
    numericDefault: 10,
  }),
  near_heritage: entry({
    featureCode: 'near_heritage',
    label: 'Adjacent heritage asset',
    description: 'Protection interface for nearby heritage building',
    triggers: [
      'china-foundation-pit-pile',
      'FND-06-01-01',
      'FND-06-01-02',
      'FND-06-01-03',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'm',
    numericDefault: 20,
  }),
  near_high_voltage: entry({
    featureCode: 'near_high_voltage',
    label: 'Adjacent high-voltage line',
    description: 'Protection interface for high-voltage tower or line',
    triggers: [
      'china-foundation-pit-pile',
      'FND-06-01-01',
      'FND-06-01-03',
      'FND-06-01-05',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'm',
    numericDefault: 15,
  }),
  prefabRate: entry({
    featureCode: 'prefabRate',
    label: 'Prefab rate',
    description: 'Prefabricated concrete assembly ratio',
    triggers: [
      'china-dangerous-subproject-control',
      'DANGER-01-01-13',
      'DANGER-02-01-06',
      'china-prefabricated-assembly',
      'PFB-00-01-01',
      'PFB-00-01-02',
      'PFB-00-01-03',
      'PFB-01-01-01',
      'PFB-01-01-02',
      'PFB-02-01-01',
      'PFB-02-01-03',
      'PFB-03-01-02',
      'PFB-03-01-03',
      'PFB-04-01-01',
      'PFB-04-01-02',
      'PFB-04-01-03',
      'PFB-04-01-04',
      'PFB-04-01-11',
      'PFB-04-01-12',
      'PFB-04-01-13',
    ],
    milestones: ['prefab_rate_acceptance'],
    dangerItems: ['DANGER-01-01-13', 'DANGER-02-01-06'],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: '%',
    numericDefault: 30,
  }),
  green_building: entry({
    featureCode: 'green_building',
    label: 'Green building',
    description: 'Green building or near-zero-energy rating',
    triggers: [
      'china-gb55032-2022',
      '09-01-01',
      '09-02-01',
      '09-03-01',
      '09-04-01',
      '09-05-01',
    ],
    milestones: ['energy_saving_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'level',
    numericDefault: 1,
  }),
  commercial_arcade: entry({
    featureCode: 'commercial_arcade',
    label: 'Commercial arcade',
    description: 'Mixed-use commercial arcade scope',
    triggers: [
      'china-jgj-tianjin-decoration',
      'DEC-05-01-01',
      'DEC-05-01-02',
      'china-facade-curtain-wall',
      'FAC-01-01-01',
      'FAC-01-01-02',
      'FAC-02-01-01',
      'FAC-02-01-02',
      'FAC-03-01-01',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  has_or: entry({
    featureCode: 'has_or',
    label: 'Operating rooms',
    description: 'Hospital operating department',
    triggers: [
      'china-cleanroom-medical-specialty',
      'CLN-01-01-01',
      'CLN-02-01-01',
      'CLN-02-01-02',
      'CLN-03-01-03',
      'CLN-03-01-04',
      'CLN-04-01-01',
      'CLN-04-01-02',
      'CLN-04-01-03',
      'CLN-04-01-04',
      'CLN-04-01-05',
      'CLN-04-01-13',
      'CLN-04-01-19',
      'CLN-04-01-20',
      'CLN-04-01-21',
    ],
    milestones: ['medical_gas_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'count',
    numericDefault: 6,
  }),
  has_medical_gas: entry({
    featureCode: 'has_medical_gas',
    label: 'Medical gas',
    description: 'Medical gas system',
    triggers: [
      'china-cleanroom-medical-specialty',
      'CLN-01-01-02',
      'CLN-03-01-05',
      'CLN-04-01-06',
      'CLN-04-01-07',
      'CLN-04-01-08',
      'CLN-04-01-09',
      'CLN-04-01-10',
      'CLN-04-01-11',
      'CLN-04-01-12',
    ],
    milestones: ['medical_gas_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  has_linac: entry({
    featureCode: 'has_linac',
    label: 'LINAC room',
    description: 'Linear accelerator room',
    triggers: ['china-cleanroom-medical-specialty', 'CLN-03-01-02', 'CLN-04-01-27', 'CLN-04-01-28'],
    milestones: ['health_supervision_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'count',
    numericDefault: 1,
  }),
  has_mri: entry({
    featureCode: 'has_mri',
    label: 'MRI room',
    description: 'MRI room shielding and fit-out',
    triggers: ['china-cleanroom-medical-specialty', 'CLN-04-01-23', 'CLN-04-01-24'],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'count',
    numericDefault: 1,
  }),
  has_bsl2: entry({
    featureCode: 'has_bsl2',
    label: 'BSL-2 lab',
    description: 'Biosafety level-2 laboratory',
    triggers: [
      'china-cleanroom-medical-specialty',
      'CLN-03-01-03',
      'CLN-03-01-04',
      'CLN-04-01-18',
      'CLN-04-01-36',
    ],
    milestones: ['biosafety_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  has_hbo_chamber: entry({
    featureCode: 'has_hbo_chamber',
    label: 'Hyperbaric oxygen chamber',
    description: 'Hyperbaric oxygen chamber',
    triggers: ['china-cleanroom-medical-specialty', 'CLN-04-01-40'],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  tier_level: entry({
    featureCode: 'tier_level',
    label: 'Tier level',
    description: 'Data-center Tier level',
    triggers: [
      'china-data-center-specialty',
      'DTC-04-01-25',
      'DTC-04-01-26',
      'DTC-04-01-27',
      'DTC-04-01-28',
      'DTC-04-01-29',
      'DTC-04-01-30',
    ],
    milestones: ['TCDD', 'TCCF', 'TCOS'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'level',
    numericDefault: 3,
  }),
  dual_utility_power: entry({
    featureCode: 'dual_utility_power',
    label: 'Dual utility power',
    description: 'Dual utility power supply',
    triggers: [
      'china-data-center-specialty',
      'DTC-02-01-01',
      'DTC-02-01-02',
      'DTC-04-01-07',
      'DTC-04-01-08',
      'DTC-04-01-09',
      'DTC-04-01-10',
      'DTC-04-01-11',
      'DTC-04-01-12',
      'DTC-04-01-13',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  has_dcim: entry({
    featureCode: 'has_dcim',
    label: 'DCIM',
    description: 'Data center infrastructure management',
    triggers: [
      'china-data-center-specialty',
      'DTC-02-02-02',
      'DTC-04-01-17',
      'DTC-04-01-18',
      'DTC-04-01-19',
    ],
    milestones: ['classified_protection_level_3'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  cabinet_density: entry({
    featureCode: 'cabinet_density',
    label: 'Cabinet density',
    description: 'Single-cabinet power density',
    triggers: [
      'china-data-center-specialty',
      'DTC-02-02-01',
      'DTC-04-01-03',
      'DTC-04-01-04',
      'DTC-04-01-05',
      'DTC-04-01-06',
      'DTC-04-01-14',
      'DTC-04-01-15',
      'DTC-04-01-16',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'kW',
    numericDefault: 10,
  }),
  data_center_size: entry({
    featureCode: 'data_center_size',
    label: 'Cabinet count',
    description: 'Total cabinet count',
    triggers: [
      'china-data-center-specialty',
      'DTC-01-01-01',
      'DTC-01-01-02',
      'DTC-03-01-01',
      'DTC-04-01-01',
      'DTC-04-01-02',
      'DTC-04-01-03',
      'DTC-04-01-04',
      'DTC-04-01-05',
      'DTC-04-01-06',
      'DTC-04-01-24',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'count',
    numericDefault: 100,
  }),
  cleanroom_grade: entry({
    featureCode: 'cleanroom_grade',
    label: 'Cleanroom grade',
    description: 'Industrial cleanroom grade',
    triggers: [
      'china-industrial-cleanroom-specialty',
      'ICR-01-01-01',
      'ICR-01-01-02',
      'ICR-02-01-01',
      'ICR-02-01-02',
      'ICR-02-02-01',
      'ICR-03-01-01',
      'ICR-03-01-02',
      'ICR-03-02-01',
      'ICR-04-02-01',
      'ICR-05-01-01',
      'ICR-05-01-02',
      'ICR-05-01-03',
      'ICR-05-01-04',
      'ICR-05-01-05',
    ],
    milestones: ['DQ', 'IQ', 'OQ', 'PQ'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'grade',
    numericDefault: 10000,
  }),
  explosion_proof: entry({
    featureCode: 'explosion_proof',
    label: 'Explosion-proof rating',
    description: 'Explosion-proof area rating',
    triggers: [
      'china-industrial-cleanroom-specialty',
      'ICR-03-02-01',
      'ICR-05-01-08',
      'ICR-05-01-31',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'category',
    numericDefault: 1,
  }),
  process_pure_water: entry({
    featureCode: 'process_pure_water',
    label: 'Process pure water',
    description: 'Process pure water system',
    triggers: [
      'china-industrial-cleanroom-specialty',
      'ICR-03-01-01',
      'ICR-05-01-17',
      'ICR-05-01-18',
      'ICR-05-01-30',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'conductivity',
    numericDefault: 10,
  }),
  voc_treatment: entry({
    featureCode: 'voc_treatment',
    label: 'VOC treatment',
    description: 'VOC exhaust treatment',
    triggers: [
      'china-industrial-cleanroom-specialty',
      'ICR-03-01-02',
      'ICR-05-01-11',
      'ICR-05-01-12',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  chemical_waste: entry({
    featureCode: 'chemical_waste',
    label: 'Chemical waste liquid',
    description: 'Chemical waste liquid treatment',
    triggers: [
      'china-industrial-cleanroom-specialty',
      'ICR-05-01-19',
      'ICR-05-01-20',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'type',
    numericDefault: 1,
  }),
  three_level_isolation: entry({
    featureCode: 'three_level_isolation',
    label: 'Three-level isolation',
    description: 'TOD three-level vibration isolation',
    triggers: [
      'china-tod-upper-cover-specialty',
      'TOD-02-01-02',
      'TOD-04-01-01',
      'TOD-04-01-02',
      'TOD-04-01-04',
      'TOD-04-01-09',
      'TOD-04-01-15',
      'TOD-04-01-20',
    ],
    milestones: ['isolation_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  non_stop_operation: entry({
    featureCode: 'non_stop_operation',
    label: 'Non-stop operation',
    description: 'Construction under operating transit constraints',
    triggers: [
      'china-tod-upper-cover-specialty',
      'TOD-01-01-02',
      'TOD-04-01-02',
      'TOD-04-01-08',
      'TOD-04-01-09',
      'TOD-04-01-18',
      'TOD-04-01-22',
    ],
    milestones: ['metro_operator_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  noise_dual_control: entry({
    featureCode: 'noise_dual_control',
    label: 'Noise dual control',
    description: 'Noise control measures',
    triggers: ['china-tod-upper-cover-specialty', 'TOD-04-01-15'],
    milestones: ['noise_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  heritage_level: entry({
    featureCode: 'heritage_level',
    label: 'Heritage level',
    description: 'Heritage protection level',
    triggers: [
      'china-heritage-preservation-specialty',
      'HRT-01-01-01',
      'HRT-01-01-02',
      'HRT-03-01-01',
      'HRT-04-01-01',
      'HRT-04-01-02',
      'HRT-04-01-03',
      'HRT-04-01-14',
      'HRT-04-01-15',
    ],
    milestones: ['heritage_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'level',
    numericDefault: 3,
  }),
  seismic_retrofit_level: entry({
    featureCode: 'seismic_retrofit_level',
    label: 'Seismic retrofit level',
    description: 'Seismic retrofit requirement level',
    triggers: [
      'china-renovation-retrofit-specialty',
      'RNV-04-01-08',
      'RNV-04-01-09',
      'RNV-04-01-10',
      'RNV-04-01-11',
    ],
    milestones: ['seismic_retrofit_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'level',
    numericDefault: 2,
  }),
  occupied_renovation: entry({
    featureCode: 'occupied_renovation',
    label: 'Occupied renovation',
    description: 'Renovation with partial occupancy or production continuity',
    triggers: [
      'china-renovation-retrofit-specialty',
      'RNV-01-01-01',
      'RNV-01-01-02',
      'RNV-03-01-01',
      'RNV-03-01-02',
      'RNV-04-01-04',
      'RNV-04-01-16',
      'RNV-04-01-18',
      'RNV-04-01-21',
      'RNV-04-01-22',
      'RNV-04-01-23',
      'RNV-04-01-24',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  existing_structure_year: entry({
    featureCode: 'existing_structure_year',
    label: 'Existing structure year',
    description: 'Construction year of existing structure',
    triggers: [
      'china-renovation-retrofit-specialty',
      'RNV-01-01-01',
      'RNV-04-01-01',
      'RNV-04-01-02',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'year',
    numericDefault: 2000,
  }),
  integral_lifting: entry({
    featureCode: 'integral_lifting',
    label: 'Integral lifting',
    description: 'Large-span structure integral lifting',
    triggers: [
      'china-dangerous-subproject-control',
      'DANGER-01-01-10',
      'DANGER-01-01-16',
      'china-steel-structure-specialty',
      'STL-04-01-18',
      'STL-04-01-20',
      'STL-04-01-21',
      'STL-04-01-29',
    ],
    milestones: ['integral_lifting_acceptance'],
    dangerItems: ['DANGER-01-01-10', 'DANGER-01-01-16'],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'm',
    numericDefault: 60,
  }),
  shm_monitoring: entry({
    featureCode: 'shm_monitoring',
    label: 'SHM monitoring',
    description: 'Structural health monitoring',
    triggers: ['china-steel-structure-specialty', 'STL-04-01-27'],
    milestones: ['monitoring_commissioning'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  ptfe_membrane: entry({
    featureCode: 'ptfe_membrane',
    label: 'PTFE membrane',
    description: 'PTFE membrane roof structure',
    triggers: [
      'china-dangerous-subproject-control',
      'DANGER-01-01-16',
      'china-steel-structure-specialty',
      'STL-04-01-24',
      'STL-04-01-25',
    ],
    milestones: [],
    dangerItems: ['DANGER-01-01-16'],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'm2',
    numericDefault: 5000,
  }),
  transport_interface: entry({
    featureCode: 'transport_interface',
    label: 'Transport interface',
    description: 'High-speed rail, airport, or event interface',
    triggers: [
      'china-steel-structure-specialty',
      'STL-04-01-12',
      'STL-04-01-18',
      'STL-04-01-19',
      'STL-04-01-21',
      'STL-04-01-27',
      'STL-04-01-28',
      'STL-04-01-29',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  deep_pit: entry({
    featureCode: 'deep_pit',
    label: 'Deep foundation pit',
    description: 'Deep foundation pit works',
    triggers: [
      'china-dangerous-subproject-control',
      'DANGER-DEEP-PIT-APPROVAL',
      'DANGER-01-01-01',
      'DANGER-02-01-08',
      'china-foundation-pit-pile',
      'FND-02-01-01',
      'FND-02-01-02',
      'FND-04-01-01',
      'FND-04-01-02',
      'FND-04-01-03',
      'FND-04-01-07',
      'FND-04-01-08',
      'FND-04-01-09',
      'FND-04-01-10',
      'FND-04-01-11',
      'FND-04-01-12',
      'FND-04-01-13',
      'FND-04-01-14',
      'FND-04-01-15',
      'FND-04-01-16',
      'FND-05-01-01',
      'FND-05-01-02',
      'FND-05-01-03',
      'FND-05-01-04',
      'FND-06-01-01',
      'FND-06-01-02',
      'FND-06-01-03',
      'FND-06-01-04',
      'FND-06-01-05',
    ],
    milestones: [],
    dangerItems: ['DANGER-DEEP-PIT-APPROVAL', 'DANGER-01-01-01', 'DANGER-02-01-08'],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'm',
    numericDefault: 10,
  }),
  basementLevelCount: entry({
    featureCode: 'basementLevelCount',
    label: 'Basement levels',
    description: 'Basement level count for pit, waterproofing, and workface sequencing',
    triggers: [
      'china-foundation-pit-pile',
      'FND-02-01-01',
      'FND-02-01-02',
      'FND-04-01-01',
      'FND-05-01-01',
      'FND-06-01-01',
      'china-waterproof-insulation',
      '01-07-01',
      '01-07-02',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'levels',
    numericDefault: 2,
  }),
  basementAreaM2: entry({
    featureCode: 'basementAreaM2',
    label: 'Basement area',
    description: 'Basement area for large-basement and waterproofing scope',
    triggers: [
      'china-foundation-pit-pile',
      'FND-02-01-01',
      'FND-02-01-02',
      'FND-05-01-01',
      'china-waterproof-insulation',
      '01-07-01',
      '01-07-02',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'm2',
    numericDefault: 8000,
  }),
  pile_foundation: entry({
    featureCode: 'pile_foundation',
    label: 'Pile foundation',
    description: 'Pile works, testing, and cap handover',
    triggers: [
      'china-foundation-pit-pile',
      'FND-01-01-01',
      'FND-01-01-03',
      'FND-03-01-01',
      'FND-03-01-02',
      'FND-03-01-03',
      'FND-03-01-04',
      'FND-03-01-06',
    ],
    milestones: ['pile_foundation_acceptance'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  foundation_dewatering: entry({
    featureCode: 'foundation_dewatering',
    label: 'Foundation dewatering',
    description: 'Foundation pit dewatering, recharge, and groundwater control',
    triggers: [
      'china-foundation-pit-pile',
      'FND-02-01-01',
      'FND-05-01-01',
      'FND-05-01-02',
      'FND-05-01-03',
      'FND-05-01-04',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  foundation_monitoring: entry({
    featureCode: 'foundation_monitoring',
    label: 'Foundation pit monitoring',
    description: 'Foundation pit monitoring, adjacent protection, and automated observation',
    triggers: [
      'china-foundation-pit-pile',
      'FND-06-01-01',
      'FND-06-01-02',
      'FND-06-01-03',
      'FND-06-01-04',
      'FND-06-01-05',
    ],
    milestones: ['monitoring_commissioning'],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  soft_soil: entry({
    featureCode: 'soft_soil',
    label: 'Soft soil',
    description: 'Soft soil foundation treatment',
    triggers: ['china-foundation-pit-pile', 'FND-01-01-02'],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  rock_foundation: entry({
    featureCode: 'rock_foundation',
    label: 'Rock foundation',
    description: 'Rock foundation treatment',
    triggers: ['china-foundation-pit-pile', 'FND-01-01-02'],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  diaphragm_wall: entry({
    featureCode: 'diaphragm_wall',
    label: 'Diaphragm wall',
    description: 'Diaphragm wall works',
    triggers: [
      'china-foundation-pit-pile',
      'FND-04-01-03',
      'FND-04-01-04',
      'FND-04-01-05',
      'FND-04-01-06',
    ],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  composite_structure: entry({
    featureCode: 'composite_structure',
    label: 'Composite structure',
    description: 'Steel tube or steel-reinforced concrete composite structure',
    triggers: ['china-building-fine-detail', 'BDT-04-01-03'],
    milestones: [],
    dangerItems: [],
    suppressionRules: [],
    hasNumericValue: false,
  }),
  large_span: entry({
    featureCode: 'large_span',
    label: 'Large span',
    description: 'Large-span structure',
    triggers: [
      'china-dangerous-subproject-control',
      'DANGER-01-01-10',
      'china-steel-structure-specialty',
      'STL-04-01-09',
      'STL-04-01-18',
      'STL-04-01-19',
      'STL-04-01-20',
      'STL-04-01-21',
      'STL-04-01-24',
      'STL-04-01-25',
      'STL-04-01-27',
      'STL-04-01-28',
      'STL-04-01-29',
    ],
    milestones: [],
    dangerItems: ['DANGER-01-01-10'],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'm',
    numericDefault: 60,
  }),
  supportHeightM: entry({
    featureCode: 'supportHeightM',
    label: 'High formwork',
    description: 'High-formwork support height',
    triggers: [
      'china-dangerous-subproject-control',
      'DANGER-01-01-02',
      'DANGER-02-01-04',
    ],
    milestones: [],
    dangerItems: ['DANGER-01-01-02', 'DANGER-02-01-04'],
    suppressionRules: [],
    hasNumericValue: true,
    numericLabel: 'm',
    numericDefault: 8,
  }),
}

export function getFeatureEntry(code: FeatureCode): FeatureToItemPackEntry | undefined {
  return FEATURE_TO_ITEM_PACK_MAP[code]
}
