export const ACCEPTANCE_CATALOG_COLUMNS = [
  'id',
  'project_id',
  'catalog_code',
  'catalog_name',
  'phase_code',
  'scope_level',
  'planned_finish_date',
  'description',
  'is_system',
  'created_at',
  'updated_at',
].join(', ')

export const ACCEPTANCE_PLAN_COLUMNS = [
  'id',
  'task_id',
  'project_id',
  'plan_name',
  'acceptance_name',
  'acceptance_type',
  'building_id',
  'scope_level',
  'participant_unit_id',
  'catalog_id',
  'type_id',
  'type_name',
  'type_color',
  'description',
  'planned_date',
  'actual_date',
  'status',
  'phase',
  'phase_code',
  'phase_order',
  'sort_order',
  'parallel_group_id',
  'predecessor_plan_ids',
  'successor_plan_ids',
  'can_submit',
  'is_overdue',
  'days_to_due',
  'requirement_ready_percent',
  'upstream_unfinished_count',
  'downstream_block_count',
  'display_badges',
  'overlay_tags',
  'is_blocked',
  'block_reason_summary',
  'warning_level',
  'is_custom',
  'responsible_user_id',
  'responsible_person',
  'responsible_unit',
  'inspection_authority',
  'documents',
  'notes',
  'created_at',
  'updated_at',
].join(', ')

export const ACCEPTANCE_DEPENDENCY_COLUMNS = [
  'id',
  'project_id',
  'source_plan_id',
  'target_plan_id',
  'dependency_kind',
  'status',
  'created_at',
  'updated_at',
].join(', ')

export const ACCEPTANCE_REQUIREMENT_COLUMNS = [
  'id',
  'project_id',
  'plan_id',
  'requirement_type',
  'source_entity_type',
  'source_entity_id',
  'drawing_package_id',
  'description',
  'status',
  'is_required',
  'is_satisfied',
  'created_at',
  'updated_at',
].join(', ')

export const ACCEPTANCE_RECORD_COLUMNS = [
  'id',
  'project_id',
  'plan_id',
  'record_type',
  'content',
  'operator',
  'record_date',
  'attachments',
  'created_at',
  'updated_at',
].join(', ')

export const ACCEPTANCE_NODE_COLUMNS = [
  'id',
  'acceptance_plan_id',
  'node_name',
  'node_type',
  'description',
  'planned_date',
  'actual_date',
  'status',
  'result',
  'documents',
  'inspector',
  'notes',
  'created_at',
  'updated_at',
].join(', ')

export const PRE_MILESTONE_COLUMNS = [
  'id',
  'project_id',
  'milestone_type',
  'milestone_name',
  'certificate_type',
  'certificate_name',
  'application_date',
  'issue_date',
  'expiry_date',
  'status',
  'certificate_no',
  'current_stage',
  'planned_finish_date',
  'actual_finish_date',
  'approving_authority',
  'issuing_authority',
  'next_action',
  'next_action_due_date',
  'is_blocked',
  'block_reason',
  'latest_record_at',
  'description',
  'phase_id',
  'lead_unit',
  'planned_start_date',
  'planned_end_date',
  'responsible_user_id',
  'sort_order',
  'notes',
  'created_by',
  'created_at',
  'updated_at',
].join(', ')

export const CERTIFICATE_WORK_ITEM_COLUMNS = [
  'id',
  'project_id',
  'item_code',
  'item_name',
  'item_stage',
  'status',
  'planned_finish_date',
  'actual_finish_date',
  'approving_authority',
  'is_shared',
  'next_action',
  'next_action_due_date',
  'is_blocked',
  'block_reason',
  'sort_order',
  'notes',
  'latest_record_at',
  'certificate_ids',
  'created_at',
  'updated_at',
].join(', ')

export const CERTIFICATE_DEPENDENCY_COLUMNS = [
  'id',
  'project_id',
  'predecessor_type',
  'predecessor_id',
  'successor_type',
  'successor_id',
  'dependency_kind',
  'notes',
  'created_at',
].join(', ')

export const PRE_MILESTONE_CONDITION_COLUMNS = [
  'id',
  'pre_milestone_id',
  'condition_name',
  'condition_type',
  'description',
  'is_satisfied',
  'status',
  'responsible_person',
  'completed_by',
  'confirmed_by',
  'due_date',
  'met_at',
  'notes',
  'created_at',
  'updated_at',
].join(', ')

export const WBS_TEMPLATE_DEFAULT_COLUMNS = [
  'id',
  'wbs_nodes',
].join(', ')

export const CONSTRUCTION_DRAWING_COLUMNS = [
  'id',
  'project_id',
  'drawing_type',
  'drawing_name',
  'version',
  'description',
  'status',
  'design_unit',
  'design_person',
  'drawing_date',
  'review_unit',
  'review_status',
  'review_date',
  'review_opinion',
  'review_report_no',
  'related_license_id',
  'planned_submit_date',
  'planned_pass_date',
  'actual_submit_date',
  'actual_pass_date',
  'lead_unit',
  'responsible_user_id',
  'sort_order',
  'package_id',
  'package_code',
  'package_name',
  'discipline_type',
  'document_purpose',
  'drawing_code',
  'parent_drawing_id',
  'version_no',
  'revision_no',
  'issued_for',
  'effective_date',
  'is_current_version',
  'requires_review',
  'review_mode',
  'review_basis',
  'has_change',
  'change_reason',
  'schedule_impact_flag',
  'is_ready_for_construction',
  'is_ready_for_acceptance',
  'notes',
  'created_by',
  'lock_version',
  'created_at',
  'updated_at',
].join(', ')

export const DRAWING_PACKAGE_COLUMNS = [
  'id',
  'project_id',
  'package_code',
  'package_name',
  'drawing_type',
  'discipline_type',
  'document_purpose',
  'status',
  'requires_review',
  'review_mode',
  'review_basis',
  'completeness_ratio',
  'missing_required_count',
  'current_version_drawing_id',
  'has_change',
  'schedule_impact_flag',
  'is_ready_for_construction',
  'is_ready_for_acceptance',
  'created_at',
  'updated_at',
].join(', ')

export const DRAWING_PACKAGE_ITEM_COLUMNS = [
  'id',
  'package_id',
  'item_code',
  'item_name',
  'discipline_type',
  'is_required',
  'current_drawing_id',
  'current_version',
  'status',
  'notes',
  'sort_order',
  'created_at',
  'updated_at',
].join(', ')

export const DRAWING_VERSION_COLUMNS = [
  'id',
  'project_id',
  'drawing_id',
  'package_id',
  'parent_drawing_id',
  'version_no',
  'revision_no',
  'issued_for',
  'effective_date',
  'previous_version_id',
  'is_current_version',
  'superseded_at',
  'change_reason',
  'created_by',
  'created_at',
  'updated_at',
].join(', ')

export const DRAWING_REVIEW_RULE_COLUMNS = [
  'id',
  'project_id',
  'package_code',
  'discipline_type',
  'document_purpose',
  'default_review_mode',
  'review_basis',
  'reviewer_id',
  'is_active',
  'created_at',
  'updated_at',
].join(', ')

export const DRAWING_TASK_COLUMNS = [
  'id',
  'project_id',
  'title',
  'description',
  'status',
  'created_at',
  'updated_at',
].join(', ')

export const DRAWING_TASK_CONDITION_COLUMNS = [
  'id',
  'task_id',
  'project_id',
  'condition_type',
  'condition_name',
  'description',
  'drawing_package_id',
  'drawing_package_code',
  'status',
  'is_satisfied',
  'created_at',
  'updated_at',
].join(', ')

export const DRAWING_ACCEPTANCE_PLAN_COLUMNS = [
  'id',
  'project_id',
  'task_id',
  'plan_name',
  'acceptance_name',
  'acceptance_type',
  'status',
  'planned_date',
  'actual_date',
  'created_at',
  'updated_at',
].join(', ')

export const DRAWING_ACCEPTANCE_REQUIREMENT_COLUMNS = [
  'id',
  'project_id',
  'plan_id',
  'requirement_type',
  'source_entity_type',
  'source_entity_id',
  'drawing_package_id',
  'description',
  'status',
  'created_at',
  'updated_at',
].join(', ')

export const DRAWING_ACCEPTANCE_RECORD_COLUMNS = [
  'id',
  'project_id',
  'plan_id',
  'record_type',
  'content',
  'record_date',
  'created_at',
  'updated_at',
].join(', ')
