BEGIN;

ALTER TABLE IF EXISTS public.acceptance_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.acceptance_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.acceptance_requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.certificate_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.certificate_work_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.change_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.data_confidence_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.data_quality_findings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.drawing_package_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.drawing_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.drawing_review_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.drawing_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.job_failures ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.participant_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.project_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.project_scope_dimensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.responsibility_alert_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.responsibility_watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.revision_pool_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.scope_dimensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.task_critical_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.task_preceding_relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.warning_acknowledgments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.weekly_digests ENABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';

COMMIT;
