-- v1.4.19 warning impact-signal runtime governance artifacts.
-- Stores runtime policy overrides and review artifacts generated by warningService.

CREATE TABLE IF NOT EXISTS public.warning_policy_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  project_type TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_warning_policy_configs_active_project
  ON public.warning_policy_configs(project_id, is_active)
  WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS public.warning_coverage_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  task_count INTEGER NOT NULL DEFAULT 0,
  impact_covered_task_count INTEGER NOT NULL DEFAULT 0,
  legacy_gap_fill_count INTEGER NOT NULL DEFAULT 0,
  suppressed_legacy_duplicate_count INTEGER NOT NULL DEFAULT 0,
  uncovered_task_count INTEGER NOT NULL DEFAULT 0,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_warning_coverage_snapshots_project_generated
  ON public.warning_coverage_snapshots(project_id, generated_at DESC);

CREATE TABLE IF NOT EXISTS public.warning_threshold_candidates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'candidate',
  approval_mode TEXT NOT NULL DEFAULT 'manual_approval_required',
  recommended_policy TEXT NOT NULL,
  recommended_threshold NUMERIC,
  current_threshold NUMERIC,
  sample_count INTEGER NOT NULL DEFAULT 0,
  evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  approved_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_warning_threshold_candidates_project_status
  ON public.warning_threshold_candidates(project_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.warning_owner_confirmations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  task_id UUID REFERENCES public.tasks(id) ON DELETE CASCADE,
  warning_id TEXT,
  owner_unit_id UUID REFERENCES public.participant_units(id) ON DELETE SET NULL,
  owner_role TEXT,
  confirmation_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  source_entity_type TEXT,
  source_entity_id TEXT,
  evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  feedback_status TEXT NOT NULL DEFAULT 'pending',
  feedback_applied_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

ALTER TABLE IF EXISTS public.warning_owner_confirmations
  ADD COLUMN IF NOT EXISTS feedback_status TEXT NOT NULL DEFAULT 'pending';

ALTER TABLE IF EXISTS public.warning_owner_confirmations
  ADD COLUMN IF NOT EXISTS feedback_applied_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_warning_owner_confirmations_pending
  ON public.warning_owner_confirmations(project_id, owner_unit_id, owner_role, created_at DESC)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_warning_owner_confirmations_feedback_pending
  ON public.warning_owner_confirmations(project_id, status, resolved_at DESC)
  WHERE resolved_at IS NOT NULL AND feedback_status <> 'applied';

CREATE TABLE IF NOT EXISTS public.algorithm_seed_quality_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  task_id UUID REFERENCES public.tasks(id) ON DELETE SET NULL,
  warning_id TEXT,
  rule_code TEXT NOT NULL,
  seed_source TEXT,
  quality_grade TEXT NOT NULL,
  runtime_role TEXT NOT NULL,
  source_entity_type TEXT,
  source_entity_id TEXT,
  reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidence_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_algorithm_seed_quality_events_rule
  ON public.algorithm_seed_quality_events(project_id, rule_code, created_at DESC);
