-- Migration 188: Stop legacy SQL trigger from calculating task completion durations
--
-- Duration values for task completion reports are now owned by
-- server/src/services/taskSummaryService.ts. The old trigger used CURRENT_DATE
-- and task.start_date, which made actual_duration drift after completion and
-- bypassed the shared inclusive duration helper.

BEGIN;

DROP TRIGGER IF EXISTS trigger_auto_generate_report ON tasks;
DROP FUNCTION IF EXISTS auto_generate_completion_report();

COMMENT ON TABLE task_completion_reports IS
  'Task completion report durations are generated by taskSummaryService with shared inclusive duration semantics; legacy SQL duration trigger removed in migration 188.';

COMMIT;

-- Validation after applying:
-- SELECT COUNT(*) FROM pg_trigger WHERE tgname = 'trigger_auto_generate_report';
-- Expected: 0
-- SELECT COUNT(*) FROM pg_proc WHERE proname = 'auto_generate_completion_report';
-- Expected: 0
