import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

function readSource(...segments: string[]) {
  const candidates = [
    join(process.cwd(), ...segments),
    join(process.cwd(), '..', ...segments),
    join(process.cwd(), '..', '..', ...segments),
    join(process.cwd(), 'client', ...segments),
    join(process.cwd(), '..', 'client', ...segments),
  ]

  for (const candidate of candidates) {
    try {
      return readFileSync(candidate, 'utf8')
    } catch {
      // Try the next workspace root.
    }
  }

  throw new Error(`Unable to locate source file: ${segments.join('/')}`)
}

describe('planning collaboration contracts', () => {
  it('keeps the shared planning table wired to lightweight presence hints', () => {
    const planningTreeView = readSource('src/components/planning/PlanningTreeView.tsx')
    const planTreeEditor = readSource('src/pages/planning/components/PlanTreeEditor.tsx')
    const ganttRows = readSource('src/pages/GanttViewRows.tsx')

    expect(planningTreeView).toContain('presence?: PlanningTreePresenceState')
    expect(planningTreeView).toContain('onActiveCellChange?:')
    expect(planningTreeView).toContain('viewerCount')
    expect(planningTreeView).toContain('editingByRowId')
    expect(planTreeEditor).toContain('presence={presence}')
    expect(planTreeEditor).toContain('onActiveCellChange={onActiveCellChange}')
    expect(ganttRows).toContain('presence?: PlanningTreePresenceState')
    expect(ganttRows).toContain('onActiveCellChange?:')
  })

  it('keeps all three planning entry pages using the same presence hook', () => {
    const ganttView = readSource('src/pages/GanttView.tsx')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')

    expect(ganttView).toContain("resourceType: 'task-list'")
    expect(ganttView).toContain('presence={taskListPresence}')
    expect(ganttView).toContain('onActiveCellChange={taskListPresence.setEditingCell}')
    expect(baselinePage).toContain("resourceType: 'baseline'")
    expect(baselinePage).toContain('presence={baselinePresence}')
    expect(baselinePage).toContain('onActiveCellChange={baselinePresence.setEditingCell}')
    expect(monthlyPage).toContain("resourceType: 'monthly'")
    expect(monthlyPage).toContain('presence={monthlyPresence}')
    expect(monthlyPage).toContain('onActiveCellChange={monthlyPresence.setEditingCell}')
  })

  it('keeps the deleted project-new route from falling through as a project id', () => {
    const app = readSource('src/App.tsx')
    const header = readSource('src/components/layout/Header.tsx')
    const sidebar = readSource('src/components/layout/Sidebar.tsx')
    const projectRouteGuards = readSource('src/lib/projectRouteGuards.ts')

    expect(app).not.toContain('path="/projects/new"')
    expect(projectRouteGuards).toContain('RESERVED_PROJECT_ROUTE_IDS')
    expect(projectRouteGuards).toContain("new Set(['new'])")
    expect(projectRouteGuards).toContain('function isReservedProjectRouteId')
    expect(projectRouteGuards).toContain('function getRouteProjectId')
    expect(projectRouteGuards).toContain('function isProjectRoutePath')
    expect(projectRouteGuards).toContain('function isReservedProjectRoutePath')
    expect(app).toContain('function ProjectRouteElement')
    expect(app).toContain('isReservedProjectRoutePath(location.pathname)')
    expect(app).toContain('isReservedProjectRouteId(id)')
    expect(app).toContain('const projectId = getRouteProjectId(location.pathname)')
    expect(app).toContain('return <NotFoundPage />')
    expect(app).toContain('element={<ProjectRouteElement />}')
    expect(header).toContain('isProjectRoutePath(location.pathname)')
    expect(sidebar).toContain('isProjectRoutePath(location.pathname)')
    expect(sidebar).toContain('getRouteProjectId(location.pathname)')
  })

  it('keeps monthly planning wired to the shared monthly tree interactions', () => {
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')

    expect(monthlyPage).toContain('treeVariant="monthly"')
    expect(monthlyPage).toContain('onPasteRows={handlePasteRows}')
    expect(monthlyPage).toContain('onDeleteRows={handleDeleteRows}')
    expect(monthlyPage).toContain('onFillRows={handleFillRows}')
    expect(monthlyPage).toContain('onUpdateCells={handleUpdateCells}')
    expect(monthlyPage).toContain('PlanningTreeClipboardRow')
    expect(monthlyPage).toContain('PlanningTreeCellUpdate')
  })

  it('keeps monthly batch edits in the local editor buffer until save', () => {
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')
    const batchHandlers = monthlyPage.slice(
      monthlyPage.indexOf('const handleBatchShiftDates'),
      monthlyPage.indexOf('const handleConfirmPlan'),
    )

    expect(monthlyPage).toContain('const commitMonthlyEditorItems = useCallback')
    expect(monthlyPage).toContain("surface: 'monthly_plan'")
    expect(batchHandlers).toContain('commitEditorSnapshot(nextItems, normalizedSelectedItemIds)')
    expect(batchHandlers).not.toContain('commitMonthlyEditorItems(nextItems)')
    expect(monthlyPage).not.toContain('/items/batch-shift-dates')
    expect(monthlyPage).not.toContain('/items/batch-target-progress')
    expect(monthlyPage).not.toContain('/items/batch-notes')
  })

  it('keeps baseline draft save and publish as separate v1.4.7.1 actions', () => {
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const planningTreeView = readSource('src/components/planning/PlanningTreeView.tsx')
    const publishHandler = baselinePage.slice(
      baselinePage.indexOf('const handlePublishBaseline'),
      baselinePage.indexOf('const metrics = ('),
    )

    expect(baselinePage).toContain("'/api/task-baselines/generate'")
    expect(baselinePage).toContain('if (!projectId || generating || isEditable) return')
    expect(baselinePage).toContain("title={isEditable ? '请先保存或取消当前编辑' : '生成新版项目基线草稿'}")
    expect(baselinePage).toContain("surface: 'baseline'")
    expect(baselinePage).toContain('data-testid="baseline-publish"')
    expect(baselinePage).toContain("`/api/task-baselines/${activeBaseline.id}/publish`")
    expect(baselinePage).toContain('resetBaselineHistory')
    expect(baselinePage).toContain('canUndo={canUndoBaselineEdit}')
    expect(baselinePage).toContain('canRedo={canRedoBaselineEdit}')
    expect(baselinePage).toContain('onUndo={handleUndo}')
    expect(baselinePage).toContain('onRedo={handleRedo}')
    expect(baselinePage).toContain('usePlanningViewMode({')
    expect(baselinePage).toContain("surface: 'baseline'")
    expect(planningTreeView).toContain("key === 'z'")
    expect(planningTreeView).toContain('event.shiftKey')
    expect(planningTreeView).toContain("key === 'y'")
    expect(planningTreeView).toContain("event.key === 'Escape'")
    expect(baselinePage).not.toContain('canUndo={false}')
    expect(baselinePage).not.toContain('onUndo={() => undefined}')
    expect(baselinePage).not.toContain('保存发布新版')
    expect(baselinePage).not.toContain('/generate-version')
    expect(baselinePage).not.toContain('/confirm')
    expect(publishHandler).not.toContain('commitPlanningTable')
  })

  it('keeps monthly planning aligned with baseline-style editable state instead of foreground draft locks', () => {
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')
    const bottomBar = readSource('src/pages/planning/components/MonthlyPlanBottomBar.tsx')
    const confirmDialog = readSource('src/pages/planning/components/MonthlyPlanConfirmDialog.tsx')
    const monthlyHeader = readSource('src/pages/planning/components/MonthlyPlanHeader.tsx')

    expect(monthlyPage).toContain("const readOnly = !canEdit || !activePlan || activePlan.status !== 'draft'")
    expect(monthlyPage).toContain('const hasUnsavedMonthlyEdits = Boolean(isDirty || isEditing)')
    expect(monthlyPage).toContain('!hasUnsavedMonthlyEdits')
    expect(monthlyPage).toContain('onSave={() => void handleSaveDraft()}')
    expect(monthlyPage).toContain('const handleStartEdit = useCallback')
    expect(monthlyPage).toContain('const handleCancelEdit = useCallback')
    expect(monthlyPage).toContain('usePlanningViewMode({')
    expect(monthlyPage).toContain("surface: 'monthly_plan'")
    expect(monthlyPage).toContain('onStartEdit={handleStartEdit}')
    expect(monthlyPage).toContain('onCancelEdit={handleCancelEdit}')
    expect(monthlyPage).toContain('monthLabel={formatMonthLabel(activePlan?.month ?? selectedMonth)}')
    expect(monthlyPage).toContain('data-testid="monthly-plan-generate-empty"')
    expect(monthlyPage).toContain('disabled={!canEdit}')
    expect(monthlyHeader).toContain("monthLabel = '当前月份'")
    expect(monthlyHeader).not.toContain('本月计划表')
    expect(confirmDialog).toContain('monthLabel?: string')
    expect(confirmDialog).toContain('{monthLabel} 月度计划确认')
    expect(monthlyPage).not.toContain('本月')
    expect(monthlyPage).not.toContain('上月')
    expect(monthlyPage).not.toContain('下月')
    expect(confirmDialog).not.toContain('本月新增数')
    expect(monthlyPage).not.toContain('onStartEdit={() => setIsEditing(true)}')
    expect(monthlyPage).not.toContain('/lock')
    expect(monthlyPage).not.toContain('DraftLockResponse')
    expect(monthlyPage).not.toContain('PlanningDraftLockRecord')
    expect(monthlyPage).not.toContain("setDraftStatus('locked')")
    expect(monthlyPage).not.toContain('lockedByOtherEditor')
    expect(bottomBar).not.toContain('lockRemainingLabel')
  })

  it('keeps shared planning view mode automatic and persisted by user/project/surface', () => {
    const viewModeHook = readSource('src/hooks/usePlanningViewMode.ts')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')

    expect(viewModeHook).toContain('workbuddy_planning_view_mode')
    expect(viewModeHook).toContain('getPlanningViewModeStorageKey')
    expect(viewModeHook).toContain('rowMode === \'edit\' ? editMode')
    expect(viewModeHook).toContain('writePlanningViewMode(storageKey, normalizedMode')
    expect(baselinePage).toContain('usePlanningViewMode({')
    expect(baselinePage).toContain("surface: 'baseline'")
    expect(monthlyPage).toContain('usePlanningViewMode({')
    expect(monthlyPage).toContain("surface: 'monthly_plan'")
  })

  it('keeps save-before-refresh merge wired for task list, baseline, and monthly pages', () => {
    const ganttView = readSource('src/pages/GanttView.tsx')
    const ganttTaskDialogActions = readSource('src/pages/GanttView/useGanttTaskDialogActions.ts')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')

    expect(ganttView).toContain('const [conflictOpen, setConflictOpen] = useState')
    expect(ganttTaskDialogActions).toContain('const handleKeepLocal = useCallback')
    expect(ganttTaskDialogActions).toContain('enqueueTaskTableDraftPatch(editingTask.id')
    expect(baselinePage).toContain('mergePlanningItemsBeforeSave')
    expect(baselinePage).toContain('getAlignedBaselineItemsBeforeSave')
    expect(baselinePage).toContain('计划条目刚被他人更新')
    expect(monthlyPage).toContain('mergePlanningItemsBeforeSave')
    expect(monthlyPage).toContain('getAlignedMonthlyItemsBeforeSave')
    expect(monthlyPage).toContain('月度计划条目刚被他人更新')
  })

  it('keeps planning table realtime events wired to light refresh without clobbering local edits', () => {
    const ganttView = readSource('src/pages/GanttView.tsx')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')
    const realtimeService = readSource('server/src/services/planningRealtimeEventService.ts')

    expect(realtimeService).toContain("type: 'planning.table.changed'")
    expect(ganttView).toContain("'task_list'")
    expect(baselinePage).toContain("lastRealtimeEvent.type !== 'planning.table.changed'")
    expect(baselinePage).toContain("String(lastRealtimeEvent.entityType ?? '').trim() !== 'baseline'")
    expect(baselinePage).toContain('historyCursorRef.current > 0')
    expect(monthlyPage).toContain("lastRealtimeEvent.type !== 'planning.table.changed'")
    expect(monthlyPage).toContain("String(lastRealtimeEvent.entityType ?? '').trim() !== 'monthly_plan'")
    expect(monthlyPage).toContain('resetMonthlyHistoryFromServer')
    expect(monthlyPage).toContain('if (isDirty) {')
  })

  it('keeps shared planning commits tied to the backend field registry version', () => {
    const ganttView = readSource('src/pages/GanttView.tsx')
    const ganttTaskCommitActions = readSource('src/pages/GanttView/useGanttTaskCommitActions.tsx')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')
    const fieldRegistryHook = readSource('src/hooks/usePlanningFieldRegistry.ts')

    expect(ganttView).toContain("usePlanningFieldRegistry(id, 'task_list')")
    expect(ganttTaskCommitActions).toContain('getTaskListFieldRegistryVersion')
    expect(baselinePage).toContain("usePlanningFieldRegistry(projectId, 'baseline')")
    expect(baselinePage).toContain('getBaselineFieldRegistryVersion')
    expect(monthlyPage).toContain("usePlanningFieldRegistry(projectId, 'monthly_plan')")
    expect(monthlyPage).toContain('getMonthlyFieldRegistryVersion')
    expect(ganttTaskCommitActions).toContain('fieldRegistryVersion: resolvedFieldRegistryVersion')
    expect(baselinePage).toContain('fieldRegistryVersion,')
    expect(monthlyPage).toContain('fieldRegistryVersion,')
    expect(fieldRegistryHook).toContain('const refetch = useCallback(() => fetchRegistry(true), [fetchRegistry])')
  })

  it('keeps baseline and monthly pages wired to shared instant validation before save', () => {
    const validationHook = readSource('src/hooks/usePlanningValidation.ts')
    const validationStrip = readSource('src/components/planning/PlanningValidationStrip.tsx')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')

    expect(validationHook).toContain('export function validatePlanningRows')
    expect(validationHook).toContain('任务名称')
    expect(validationStrip).toContain('表格校核')
    expect(baselinePage).toContain('usePlanningValidation(baselineValidationInputs')
    expect(baselinePage).toContain('data-baseline-editor-cell')
    expect(baselinePage).toContain('baselineValidation.blockCount > 0')
    expect(baselinePage).toContain('baseline-validation-strip')
    expect(monthlyPage).toContain('usePlanningValidation(monthlyValidationInputs')
    expect(monthlyPage).toContain('monthlyTableValidation.blockCount > 0')
    expect(monthlyPage).toContain('combinedValidationIssues')
    expect(monthlyPage).toContain('const hasBlockingIssues = monthlyConfirmabilityIssues.some')
    expect(monthlyPage).toContain('monthly-validation-strip')
  })

  it('keeps planning table export wired on all three shared planning surfaces', () => {
    const exportDialog = readSource('src/components/planning/PlanningExportDialog.tsx')
    const exportHelper = readSource('src/lib/planningExport.ts')
    const taskExport = readSource('src/pages/GanttView/taskExport.ts')
    const taskExportHook = readSource('src/pages/GanttView/useGanttTaskExport.ts')
    const ganttView = readSource('src/pages/GanttView.tsx')
    const ganttAuxiliaryDialogs = readSource('src/pages/GanttView/GanttAuxiliaryDialogs.tsx')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')

    expect(exportDialog).toContain("export type ExportScope = 'visible' | 'all'")
    expect(exportDialog).toContain("export type ExportFormat = 'xlsx' | 'csv'")
    expect(exportHelper).toContain('writePlanningTableExport')
    expect(ganttView).toContain('<GanttAuxiliaryDialogs')
    expect(ganttAuxiliaryDialogs).toContain('LazyPlanningExportDialog')
    expect(ganttAuxiliaryDialogs).toContain('exportDialogProps.open ? <LazyPlanningExportDialog')
    expect(ganttView).toContain('handleExportTaskList')
    expect(taskExportHook).toContain('readPlanningFieldConfigExtraColumns')
    expect(taskExport).toContain('TASK_EXPORT_KEY_BY_EXTRA_COLUMN')
    expect(baselinePage).toContain('<PlanningExportDialog')
    expect(baselinePage).toContain('data-testid="baseline-export-open"')
    expect(baselinePage).toContain('handleExportBaseline')
    expect(baselinePage).toContain('BASELINE_EXPORT_KEY_BY_EXTRA_COLUMN')
    expect(monthlyPage).toContain('<PlanningExportDialog')
    expect(monthlyPage).toContain('data-testid="monthly-plan-export-open"')
    expect(monthlyPage).toContain('handleExportMonthlyPlan')
    expect(monthlyPage).toContain('MONTHLY_EXPORT_KEY_BY_EXTRA_COLUMN')
  })

  it('keeps task-list imports aligned with v1.4.22.1 supported formats', () => {
    const taskListBusinessActions = readSource('src/pages/GanttView/TaskListBusinessActions.tsx')
    const taskListEmptyState = readSource('src/components/planning/TaskListEmptyState.tsx')

    for (const source of [taskListBusinessActions, taskListEmptyState]) {
      expect(source).toContain('.xlsx,.xls,.csv,.tsv,.xml')
      expect(source).toContain('application/xml')
      expect(source).toContain('text/xml')
      expect(source).not.toContain('.mpp')
    }
  })

  it('keeps shared planning tree field configuration available on plan entry tables', () => {
    const planningTreeView = readSource('src/components/planning/PlanningTreeView.tsx')
    const planTreeEditor = readSource('src/pages/planning/components/PlanTreeEditor.tsx')
    const ganttView = readSource('src/pages/GanttView.tsx')
    const ganttScopePreferences = readSource('src/pages/GanttView/useGanttScopePreferences.ts')
    const ganttRows = readSource('src/pages/GanttViewRows.tsx')
    const ganttTaskPlanningTreeAdapter = readSource('src/pages/GanttView/GanttTaskPlanningTreeAdapter.tsx')
    const taskListBusinessActions = readSource('src/pages/GanttView/TaskListBusinessActions.tsx')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')
    const fieldConfig = readSource('src/lib/planningFieldConfig.ts')

    expect(planningTreeView).toContain('字段配置')
    expect(planningTreeView).toContain('<PlanningColumnConfig')
    expect(planningTreeView).toContain('fieldConfigStorageKey')
    expect(planningTreeView).toContain('safeStorageSet')
    expect(planningTreeView).toContain('const availableExtraColumns = useMemo')
    expect(planningTreeView).toContain("if (isPlanEntryTable && column.key === 'actions') return false")
    expect(planningTreeView).toContain('const visibleExtraColumns = availableExtraColumns.filter')
    expect(planningTreeView).toContain('availableExtraColumns.length > 0 ? (')
    expect(planningTreeView).not.toContain('const visibleExtraColumns = isPlanEntryTable ? []')
    expect(fieldConfig).toContain('workbuddy_planning_field_config')
    expect(planTreeEditor).toContain('fieldRegistryFields={fieldRegistryFields}')
    expect(baselinePage).toContain("getPlanningFieldConfigStorageKey(projectId, 'baseline'")
    expect(monthlyPage).toContain("getPlanningFieldConfigStorageKey(projectId, 'monthly_plan'")
    expect(ganttView).toContain('useGanttScopePreferences({')
    expect(ganttScopePreferences).toContain("getPlanningFieldConfigStorageKey(projectId, 'task_list'")
    expect(ganttRows).toContain('<GanttTaskPlanningTreeAdapter')
    expect(ganttTaskPlanningTreeAdapter).toContain('toolbar')
    expect(ganttTaskPlanningTreeAdapter).toContain("enabledViews={['list', 'card', 'detail', 'gantt']}")
    expect(ganttTaskPlanningTreeAdapter).toContain('fieldRegistryFields={props.fieldRegistryFields}')
  })

  it('keeps shared planning tree collaboration signals in the common surface', () => {
    const planningTreeView = readSource('src/components/planning/PlanningTreeView.tsx')
    const presenceBar = readSource('src/components/planning/PlanningPresenceBar.tsx')
    const planTreeEditor = readSource('src/pages/planning/components/PlanTreeEditor.tsx')
    const ganttRows = readSource('src/pages/GanttViewRows.tsx')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const monthlyPage = readSource('src/pages/planning/MonthlyPlanPage.tsx')
    const ganttView = readSource('src/pages/GanttView.tsx')

    expect(presenceBar).toContain("data-testid=\"planning-presence-bar\"")
    expect(presenceBar).toContain('slice(0, 2)')
    expect(planningTreeView).toContain('<PlanningPresenceBar')
    expect(planningTreeView).toContain('const presenceSignals = useMemo<PresenceSignal[]>')
    expect(planningTreeView).toContain('dirtyCellMap?.size')
    expect(planTreeEditor).toContain('presence={presence}')
    expect(ganttRows).toContain('presence={props.presence}')
    expect(baselinePage).toContain('presence={baselinePresence}')
    expect(monthlyPage).toContain('presence={monthlyPresence}')
    expect(ganttView).toContain('presence={taskListPresence}')
  })

  it('keeps planning tree keyboard shortcut help in the shared toolbar without rebinding global shortcuts', () => {
    const planningTreeView = readSource('src/components/planning/PlanningTreeView.tsx')
    const shortcuts = readSource('src/components/planning/KeyboardShortcuts.tsx')

    expect(shortcuts).toContain('data-testid="planning-keyboard-shortcuts"')
    expect(planningTreeView).toContain('PLANNING_TREE_SHORTCUTS')
    expect(planningTreeView).toContain('<KeyboardShortcuts')
    expect(planningTreeView).toContain('enabled={false}')
    expect(planningTreeView).toContain('label="快捷键"')
    expect(planningTreeView).toContain('searchInputRef.current?.focus()')
    expect(planningTreeView).toContain("key === 'f'")
    expect(planningTreeView).toContain("isPlanEntryTable || searchKeyword || activeFilterCount > 0 || sortMode !== 'default'")
    expect(planningTreeView).toContain('data-testid="planning-start-edit"')
  })

  it('keeps lightweight first-use guidance scoped by user and planning surface', () => {
    const planningTreeView = readSource('src/components/planning/PlanningTreeView.tsx')
    const planningGuidance = readSource('src/lib/planningGuidance.ts')
    const planningGuideBubble = readSource('src/components/planning/PlanningGuideBubble.tsx')
    const editProfileDialog = readSource('src/components/EditProfileDialog.tsx')

    expect(planningGuideBubble).toContain('data-testid="planning-guide-bubble"')
    expect(planningGuideBubble).toContain('关闭共享计划树提示')
    expect(planningGuideBubble).toContain('pointer-events-none')
    expect(planningGuideBubble).toContain('pointer-events-auto')
    expect(planningGuidance).toContain('workbuddy_planning_guidance')
    expect(planningGuidance).toContain('PLANNING_GUIDANCE_AUTO_DISMISS_EDIT_COUNT = 5')
    expect(planningGuidance).toContain('PLANNING_GUIDANCE_AUTO_DISMISS_DAYS = 30')
    expect(planningGuidance).toContain('getPlanningGuidanceStorageKey')
    expect(planningGuidance).toContain('${normalizeUserId(userId)}:${surface}:${guideKey}')
    expect(planningGuidance).toContain('resetPlanningGuidanceForUser')
    expect(planningTreeView).toContain('useCurrentUser()')
    expect(planningTreeView).toContain('getPlanningGuidanceStorageKeys(currentUser?.id, guidanceSurface)')
    expect(planningTreeView).toContain("triggerPlanningGuide('paste')")
    expect(planningTreeView).toContain("triggerPlanningGuide('field_config')")
    expect(planningTreeView).toContain("triggerPlanningGuide('undo')")
    expect(planningTreeView).toContain('recordGuidanceCompletion()')
    expect(planningTreeView).toContain('点击编辑后，任务列表将在计划表工作台中打开，像一张工程计划表一样维护。')
    expect(planningTreeView).toContain("className: 'left-auto right-0'")
    expect(editProfileDialog).toContain('resetPlanningGuidanceForUser(user?.id)')
    expect(editProfileDialog).toContain('data-testid="reset-planning-guidance"')
    expect(editProfileDialog).toContain('重置共享计划树引导')
  })

  it('keeps row delete governance connected to the shared planning tree', () => {
    const deleteGuard = readSource('src/components/planning/PlanningDeleteGuard.ts')
    const planningTreeView = readSource('src/components/planning/PlanningTreeView.tsx')
    const ganttRows = readSource('src/pages/GanttViewRows.tsx')
    const baselinePage = readSource('src/pages/planning/BaselinePage.tsx')
    const planningShared = readSource('src/pages/planning/planningShared.tsx')

    expect(deleteGuard).toContain('evaluateDeleteDisposition')
    expect(deleteGuard).toContain('hasAcceptanceLinks')
    expect(planningTreeView).toContain('getDeleteDispositionForRow')
    expect(planningTreeView).toContain('getDeleteButtonDisabled(deleteDisposition)')
    expect(planningTreeView).toContain('selectedDeleteTooltip')
    expect(ganttRows).toContain('hasConditions: taskConditions.length > 0')
    expect(ganttRows).toContain('hasBlockages: taskObstacles.length > 0 || obstacleCount > 0')
    expect(ganttRows).toContain('hasAcceptanceLinks: acceptanceImpactItems.length > 0')
    expect(baselinePage).toContain('childCountByParentId')
    expect(planningShared).toContain('childCount: childCount.get(item.id) ?? 0')
  })

  it('keeps the v1.4.7.1 shared planning tree test harness available for all three surfaces', () => {
    const harness = readSource('src/test/planningTreeHarness.ts')

    expect(harness).toContain("export function mountSurface(")
    expect(harness).toContain("surface: PlanningSurface")
    expect(harness).toContain("enterEdit(): Promise<void>")
    expect(harness).toContain("editCell(rowId: string, field: string, value: unknown): Promise<void>")
    expect(harness).toContain("pasteAt(rowId: string, field: string, tsv: string): Promise<void>")
    expect(harness).toContain("clickSave(): Promise<PlanningTableCommitRequest>")
    expect(harness).toContain("fieldRegistryVersion: getRegistryVersion(options)")
    expect(harness).toContain("assertEditable(surface, field, options)")
  })

  it('keeps ordinary task-list entry points within the v1.4.7.1 task surface', () => {
    const ganttView = readSource('src/pages/GanttView.tsx')
    const ganttHeader = readSource('src/pages/GanttViewHeader.tsx')
    const ganttDialogs = readSource('src/pages/GanttViewDialogs.tsx')
    const ganttFilters = readSource('src/pages/GanttViewFilters.tsx')
    const ganttRows = readSource('src/pages/GanttViewRows.tsx')
    const ganttTaskPlanningTreeAdapter = readSource('src/pages/GanttView/GanttTaskPlanningTreeAdapter.tsx')
    const taskListBusinessActions = readSource('src/pages/GanttView/TaskListBusinessActions.tsx')
    const ganttRowSections = readSource('src/pages/GanttViewRowSections.tsx')
    const ganttTaskTableActions = readSource('src/pages/GanttView/useGanttTaskTableActions.ts')
    const ganttBusinessActionSlots = readSource('src/pages/GanttView/useGanttBusinessActionSlots.tsx')
    const ganttTaskCommitActions = readSource('src/pages/GanttView/useGanttTaskCommitActions.tsx')
    const ganttTaskDialogActions = readSource('src/pages/GanttView/useGanttTaskDialogActions.ts')
    const ganttTaskRowInlineParts = readSource('src/pages/GanttView/GanttTaskRowInlineParts.tsx')
    const ganttDeleteGuardActions = readSource('src/pages/GanttView/useGanttDeleteGuardActions.ts')
    const taskDraftUtils = readSource('src/pages/GanttView/taskDraftUtils.ts')
    const taskExport = readSource('src/pages/GanttView/taskExport.ts')
    const taskExportHook = readSource('src/pages/GanttView/useGanttTaskExport.ts')
    const ganttDetailDrawer = readSource('src/pages/GanttView/GanttDetailDrawer.tsx')
    const participantUnitApi = readSource('src/pages/GanttView/participantUnitApi.ts')
    const participantUnitActions = readSource('src/pages/GanttView/useGanttParticipantUnitActions.ts')
    const ganttScopePreferences = readSource('src/pages/GanttView/useGanttScopePreferences.ts')
    const ganttWorkspaceChrome = readSource('src/pages/GanttView/GanttWorkspaceChrome.tsx')
    const planningTreeView = readSource('src/components/planning/PlanningTreeView.tsx')
    const predecessorSelector = readSource('src/components/planning/PredecessorSelector.tsx')
    const planningChipBand = readSource('src/components/planning/PlanningChipBand.tsx')
    const planningRowGutter = readSource('src/components/planning/PlanningRowGutter.tsx')
    const planningPrecedingBadge = readSource('src/components/planning/PlanningPrecedingBadge.tsx')
    const blockageListPopover = readSource('src/components/planning/blockages/BlockageListPopover.tsx')
    const conditionListPopover = readSource('src/components/planning/conditions/ConditionListPopover.tsx')
    const planningAssigneeLookup = readSource('src/components/planning/lookups/AssigneeCombobox.tsx')
    const precedingTaskLookup = readSource('src/components/planning/lookups/PrecedingTaskLookup.tsx')
    const milestoneLevelPicker = readSource('src/components/planning/milestones/MilestoneLevelPicker.tsx')
    const riskManagement = readSource('src/pages/RiskManagement.tsx')
    const planningScopeHook = readSource('src/hooks/usePlanningScope.ts')
    const useGroupMode = readSource('src/hooks/useGroupMode.ts')
    const groupModeToggle = readSource('src/components/planning/GroupModeToggle.tsx')
    const taskListProjection = readSource('src/pages/GanttView/taskListProjection.ts')
    const taskTimelineView = readSource('src/pages/GanttView/TaskTimelineView.tsx')
    const saveTaskSegment = ganttTaskDialogActions.slice(
      ganttTaskDialogActions.indexOf('const handleSaveTask = useCallback(async () => {'),
      ganttTaskDialogActions.indexOf('const openEditDialog'),
    )

    expect(ganttView).toContain('commitTaskListOperations')
    expect(saveTaskSegment).not.toContain('actual_start_date')
    expect(saveTaskSegment).not.toContain('actual_end_date')
    expect(saveTaskSegment).not.toContain('first_progress_at')
    expect(saveTaskSegment).toContain('enqueueTaskTableDraftPatch(editingTask.id')
    expect(saveTaskSegment).toContain('__draftCreated: true')
    expect(saveTaskSegment).not.toContain("type: 'create_row'")
    expect(saveTaskSegment).not.toContain('applyCommittedTaskRows')
    expect(ganttRows).not.toContain('onRequestComplete')
    expect(ganttRows).not.toContain('onBlur')
    expect(ganttRowSections).not.toContain('onBlur')
    expect(ganttTaskRowInlineParts).toContain('function usePreservedRealtimeDraft')
    expect(ganttTaskRowInlineParts).toContain('return current === previousNormalized ? normalized : current')
    expect(ganttRows).toContain('const tableEditAllowed = Boolean(props.canEdit && props.taskDraftEditing)')
    expect(ganttRows).toContain('onAddChild: tableEditAllowed')
    expect(ganttRows).toContain('disabled={!tableEditAllowed}')
    expect(ganttRows).toContain("durationSuggestionQuery: tableEditAllowed && isScheduleCellActive")
    expect(ganttRows).toContain('readOnly={false}')
    expect(ganttRows).toContain('<GanttTaskPlanningTreeAdapter')
    expect(ganttTaskPlanningTreeAdapter).toContain('rowMode={props.taskDraftEditing ? \'edit\' : \'read\'}')
    expect(ganttTaskPlanningTreeAdapter).toContain('onStartEdit={props.onStartTaskDraft}')
    expect(ganttTaskPlanningTreeAdapter).toContain('saveDisabled={!props.taskDraftDirtyCount}')
    expect(ganttTaskPlanningTreeAdapter).toContain('data-testid="gantt-task-list-toolbar"')
    expect(ganttTaskPlanningTreeAdapter).toContain('showEditModeToolbar')
    expect(ganttTaskPlanningTreeAdapter).toContain("toolbarMode={props.taskDraftEditing ? 'full' : 'task_read'}")
    expect(planningTreeView).toContain("toolbarMode?: 'full' | 'task_read'")
    expect(planningTreeView).toContain('const isTaskReadToolbar = resolvedToolbarMode ===')
    expect(planningTreeView).toContain('renderEditModeToolbar({ largeView: true })')
    expect(planningTreeView).toContain('onClick={() => void copyRowsToClipboard()}')
    expect(planningTreeView).toContain('onClick={() => void pasteRowsFromClipboard()}')
    expect(planningTreeView).toContain('<KeyboardShortcuts')
    expect(ganttBusinessActionSlots).toContain('onOpenFilters?: () => void')
    expect(ganttBusinessActionSlots).toContain('onOpenFilters={onOpenFilters}')
    expect(taskListBusinessActions).toContain('data-testid="gantt-open-task-filters"')
    expect(taskListBusinessActions).toContain('data-testid="gantt-task-list-light-more"')
    expect(taskListBusinessActions).toContain('data-testid="gantt-generation-template-menu"')
    expect(ganttWorkspaceChrome).toContain('<Sheet open={showFilterBar} onOpenChange={setShowFilterBar}>')
    expect(ganttWorkspaceChrome).not.toContain('点击展开筛选')
    expect(taskDraftUtils).toContain('__draftDeleted?: boolean')
    expect(ganttView).toContain('taskTableDraftDeletedIds')
    expect(taskDraftUtils).toContain("type: 'delete_row' as const")
    expect(taskDraftUtils).toContain("type: 'move_row' as const")
    expect(taskDraftUtils).toContain("type: 'set_predecessors' as const")
    expect(taskDraftUtils).toContain('normalizeTaskDraftDependencyIds')
    expect(ganttTaskTableActions).toContain('已暂存排序调整')
    expect(ganttView).not.toContain('void commitTaskListOperations(reordered')
    expect(ganttTaskTableActions).toContain('handleDeleteTaskRows(Array.from(selectedIds))')
    expect(ganttTaskTableActions).toContain('保存编辑前可撤销或取消。')
    expect(ganttRows).toContain('getTaskScopeLabel')
    expect(ganttRows).toContain("props.onOpenDetailDrawer?.(task, 'scope')")
    expect(ganttView).toContain('engineeringObjectLabelsById={engineeringObjectLabelsById}')
    expect(ganttView).toContain('useGanttScopePreferences({')
    expect(ganttScopePreferences).toContain('usePlanningScope({')
    expect(planningScopeHook).toContain('TASK_SCOPE_SELECTION_STORAGE_PREFIX')
    expect(planningScopeHook).toContain('readStoredTaskScopeSelection')
    expect(planningScopeHook).toContain('getTaskScopePatchFromSelection')
    expect(ganttTaskDialogActions).toContain('inheritedScopePatch')
    expect(ganttFilters).toContain('gantt-batch-apply-scope')
    expect(ganttFilters).toContain('应用当前作用域')
    expect(ganttFilters).toContain('gantt-bulk-progress-input')
    expect(ganttFilters).toContain('目标进度')
    expect(ganttView).toContain('handleApplyBatchUpdate(activeTaskScopePatch)')
    expect(taskDraftUtils).toContain('payload.progress')
    expect(taskDraftUtils).toContain("patch.status = progress >= 100 ? 'completed' : progress > 0 ? 'in_progress' : 'todo'")
    expect(ganttTaskTableActions).toContain('!taskTableEditing')
    expect(ganttTaskTableActions).toContain('recordTaskTableDraftPatches((current) =>')
    expect(ganttTaskTableActions).toContain('批量更新已加入表格编辑')
    expect(ganttView).toContain('canBatchEdit={taskTableEditing}')
    expect(ganttFilters).toContain('canBatchEdit?: boolean')
    expect(ganttFilters).toContain('disabled={batchUpdating || !canBatchEdit')

    expect(planningTreeView).toContain('startingLineClass?:')
    expect(planningTreeView).toContain('reconcilePhase?:')
    expect(planningTreeView).toContain('defaultCollapseDepth?: number')
    expect(planningTreeView).toContain('initializeCollapsedRows')
    expect(planningTreeView).toContain('getStartingLineRowClass')
    expect(planningTreeView).toContain('History className')
    expect(planningTreeView).toContain('Play className')
    expect(planningTreeView).toContain('getReconcileRowStyle(row.reconcilePhase)')
    expect(planningTreeView).toContain("row.reconcilePhase === 'rename_suggest'")
    expect(planningTreeView).toContain('onReconcileEntryAction?:')

    expect(ganttRows).toContain('getTaskStartingLineClass')
    expect(ganttRows).toContain('standardTaskMetadata.is_historical')
    expect(ganttRows).toContain('standardTaskMetadata.onboarding_stage_classification')
    expect(ganttRows).toContain('reconcilePhase')
    expect(ganttRows).toContain('defaultCollapseDepth={2}')
    expect(ganttRows).toContain('reconcileEntries={props.reconcileEntries}')
    expect(ganttRows).toContain('onReconcileEntryAction={props.onReconcileEntryAction}')

    expect(ganttTaskDialogActions).toContain('lastManualTaskScopeRef')
    expect(ganttTaskDialogActions).toContain('readTaskManualScopePatch')
    expect(ganttTaskDialogActions).toContain('lastManualTaskScopeRef.current =')
    expect(ganttTaskDialogActions).toContain('...lastManualTaskScopeRef.current')
    expect(ganttView).toContain('<GanttWorkspaceChrome')
    expect(ganttWorkspaceChrome).toContain('PlanningHealthBanner')
    expect(ganttWorkspaceChrome).toContain('gantt-risk-issue-filter-banner')
    expect(riskManagement).toContain("query.get('taskId')")
    expect(riskManagement).toContain('setWorkspaceSearch(taskId)')
    expect(ganttView).toContain('handleQuickAddTaskObstacle')
    expect(ganttDialogs).toContain('normalizeObstacleSeverity')
    expect(ganttDialogs).toContain('<SelectItem value="low">低</SelectItem>')
    expect(ganttDialogs).toContain('<SelectItem value="medium">中</SelectItem>')
    expect(ganttDialogs).toContain('<SelectItem value="high">高</SelectItem>')
    expect(ganttDialogs).toContain('disabled={!props.newObstacleTitle.trim() || !props.newObstacleExpectedResolutionDate}')
    expect(ganttDialogs).not.toContain('<SelectItem value="严重">严重</SelectItem>')
    expect(ganttDetailDrawer).toContain('if (onOpenTemplateGenerate)')
    expect(ganttDetailDrawer).toContain('onOpenTemplateGenerate()')
    expect(ganttView).toContain('handleLightRefresh')
    expect(ganttDeleteGuardActions).toContain('refreshGanttProjectData({ includeSummary: true })')
    expect(ganttHeader).toContain('gantt-light-refresh')
    expect(ganttHeader).toContain("refreshing ? '刷新中' : '刷新'")
    expect(ganttView).not.toContain('taskRowDensity')
    expect(ganttBusinessActionSlots).toContain('setExportOpen(true)')
    expect(ganttBusinessActionSlots).toContain('onOpenExport={openExport}')
    expect(ganttView).toContain('open: exportOpen')
    expect(ganttView).toContain('handleExportTaskList(scope, format)')
    expect(taskExport).toContain('TASK_EXPORT_COLUMNS')
    expect(taskExportHook).toContain('getTaskExportColumns(scope, visibleExtraColumns)')
    expect(taskExportHook).toContain('已导出当前 ${rows.length} 行、${exportedColumnCount} 个字段。')
    expect(ganttView).not.toContain("const exportRows = scope === 'visible' ? filteredFlatList : flatList")
    expect(ganttView).toContain('handleAddFirstTaskRow')
    expect(ganttView).toContain('onAddFirstRow={handleAddFirstTaskRow}')
    expect(ganttView).toContain('handleOpenTaskListWizard')
    expect(ganttView).toContain("openModelingWorkbench(task ? 'expand' : 'generate', task?.id)")
    expect(ganttView).toContain("nextSearch.set('taskPlanTaskId', taskId)")
    expect(ganttView).toContain('handleOpenTemplateAdjustWizard')
    expect(ganttView).toContain("openModelingWorkbench('adjust')")
    expect(ganttView).not.toContain('/projects/new')
    expect(ganttView).toContain('modelingWorkbench')
    expect(ganttView).toContain('PlanningModelingWorkbenchDialog')
    expect(ganttView).toContain('onOpenTaskListWizard: handleOpenTaskListWizard')
    expect(ganttView).toContain('onOpenReconcile: handleOpenTemplateAdjustWizard')
    expect(ganttView).toContain('onGenerateTasks={handleOpenTaskListWizard}')
    expect(ganttView).not.toContain('onGenerateTasks={() => setTemplateGenerateOpen(true)}')
    expect(ganttBusinessActionSlots).toContain('onOpenTaskListWizard: () => void')
    expect(ganttBusinessActionSlots).toContain('onGenerateTasks={onOpenTaskListWizard}')
    expect(ganttBusinessActionSlots).not.toContain('setTemplateGenerateOpen')
    expect(ganttBusinessActionSlots).not.toContain('openTemplateGenerate')
    expect(taskDraftUtils).toContain('__draftCreated?: boolean')
    expect(ganttView).toContain('taskTableDraftRows')
    expect(ganttTaskTableActions).toContain('已新增首行草稿')
    expect(ganttTaskTableActions).toContain('已粘贴 ${createdIds.length} 个任务草稿')
    expect(taskDraftUtils).toContain("clientRowId: taskId")
    expect(ganttTaskTableActions).toContain('setInlineTitleTaskId(clientRowId)')
    expect(ganttRows).toContain('onGenerateTasks={props.onGenerateTasks}')
    expect(ganttRows).toContain('onAddFirstRow={props.onAddFirstRow ?? (() => props.onOpenEditDialog())}')
    expect(ganttTaskRowInlineParts).toContain('AssigneeCombobox')
    expect(ganttTaskRowInlineParts).toContain('task-row-assignee-combobox')
    expect(ganttView).toContain('projectMembers={projectMembers}')
    expect(ganttTaskRowInlineParts).toContain('task-inline-blockage-popover')
    expect(ganttTaskRowInlineParts).toContain('task-blockage-chip-popover')
    expect(ganttRows).toContain('isActiveTaskObstacle')
    expect(ganttView).toContain('taskObstacles={scopedProjectObstacles}')
    expect(ganttTaskRowInlineParts).toContain('task-inline-condition-popover')
    expect(ganttTaskRowInlineParts).toContain('task-condition-chip-popover')
    expect(ganttTaskRowInlineParts).toContain('toInlineConditionItems')
    expect(ganttTaskRowInlineParts).toContain('condition && !isHardCondition(condition)')
    expect(ganttRows).toContain('task-hard-condition-blocked')
    expect(ganttRows).toContain('项硬条件未满足')
    expect(ganttRows).toContain('getTaskConditionBreakdown')
    expect(ganttTaskRowInlineParts).toContain('conditionBreakdown.hardSatisfied')
    expect(ganttTaskRowInlineParts).toContain('conditionBreakdown.softSatisfied')
    expect(ganttView).toContain('taskConditions={scopedProjectConditions}')
    expect(ganttWorkspaceChrome).toContain('readOnly={canEdit === false}')
    expect(participantUnitApi).toContain("unit_type: draft.unit_type.trim() || '其他'")
    expect(participantUnitActions).toContain("toast({ title: '请先填写单位名称'")
    expect(ganttTaskRowInlineParts).toContain('QuickBlockageForm')
    expect(ganttTaskRowInlineParts).toContain('BlockageListPopover')
    expect(ganttTaskRowInlineParts).toContain('ConditionListPopover')
    expect(blockageListPopover).toContain('data-testid="blockage-list-popover"')
    expect(conditionListPopover).toContain('data-testid="condition-list-popover"')
    expect(ganttTaskPlanningTreeAdapter).toContain('gantt-task-list-toolbar')
    expect(ganttTaskPlanningTreeAdapter).toContain('GroupModeToggle')
    expect(useGroupMode).toContain("export type GroupMode = 'execution' | 'spatial'")
    expect(useGroupMode).toContain("return stored === 'spatial' ? 'spatial' : 'execution'")
    expect(groupModeToggle).toContain('planning-group-mode-execution')
    expect(groupModeToggle).toContain('按执行')
    expect(groupModeToggle).not.toContain('planning-group-mode-wbs')
    expect(groupModeToggle).not.toContain('按 WBS')
    expect(taskListProjection).toContain('shouldShowTaskInMainExecutionList')
    expect(taskListProjection).toContain("planItemKind === 'linked_projection'")
    expect(ganttRows).toContain('visibleExecutionFlatList')
    expect(ganttRows).toContain('compareTasksByExecutionOrder')
    expect(ganttRows).toContain('const showTreeExpander = false')
    expect(ganttView).toContain('mainExecutionRows')
    expect(ganttView).toContain('filteredFlatList: mainExecutionRows')
    expect(ganttView).toContain('rows={mainExecutionRows}')
    expect(taskTimelineView).toContain('executionRows')
    expect(taskTimelineView).toContain('[...rows].sort(compareTasksByExecutionOrder)')
    expect(ganttTaskPlanningTreeAdapter).toContain('density="comfortable"')
    expect(ganttTaskPlanningTreeAdapter).not.toContain('gantt-row-density')
    expect(taskListBusinessActions).toContain('gantt-open-export-dialog')
    expect(ganttBusinessActionSlots).toContain('onOpenExport={openExport}')
    expect(ganttTaskRowInlineParts).toContain('PlanningChipBand')
    expect(planningChipBand).toContain('data-testid="planning-chip-band"')
    expect(planningTreeView).toContain('PlanningTreeDensity')
    expect(planningTreeView).toContain('density?: PlanningTreeDensity')
    expect(planningTreeView).toContain('PlanningRowGutter')
    expect(planningRowGutter).toContain('data-testid="planning-row-gutter"')
    expect(ganttRows).toContain('sequenceLabel: task.wbs_code || String(rowIndex + 1)')
    expect(planningTreeView).toContain('onOpenCriticalPath?:')
    expect(planningTreeView).toContain('planning-row-open-critical-path')
    expect(planningTreeView).toContain('planning-row-change-node-type')
    expect(ganttRows).toContain('wbs_node_type: nodeType')
    expect(ganttRows).toContain('onOpenCriticalPath?:')
    expect(ganttRows).toContain('onRemoveCriticalPathAttention')
    expect(ganttView).toContain('onOpenCriticalPath={(taskId) => handleOpenCriticalPathDialog(taskId)}')
    expect(ganttWorkspaceChrome).toContain('CriticalPathAlert')
    expect(ganttView).toContain('criticalPathChangeNotice')
    expect(ganttTaskCommitActions).toContain('setCriticalPathChangeNotice({ enteredCount, leftCount, focusTaskId })')
    expect(ganttDialogs).toContain('PredecessorSelector')
    expect(ganttRows).toContain('PredecessorSelector')
    expect(predecessorSelector).toContain('PlanningPrecedingBadge')
    expect(planningPrecedingBadge).toContain('data-testid="planning-preceding-badge"')
    expect(planningAssigneeLookup).toContain('AssigneeCombobox')
    expect(precedingTaskLookup).toContain('PrecedingTaskLookup')
    expect(milestoneLevelPicker).toContain('MilestoneLevelPicker')
    expect(predecessorSelector).toContain('predecessor-selector-advanced-toggle')
    expect(predecessorSelector).toContain('predecessor-selector-advanced-panel')
    expect(ganttRows).toContain('getAvailablePredecessors')
    expect(ganttRows).toContain('getDependencyChain(candidateId, taskMap).has(taskId)')
    expect(ganttRows).toContain("dependencies: [...predecessorIds, taskId]")
    expect(ganttDialogs).toContain('handleDependencyChange(taskId, true)')
    expect(ganttRows).toContain('Boolean(criticalTask)')
    expect(planningTreeView).toContain('isTaskTable && row.isCritical')
    expect(ganttView).not.toContain('gantt-complete-task-confirm-dialog')
    expect(ganttHeader).not.toContain('gantt-open-task-summary')
    expect(ganttHeader).not.toContain('gantt-closeout-entry')
    expect(ganttHeader).not.toContain('gantt-create-task')
    expect(ganttView).not.toContain('onCreateTask={() => openEditDialog()}')
    expect(ganttDialogs).not.toContain('新建任务')
    expect(ganttDialogs).not.toContain('AI ڽ')
    expect(ganttDialogs).not.toMatch(/\/api\/ai[-]duration\/estimate[-]duration/)
    expect(ganttDialogs).not.toContain('onOpenRiskWorkspaceForObstacle')
  })

  it('keeps task-list acceptance impact read-only and routed through the detail drawer', () => {
    const ganttView = readSource('src/pages/GanttView.tsx')
    const ganttRows = readSource('src/pages/GanttViewRows.tsx')
    const ganttTaskRowInlineParts = readSource('src/pages/GanttView/GanttTaskRowInlineParts.tsx')
    const taskTypes = readSource('src/pages/GanttViewTypes.ts')
    const tasksRoute = readSource('server/src/routes/tasks.ts')
    const drawerSections = readSource('src/components/planning/DrawerSections.tsx')
    const ganttDetailDrawer = readSource('src/pages/GanttView/GanttDetailDrawer.tsx')
    const ganttConditionActions = readSource('src/pages/GanttView/useGanttConditionActions.ts')
    const inlinePopover = readSource('src/components/planning/PlanningInlinePopover.tsx')
    const templateInlineExpand = readSource('src/components/planning/TemplateInlineExpand.tsx')

    expect(taskTypes).toContain('acceptance_impact_summary?: TaskAcceptanceImpactItem[]')
    expect(tasksRoute).toContain('acceptance_impact_summary')
    expect(tasksRoute).toContain("relation_type = 'covers_task'")
    expect(tasksRoute).toContain('attachAcceptanceImpactSummaries')
    expect(ganttTaskRowInlineParts).toContain('AcceptanceImpactChip')
    expect(ganttRows).toContain('TaskIssueChipBand')
    expect(ganttRows).not.toContain('关联风险')
    expect(ganttRows).not.toContain('关联问题')
    expect(ganttTaskRowInlineParts).toContain("handleOpen('acceptance')")
    expect(ganttTaskRowInlineParts).toContain("section: 'blockages'")
    expect(ganttTaskRowInlineParts).toContain("section: 'conditions'")
    expect(ganttTaskRowInlineParts).not.toContain("section: 'predecessors'")
    expect(ganttRows).toContain('PredecessorSelector')
    expect(ganttTaskRowInlineParts).toContain('task-inline-blockage-popover')
    expect(ganttTaskRowInlineParts).toContain('task-inline-condition-popover')
    expect(ganttView).toContain('GanttDetailDrawer')
    expect(ganttDetailDrawer).toContain('PlanningDetailDrawer')
    expect(ganttConditionActions).toContain('setExpandedConditionTaskId(null)')
    expect(ganttView).toContain("switchPlanningDetailDrawerTask('previous')")
    expect(ganttView).toContain("switchPlanningDetailDrawerTask('next')")
    expect(drawerSections).toContain('ConditionDrawerSection')
    expect(ganttDetailDrawer).toContain('BlockageDrawerSection')
    expect(ganttDetailDrawer).toContain('ConditionDrawerSection')
    expect(ganttDetailDrawer).toContain('renderScope={() =>')
    expect(ganttDetailDrawer).toContain('renderConditions={() =>')
    expect(ganttDetailDrawer).toContain('onLoadFromTemplate={() =>')
    expect(ganttDetailDrawer).toContain('if (onOpenTemplateGenerate)')
    expect(ganttDetailDrawer).toContain('onOpenTemplateGenerate()')
    expect(templateInlineExpand).toContain('data-testid="template-inline-expand"')
    expect(templateInlineExpand).toContain('generateWbsTemplatePreview')
    expect(ganttDetailDrawer).not.toContain('/wbs-templates')
    expect(drawerSections).toContain('从模板批量挂载')
    expect(ganttDetailDrawer).toContain('renderBlockages={() =>')
    expect(ganttDetailDrawer).toContain('renderPredecessors={() =>')
    expect(ganttDetailDrawer).toContain('renderAcceptance={() =>')
    expect(ganttDetailDrawer).toContain('renderSource={() =>')
    expect(ganttView).toContain('relatedRiskIssueSummaryByTaskId')
    expect(ganttDetailDrawer).toContain('task-related-risk-issue-summary')
    expect(ganttDetailDrawer).toContain('/acceptance?planId=')
    expect(drawerSections).toContain('expectedResolutionDate')
    expect(drawerSections).toContain('disabled={!newDesc.trim() || !newExpectedResolutionDate}')
    expect(inlinePopover).toContain('expectedResolution?: string')
    expect(inlinePopover).toContain('aria-label="预计解除日期，可选"')
    expect(inlinePopover).toContain('disabled={!description.trim()}')
    expect(ganttView).not.toContain('updateStatus(')
  })

  it('keeps realtime presence reminder-only on the websocket server', () => {
    const realtimeServer = readSource('server/src/services/realtimeServer.ts')

    expect(realtimeServer).toContain('planning.presence.update')
    expect(realtimeServer).toContain('planning.presence.changed')
    expect(realtimeServer).toContain('broadcastPlanningPresence')
    expect(realtimeServer).not.toContain('planning.presence.lock')
  })

  it('documents that CRDT, cell logs, and batch operation logs are not in this phase', () => {
    const doc = readSource('docs/plans/v1.3.5.3视觉精调.md')

    expect(doc).toContain('不引入 CRDT/OT')
    expect(doc).toContain('单元格级操作日志本轮不做')
    expect(doc).toContain('批量操作日志本轮也不做')
  })
})
