import type { DefaultMasterPlanVisibilityPolicyRecord } from '../services/defaultMasterPlanVisibilityService.js'

export const DEFAULT_MASTER_PLAN_VISIBILITY_POLICY_SEED_VERSION = 'v1.4.23.1-master-plan-visibility-v1'

export const DEFAULT_MASTER_PLAN_VISIBILITY_POLICY_SEED: DefaultMasterPlanVisibilityPolicyRecord[] = [
  {
    stableCode: 'master-plan-hide-industrial-interleaved-equipment-packages',
    businessTypes: ['industrial'],
    targetStableCodePatterns: ['^IPL-(02-01-01|03-01-01|03-01-02)$'],
    visibilityClass: 'detail_plan_only',
    visibleOnMasterPlan: false,
    priority: 1_000,
    source: 'system_visibility_seed',
    isActive: true,
    evidenceSourceKeys: ['v1.4.23.1.process_level_interleaving_not_whole_package_sequence'],
    sourceStandard: 'v1.4.23.1_default_master_plan_terminal_architecture',
    sourceVersion: 'v1.4.23.1',
    sourceClauseRef: 'process_level_interleaving_not_whole_package_sequence',
    webVerified: false,
    reviewNeeded: false,
  },
  {
    stableCode: 'master-plan-visible-managed-frontier-profile',
    businessTypes: [],
    targetSourcePatterns: ['^managed_frontier_default_master_plan$'],
    visibilityClass: 'primary_control',
    visibleOnMasterPlan: true,
    priority: 900,
    source: 'system_visibility_seed',
    isActive: true,
    evidenceSourceKeys: ['v1.4.23.1.default_master_plan_control_profile'],
    sourceStandard: 'v1.4.23.1_default_master_plan_terminal_architecture',
    sourceVersion: 'v1.4.23.1',
    sourceClauseRef: 'default_master_plan_control_profile',
    webVerified: false,
    reviewNeeded: false,
  },
  {
    stableCode: 'master-plan-hide-residential-startup-detail',
    businessTypes: ['general_civil'],
    targetStableCodePatterns: ['^RMP-01-(02|03|04|05|06)$'],
    visibilityClass: 'internal_network_constraint',
    visibleOnMasterPlan: false,
    priority: 800,
    source: 'system_visibility_seed',
    isActive: true,
    evidenceSourceKeys: ['v1.4.23.1.resources_are_sidecar_not_primary_schedule'],
    sourceStandard: 'v1.4.23.1_default_master_plan_terminal_architecture',
    sourceVersion: 'v1.4.23.1',
    sourceClauseRef: 'resources_are_sidecar_not_primary_schedule',
    webVerified: false,
    reviewNeeded: false,
  },
  {
    stableCode: 'master-plan-hide-residential-construction-hoist',
    businessTypes: ['general_civil'],
    targetStableCodePatterns: ['^RMP-10-01$'],
    visibilityClass: 'internal_network_constraint',
    visibleOnMasterPlan: false,
    priority: 800,
    source: 'system_visibility_seed',
    isActive: true,
    evidenceSourceKeys: ['v1.4.23.1.resources_are_sidecar_not_primary_schedule'],
    sourceStandard: 'v1.4.23.1_default_master_plan_terminal_architecture',
    sourceVersion: 'v1.4.23.1',
    sourceClauseRef: 'resources_are_sidecar_not_primary_schedule',
    webVerified: false,
    reviewNeeded: false,
  },
]

export const DEFAULT_MASTER_PLAN_VISIBILITY_POLICY_SEED_META = {
  seedVersion: DEFAULT_MASTER_PLAN_VISIBILITY_POLICY_SEED_VERSION,
  seedScope: 'master_plan_visibility_policy',
  sourceStandards: [
    'v1.4.23.1_default_master_plan_terminal_architecture',
    'construction_master_schedule_control_level_practice',
  ],
  expectedCounts: { records: DEFAULT_MASTER_PLAN_VISIBILITY_POLICY_SEED.length },
  evidenceSources: [
    {
      sourceKey: 'v1.4.23.1.default_master_plan_visibility',
      title: 'Default master plan visible control layer and hidden calculation network',
      sourceType: 'governed_internal_architecture',
    },
  ],
  generationPolicy: 'rule_seed_only; deterministic visibility classification; governed records may override non-protected rows; contractual gates are fail-safe visible',
  relationshipRole: 'master_plan_visibility_policy',
  upstreamRuleTypes: ['wizard_project_facts', 'default_master_plan_profile', 'pm_visibility_feedback'],
  downstreamRuleTypes: ['wbs_template_generation', 'executable_default_master_plan_assembly'],
  boundaryPolicy: [
    'classification_only_no_task_or_dependency_write',
    'pm_feedback_candidate_only_until_governed_publication',
    'protected_commitment_rows_never_auto_hidden',
  ],
  webVerified: false,
  reviewNeeded: false,
} as const
