export type V1474SeedEvidenceSource = {
  sourceKey: string
  title: string
  url: string
  accessedAt: string
}

export type V1474HolidayWindow = {
  holidayCode: string
  holidayName: string
  year: number
  month: number
  startDate: string
  endDate: string
  adjustedWorkDates: string[]
  productivity: number
  isCompensatoryWorkday: boolean
  adjustmentOrigin: string
  calendarKind:
    | 'statutory_holiday'
    | 'compensatory_workday'
    | 'forecast_calendar_window'
    | 'spring_festival_remobilization'
    | 'winter_shutdown'
    | 'plum_rain_window'
    | 'hot_summer_window'
    | 'dust_storm_window'
  sourceStandard: 'national_calendar' | 'system_default'
  sourceVersion: string
  sourceClauseRef: string
  evidenceSourceKeys: string[]
  webVerified: boolean
  reviewNeeded: boolean
  confidence: 'high' | 'medium' | 'low'
}

export const V1474_WORK_CALENDAR_SEED_VERSION = 'v1.4.7.4-calendar-fields-20260518'

export const V1474_WORK_CALENDAR_EVIDENCE_SOURCES: V1474SeedEvidenceSource[] = [
  {
    sourceKey: 'STATE_COUNCIL_HOLIDAY_2026',
    title: '国务院办公厅关于2026年部分节假日安排的通知',
    url: 'https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm',
    accessedAt: '2026-05-16',
  },
  {
    sourceKey: 'FORECAST_HOLIDAY_2027',
    title: '2027 statutory holiday forecast pending State Council notice',
    url: 'internal://workbuddy/calendar-forecast/2027',
    accessedAt: '2026-05-23',
  },
  {
    sourceKey: 'CONSTRUCTION_CLIMATE_CALENDAR_WINDOWS_2026',
    title: 'WorkBuddy construction climate planning windows for plum rain, hot summer and northwest dust storm',
    url: 'internal://workbuddy/calendar-climate-windows/2026',
    accessedAt: '2026-05-24',
  },
]

export const V1474_WORK_CALENDAR_SEED: V1474HolidayWindow[] = [
  {
    holidayCode: 'new_year_day_2026',
    holidayName: '2026 New Year holiday',
    year: 2026,
    month: 1,
    startDate: '2026-01-01',
    endDate: '2026-01-03',
    adjustedWorkDates: ['2026-01-04'],
    productivity: 0.9,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm',
    calendarKind: 'statutory_holiday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 New Year: Jan 1 to Jan 3 holiday; Jan 4 adjusted workday',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'spring_festival_2026',
    holidayName: '2026 Spring Festival construction window',
    year: 2026,
    month: 2,
    startDate: '2026-02-15',
    endDate: '2026-02-23',
    adjustedWorkDates: ['2026-02-14', '2026-02-28'],
    productivity: 0.35,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm',
    calendarKind: 'statutory_holiday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 Spring Festival: Feb 15 to Feb 23 holiday; Feb 14 and Feb 28 adjusted workdays',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'qingming_2026',
    holidayName: '2026 Qingming holiday',
    year: 2026,
    month: 4,
    startDate: '2026-04-04',
    endDate: '2026-04-06',
    adjustedWorkDates: [],
    productivity: 0.9,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm',
    calendarKind: 'statutory_holiday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 Qingming: Apr 4 to Apr 6 holiday',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'labor_day_2026',
    holidayName: '2026 Labor Day holiday',
    year: 2026,
    month: 5,
    startDate: '2026-05-01',
    endDate: '2026-05-05',
    adjustedWorkDates: ['2026-05-09'],
    productivity: 0.84,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm',
    calendarKind: 'statutory_holiday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 Labor Day: May 1 to May 5 holiday; May 9 adjusted workday',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'dragon_boat_2026',
    holidayName: '2026 Dragon Boat Festival holiday',
    year: 2026,
    month: 6,
    startDate: '2026-06-19',
    endDate: '2026-06-21',
    adjustedWorkDates: [],
    productivity: 0.9,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm',
    calendarKind: 'statutory_holiday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 Dragon Boat Festival: Jun 19 to Jun 21 holiday',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'mid_autumn_2026',
    holidayName: '2026 Mid-Autumn Festival holiday',
    year: 2026,
    month: 9,
    startDate: '2026-09-25',
    endDate: '2026-09-27',
    adjustedWorkDates: [],
    productivity: 0.9,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm',
    calendarKind: 'statutory_holiday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 Mid-Autumn Festival: Sep 25 to Sep 27 holiday',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'national_day_2026',
    holidayName: '2026 National Day construction window',
    year: 2026,
    month: 10,
    startDate: '2026-10-01',
    endDate: '2026-10-07',
    adjustedWorkDates: ['2026-09-20', '2026-10-10'],
    productivity: 0.77,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm',
    calendarKind: 'statutory_holiday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 National Day: Oct 1 to Oct 7 holiday; Sep 20 and Oct 10 adjusted workdays',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'new_year_day_2026_adjusted_workday_2026_01_04',
    holidayName: '2026 New Year adjusted workday',
    year: 2026,
    month: 1,
    startDate: '2026-01-04',
    endDate: '2026-01-04',
    adjustedWorkDates: [],
    productivity: 1,
    isCompensatoryWorkday: true,
    adjustmentOrigin: 'new_year_day_2026',
    calendarKind: 'compensatory_workday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 New Year adjusted workday: Jan 4',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'spring_festival_2026_adjusted_workday_2026_02_14',
    holidayName: '2026 Spring Festival adjusted workday',
    year: 2026,
    month: 2,
    startDate: '2026-02-14',
    endDate: '2026-02-14',
    adjustedWorkDates: [],
    productivity: 1,
    isCompensatoryWorkday: true,
    adjustmentOrigin: 'spring_festival_2026',
    calendarKind: 'compensatory_workday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 Spring Festival adjusted workday: Feb 14',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'spring_festival_2026_adjusted_workday_2026_02_28',
    holidayName: '2026 Spring Festival adjusted workday',
    year: 2026,
    month: 2,
    startDate: '2026-02-28',
    endDate: '2026-02-28',
    adjustedWorkDates: [],
    productivity: 1,
    isCompensatoryWorkday: true,
    adjustmentOrigin: 'spring_festival_2026',
    calendarKind: 'compensatory_workday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 Spring Festival adjusted workday: Feb 28',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'labor_day_2026_adjusted_workday_2026_05_09',
    holidayName: '2026 Labor Day adjusted workday',
    year: 2026,
    month: 5,
    startDate: '2026-05-09',
    endDate: '2026-05-09',
    adjustedWorkDates: [],
    productivity: 1,
    isCompensatoryWorkday: true,
    adjustmentOrigin: 'labor_day_2026',
    calendarKind: 'compensatory_workday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 Labor Day adjusted workday: May 9',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'national_day_2026_adjusted_workday_2026_09_20',
    holidayName: '2026 National Day adjusted workday',
    year: 2026,
    month: 9,
    startDate: '2026-09-20',
    endDate: '2026-09-20',
    adjustedWorkDates: [],
    productivity: 1,
    isCompensatoryWorkday: true,
    adjustmentOrigin: 'national_day_2026',
    calendarKind: 'compensatory_workday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 National Day adjusted workday: Sep 20',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'national_day_2026_adjusted_workday_2026_10_10',
    holidayName: '2026 National Day adjusted workday',
    year: 2026,
    month: 10,
    startDate: '2026-10-10',
    endDate: '2026-10-10',
    adjustedWorkDates: [],
    productivity: 1,
    isCompensatoryWorkday: true,
    adjustmentOrigin: 'national_day_2026',
    calendarKind: 'compensatory_workday',
    sourceStandard: 'national_calendar',
    sourceVersion: 'State Council 2026 holiday notice',
    sourceClauseRef: '2026 National Day adjusted workday: Oct 10',
    evidenceSourceKeys: ['STATE_COUNCIL_HOLIDAY_2026'],
    webVerified: true,
    reviewNeeded: false,
    confidence: 'high',
  },
  {
    holidayCode: 'new_year_day_2027_forecast',
    holidayName: '2027 New Year forecast holiday',
    year: 2027,
    month: 1,
    startDate: '2027-01-01',
    endDate: '2027-01-03',
    adjustedWorkDates: [],
    productivity: 0.9,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'forecast_pending_state_council_notice',
    calendarKind: 'forecast_calendar_window',
    sourceStandard: 'system_default',
    sourceVersion: 'forecast pending State Council 2027 holiday notice',
    sourceClauseRef: 'Forecast New Year construction window; replace after State Council publishes 2027 holiday notice.',
    evidenceSourceKeys: ['FORECAST_HOLIDAY_2027'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'low',
  },
  {
    holidayCode: 'spring_festival_2027_forecast',
    holidayName: '2027 Spring Festival construction forecast window',
    year: 2027,
    month: 2,
    startDate: '2027-02-04',
    endDate: '2027-02-12',
    adjustedWorkDates: [],
    productivity: 0.35,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'forecast_pending_state_council_notice',
    calendarKind: 'forecast_calendar_window',
    sourceStandard: 'system_default',
    sourceVersion: 'forecast pending State Council 2027 holiday notice',
    sourceClauseRef: 'Forecast Spring Festival construction low-productivity shutdown window around Lunar New Year 2027-01-01; replace after State Council notice.',
    evidenceSourceKeys: ['FORECAST_HOLIDAY_2027'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'low',
  },
  {
    holidayCode: 'qingming_2027_forecast',
    holidayName: '2027 Qingming forecast holiday',
    year: 2027,
    month: 4,
    startDate: '2027-04-03',
    endDate: '2027-04-05',
    adjustedWorkDates: [],
    productivity: 0.9,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'forecast_pending_state_council_notice',
    calendarKind: 'forecast_calendar_window',
    sourceStandard: 'system_default',
    sourceVersion: 'forecast pending State Council 2027 holiday notice',
    sourceClauseRef: 'Forecast Qingming construction window; replace after State Council publishes 2027 holiday notice.',
    evidenceSourceKeys: ['FORECAST_HOLIDAY_2027'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'low',
  },
  {
    holidayCode: 'labor_day_2027_forecast',
    holidayName: '2027 Labor Day forecast holiday',
    year: 2027,
    month: 5,
    startDate: '2027-05-01',
    endDate: '2027-05-05',
    adjustedWorkDates: [],
    productivity: 0.84,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'forecast_pending_state_council_notice',
    calendarKind: 'forecast_calendar_window',
    sourceStandard: 'system_default',
    sourceVersion: 'forecast pending State Council 2027 holiday notice',
    sourceClauseRef: 'Forecast Labor Day construction window; replace after State Council publishes 2027 holiday notice.',
    evidenceSourceKeys: ['FORECAST_HOLIDAY_2027'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'low',
  },
  {
    holidayCode: 'dragon_boat_2027_forecast',
    holidayName: '2027 Dragon Boat Festival forecast holiday',
    year: 2027,
    month: 6,
    startDate: '2027-06-07',
    endDate: '2027-06-09',
    adjustedWorkDates: [],
    productivity: 0.9,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'forecast_pending_state_council_notice',
    calendarKind: 'forecast_calendar_window',
    sourceStandard: 'system_default',
    sourceVersion: 'forecast pending State Council 2027 holiday notice',
    sourceClauseRef: 'Forecast Dragon Boat construction window; replace after State Council publishes 2027 holiday notice.',
    evidenceSourceKeys: ['FORECAST_HOLIDAY_2027'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'low',
  },
  {
    holidayCode: 'mid_autumn_national_day_2027_forecast',
    holidayName: '2027 Mid-Autumn and National Day construction forecast window',
    year: 2027,
    month: 10,
    startDate: '2027-10-01',
    endDate: '2027-10-08',
    adjustedWorkDates: [],
    productivity: 0.74,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'forecast_pending_state_council_notice',
    calendarKind: 'forecast_calendar_window',
    sourceStandard: 'system_default',
    sourceVersion: 'forecast pending State Council 2027 holiday notice',
    sourceClauseRef: 'Forecast combined Mid-Autumn/National Day construction window; replace after State Council publishes 2027 holiday notice.',
    evidenceSourceKeys: ['FORECAST_HOLIDAY_2027'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'low',
  },
  {
    holidayCode: 'plum_rain_2026_forecast',
    holidayName: '2026 Yangtze Delta plum-rain construction calendar window',
    year: 2026,
    month: 6,
    startDate: '2026-06-01',
    endDate: '2026-07-15',
    adjustedWorkDates: [],
    productivity: 0.97,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'construction_climate_calendar_window',
    calendarKind: 'plum_rain_window',
    sourceStandard: 'system_default',
    sourceVersion: 'construction climate calendar window 2026',
    sourceClauseRef: 'Explicit work-calendar climate window for plum-rain planning; process/weather facts own stronger task-level impacts.',
    evidenceSourceKeys: ['CONSTRUCTION_CLIMATE_CALENDAR_WINDOWS_2026'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'medium',
  },
  {
    holidayCode: 'hot_summer_2026_forecast',
    holidayName: '2026 hot-summer construction calendar window',
    year: 2026,
    month: 7,
    startDate: '2026-07-15',
    endDate: '2026-08-31',
    adjustedWorkDates: [],
    productivity: 0.97,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'construction_climate_calendar_window',
    calendarKind: 'hot_summer_window',
    sourceStandard: 'system_default',
    sourceVersion: 'construction climate calendar window 2026',
    sourceClauseRef: 'Explicit work-calendar climate window for hot-summer work-hour rhythm; weather facts own strong heat events.',
    evidenceSourceKeys: ['CONSTRUCTION_CLIMATE_CALENDAR_WINDOWS_2026'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'medium',
  },
  {
    holidayCode: 'dust_storm_2026_forecast',
    holidayName: '2026 northwest dust-storm construction calendar window',
    year: 2026,
    month: 4,
    startDate: '2026-03-15',
    endDate: '2026-05-15',
    adjustedWorkDates: [],
    productivity: 0.97,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'construction_climate_calendar_window',
    calendarKind: 'dust_storm_window',
    sourceStandard: 'system_default',
    sourceVersion: 'construction climate calendar window 2026',
    sourceClauseRef: 'Explicit work-calendar climate window for northwest dust and wind-sand planning; weather facts own actual event severity.',
    evidenceSourceKeys: ['CONSTRUCTION_CLIMATE_CALENDAR_WINDOWS_2026'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'medium',
  },
  {
    holidayCode: 'plum_rain_2027_forecast',
    holidayName: '2027 Yangtze Delta plum-rain construction calendar window',
    year: 2027,
    month: 6,
    startDate: '2027-06-01',
    endDate: '2027-07-15',
    adjustedWorkDates: [],
    productivity: 0.97,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'construction_climate_calendar_window',
    calendarKind: 'plum_rain_window',
    sourceStandard: 'system_default',
    sourceVersion: 'construction climate calendar window 2027',
    sourceClauseRef: 'Explicit work-calendar climate window for plum-rain planning; process/weather facts own stronger task-level impacts.',
    evidenceSourceKeys: ['FORECAST_HOLIDAY_2027'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'low',
  },
  {
    holidayCode: 'hot_summer_2027_forecast',
    holidayName: '2027 hot-summer construction calendar window',
    year: 2027,
    month: 7,
    startDate: '2027-07-15',
    endDate: '2027-08-31',
    adjustedWorkDates: [],
    productivity: 0.97,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'construction_climate_calendar_window',
    calendarKind: 'hot_summer_window',
    sourceStandard: 'system_default',
    sourceVersion: 'construction climate calendar window 2027',
    sourceClauseRef: 'Explicit work-calendar climate window for hot-summer work-hour rhythm; weather facts own strong heat events.',
    evidenceSourceKeys: ['FORECAST_HOLIDAY_2027'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'low',
  },
  {
    holidayCode: 'dust_storm_2027_forecast',
    holidayName: '2027 northwest dust-storm construction calendar window',
    year: 2027,
    month: 4,
    startDate: '2027-03-15',
    endDate: '2027-05-15',
    adjustedWorkDates: [],
    productivity: 0.97,
    isCompensatoryWorkday: false,
    adjustmentOrigin: 'construction_climate_calendar_window',
    calendarKind: 'dust_storm_window',
    sourceStandard: 'system_default',
    sourceVersion: 'construction climate calendar window 2027',
    sourceClauseRef: 'Explicit work-calendar climate window for northwest dust and wind-sand planning; weather facts own actual event severity.',
    evidenceSourceKeys: ['FORECAST_HOLIDAY_2027'],
    webVerified: true,
    reviewNeeded: true,
    confidence: 'low',
  },
]

export function getV1474HolidayWindow(month: number) {
  return V1474_WORK_CALENDAR_SEED.find((item) => item.month === month) ?? null
}

export const V1474_WORK_CALENDAR_SEED_META = {
  seedVersion: V1474_WORK_CALENDAR_SEED_VERSION,
  seedScope: 'algorithm_auxiliary',
  sourceStandards: ['State Council 2026 holiday notice', 'construction climate calendar windows'],
  expectedCounts: {
    records: V1474_WORK_CALENDAR_SEED.length,
  },
  evidenceSources: V1474_WORK_CALENDAR_EVIDENCE_SOURCES,
  generationPolicy: 'source_backed_no_generic_generation; statutory holiday windows and explicit construction climate windows are seeded here; labor demobilization or remobilization buffers must come from project history or company overrides',
  usagePolicy: 'construction_productivity_calendar; weekends are production days by default; adjusted workdays are retained as source metadata only; Spring Festival windows are treated as construction shutdown windows; plum-rain/hot-summer/dust-storm windows are low-strength calendarKind context while weather/process facts own stronger impacts',
  webVerified: true,
  reviewNeeded: false,
} as const
