import type { V1474RegionCode } from './v1474SeasonalProductivitySeed.js'

export type V1474ClimateRiskLevel = 'none' | 'low' | 'medium' | 'high'

export type V1474RegionalClimateRule = {
  province: string
  city?: string | null
  adminCode?: string | null
  aliases: string[]
  climateRegion: V1474RegionCode
  thermalZone: 'severe_cold' | 'cold' | 'hot_summer_cold_winter' | 'hot_summer_warm_winter' | 'mild' | 'plateau' | 'desert'
  rainySeasonMonths: number[]
  highTempMonths: number[]
  coldWeatherMonths: number[]
  typhoonRiskLevel: V1474ClimateRiskLevel
  floodSeasonMonths: number[]
  winterShutdownRiskLevel: V1474ClimateRiskLevel
  climateTags: string[]
  /** v1.4.22.1: 软土地基等级 0=无/1=轻度/2=中度/3=重度。作为区域地理环境事实值，不新增平行算法入口。 */
  softSoilLevel: 0 | 1 | 2 | 3
  /** v1.4.22.1: 山区地形标识。 */
  mountainTerrain: boolean
  /** v1.4.22.1: 地形难度等级 0=平原/1=丘陵/2=低山/3=高山。 */
  terrainDifficultyLevel: 0 | 1 | 2 | 3
  /** v1.4.22.1: 抗震设防烈度 null=未设定/6/7/8/9。 */
  seismicIntensity: null | 6 | 7 | 8 | 9
  sourceStandard: string
  sourceVersion: string
  sourceClauseRef: string
  evidenceSourceKeys: string[]
  confidence: 'high' | 'medium' | 'low'
}

export const V1474_REGIONAL_CLIMATE_RULE_EVIDENCE_SOURCES = [
  {
    sourceKey: 'GB50176_2016',
    title: 'GB 50176-2016 Design code for thermal engineering of civil building',
    url: 'https://www.ndls.org.cn/standard/detail/601ac0207027631848eab55107c0ea03',
    accessedAt: '2026-05-16',
  },
  {
    sourceKey: 'CMA_PUBLIC_WEATHER_SERVICE',
    title: 'China Meteorological Administration public weather service',
    url: 'https://www.cma.gov.cn/',
    accessedAt: '2026-05-16',
  },
]

const SOURCE = {
  sourceStandard: 'GB 50176-2016 + CMA public climate service',
  sourceVersion: 'v1.4.7.5 mainland China province-level cold-start + priority city climate seed',
  sourceClauseRef: 'Mainland China housing-construction climate tags derived from building thermal climate zoning and public meteorological service categories; province rules are cold-start fallback and priority city rules are the commercial main path starter set.',
  evidenceSourceKeys: ['GB50176_2016', 'CMA_PUBLIC_WEATHER_SERVICE'],
  confidence: 'medium' as const,
}

type RuleInput = Omit<V1474RegionalClimateRule, keyof typeof SOURCE | 'softSoilLevel' | 'mountainTerrain' | 'terrainDifficultyLevel' | 'seismicIntensity'> & {
  softSoilLevel?: 0 | 1 | 2 | 3
  mountainTerrain?: boolean
  terrainDifficultyLevel?: 0 | 1 | 2 | 3
  seismicIntensity?: null | 6 | 7 | 8 | 9
}

function rule(input: RuleInput) {
  return {
    softSoilLevel: 0 as const,
    mountainTerrain: false,
    terrainDifficultyLevel: 0 as const,
    seismicIntensity: null,
    ...input,
    ...SOURCE,
  }
}

const V1474_PROVINCE_CLIMATE_RULE_SEED: V1474RegionalClimateRule[] = [
  rule({
    province: 'beijing',
    aliases: ['beijing', '\u5317\u4eac'],
    climateRegion: 'north',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [6, 7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'medium',
    climateTags: ['cold_winter', 'summer_rain'],
    seismicIntensity: 8,
  }),
  rule({
    province: 'tianjin',
    aliases: ['tianjin', '\u5929\u6d25'],
    climateRegion: 'north',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [6, 7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'low',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'medium',
    climateTags: ['cold_winter', 'summer_rain', 'coastal_wind'],
  }),
  rule({
    province: 'hebei',
    aliases: ['hebei', '\u6cb3\u5317', '\u77f3\u5bb6\u5e84'],
    climateRegion: 'north',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [6, 7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'medium',
    climateTags: ['cold_winter', 'summer_rain'],
  }),
  rule({
    province: 'shanxi',
    aliases: ['shanxi', '\u5c71\u897f', '\u592a\u539f'],
    climateRegion: 'north',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [6, 7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'medium',
    climateTags: ['cold_winter', 'inland_dry'],
  }),
  rule({
    province: 'inner_mongolia',
    aliases: ['inner mongolia', 'inner_mongolia', '\u5185\u8499\u53e4', '\u547c\u548c\u6d69\u7279'],
    climateRegion: 'north',
    thermalZone: 'severe_cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [7, 8],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['severe_cold', 'wind_sand', 'short_construction_season'],
  }),
  rule({
    province: 'liaoning',
    aliases: ['liaoning', '\u8fbd\u5b81', '\u6c88\u9633', '\u5927\u8fde'],
    climateRegion: 'north',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [7, 8],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'low',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['cold_winter', 'coastal_wind'],
  }),
  rule({
    province: 'jilin',
    aliases: ['jilin', '\u5409\u6797', '\u957f\u6625'],
    climateRegion: 'north',
    thermalZone: 'severe_cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [7, 8],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['severe_cold', 'freeze_thaw'],
  }),
  rule({
    province: 'heilongjiang',
    aliases: ['heilongjiang', '\u9ed1\u9f99\u6c5f', '\u54c8\u5c14\u6ee8'],
    climateRegion: 'north',
    thermalZone: 'severe_cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [7, 8],
    coldWeatherMonths: [10, 11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['severe_cold', 'long_winter_shutdown_risk'],
  }),
  rule({
    province: 'shanghai',
    aliases: ['shanghai', '\u4e0a\u6d77'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [6, 7],
    highTempMonths: [7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'medium',
    floodSeasonMonths: [6, 7, 8, 9],
    winterShutdownRiskLevel: 'low',
    climateTags: ['plum_rain', 'hot_humid_summer', 'coastal_typhoon'],
    softSoilLevel: 2,
    seismicIntensity: 7,
  }),
  rule({
    province: 'jiangsu',
    aliases: ['jiangsu', '\u6c5f\u82cf', '\u5357\u4eac', '\u82cf\u5dde', '\u65e0\u9521'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [6, 7],
    highTempMonths: [7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'medium',
    floodSeasonMonths: [6, 7, 8],
    winterShutdownRiskLevel: 'low',
    climateTags: ['plum_rain', 'hot_humid_summer'],
  }),
  rule({
    province: 'zhejiang',
    aliases: ['zhejiang', '\u6d59\u6c5f', '\u676d\u5dde', '\u5b81\u6ce2', '\u6e29\u5dde'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [5, 6, 7, 8, 9],
    highTempMonths: [7, 8],
    coldWeatherMonths: [11, 12, 1, 2],
    typhoonRiskLevel: 'high',
    floodSeasonMonths: [6, 7, 8, 9],
    winterShutdownRiskLevel: 'low',
    climateTags: ['plum_rain', 'typhoon', 'hot_humid_summer'],
  }),
  rule({
    province: 'anhui',
    aliases: ['anhui', '\u5b89\u5fbd', '\u5408\u80a5'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [6, 7],
    highTempMonths: [7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'low',
    floodSeasonMonths: [6, 7, 8],
    winterShutdownRiskLevel: 'low',
    climateTags: ['plum_rain', 'hot_summer'],
  }),
  rule({
    province: 'fujian',
    aliases: ['fujian', '\u798f\u5efa', '\u798f\u5dde', '\u53a6\u95e8', '\u6cc9\u5dde'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_warm_winter',
    rainySeasonMonths: [5, 6, 7],
    highTempMonths: [6, 7, 8, 9],
    coldWeatherMonths: [1],
    typhoonRiskLevel: 'high',
    floodSeasonMonths: [5, 6, 7, 8, 9],
    winterShutdownRiskLevel: 'none',
    climateTags: ['typhoon', 'hot_humid_summer', 'coastal_rain'],
  }),
  rule({
    province: 'jiangxi',
    aliases: ['jiangxi', '\u6c5f\u897f', '\u5357\u660c'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [4, 5, 6],
    highTempMonths: [7, 8, 9],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'low',
    floodSeasonMonths: [4, 5, 6, 7],
    winterShutdownRiskLevel: 'low',
    climateTags: ['early_flood_season', 'hot_summer'],
  }),
  rule({
    province: 'shandong',
    aliases: ['shandong', '\u5c71\u4e1c', '\u6d4e\u5357', '\u9752\u5c9b'],
    climateRegion: 'east',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [6, 7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'low',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'medium',
    climateTags: ['cold_winter', 'summer_rain', 'coastal_wind'],
  }),
  rule({
    province: 'henan',
    aliases: ['henan', '\u6cb3\u5357', '\u90d1\u5dde'],
    climateRegion: 'east',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [6, 7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'medium',
    climateTags: ['hot_summer', 'summer_rain'],
  }),
  rule({
    province: 'hubei',
    aliases: ['hubei', '\u6e56\u5317', '\u6b66\u6c49'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [6, 7],
    highTempMonths: [7, 8, 9],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [6, 7, 8],
    winterShutdownRiskLevel: 'low',
    climateTags: ['hot_summer', 'plum_rain'],
  }),
  rule({
    province: 'hunan',
    aliases: ['hunan', '\u6e56\u5357', '\u957f\u6c99'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [5, 6, 7],
    highTempMonths: [7, 8, 9],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'low',
    floodSeasonMonths: [5, 6, 7, 8],
    winterShutdownRiskLevel: 'low',
    climateTags: ['hot_summer', 'rainy_season'],
  }),
  rule({
    province: 'guangdong',
    aliases: ['guangdong', '\u5e7f\u4e1c', '\u5e7f\u5dde', '\u6df1\u5733', '\u73e0\u6d77'],
    climateRegion: 'south',
    thermalZone: 'hot_summer_warm_winter',
    rainySeasonMonths: [4, 5, 6, 7, 8, 9],
    highTempMonths: [5, 6, 7, 8, 9],
    coldWeatherMonths: [],
    typhoonRiskLevel: 'high',
    floodSeasonMonths: [4, 5, 6, 7, 8, 9],
    winterShutdownRiskLevel: 'none',
    climateTags: ['typhoon', 'long_rainy_season', 'hot_humid_summer'],
  }),
  rule({
    province: 'guangxi',
    aliases: ['guangxi', '\u5e7f\u897f', '\u5357\u5b81', '\u6842\u6797'],
    climateRegion: 'south',
    thermalZone: 'hot_summer_warm_winter',
    rainySeasonMonths: [4, 5, 6, 7, 8],
    highTempMonths: [6, 7, 8, 9],
    coldWeatherMonths: [],
    typhoonRiskLevel: 'medium',
    floodSeasonMonths: [4, 5, 6, 7, 8],
    winterShutdownRiskLevel: 'none',
    climateTags: ['long_rainy_season', 'hot_humid_summer'],
  }),
  rule({
    province: 'hainan',
    aliases: ['hainan', '\u6d77\u5357', '\u6d77\u53e3', '\u4e09\u4e9a'],
    climateRegion: 'south',
    thermalZone: 'hot_summer_warm_winter',
    rainySeasonMonths: [5, 6, 7, 8, 9, 10],
    highTempMonths: [4, 5, 6, 7, 8, 9],
    coldWeatherMonths: [],
    typhoonRiskLevel: 'high',
    floodSeasonMonths: [5, 6, 7, 8, 9, 10],
    winterShutdownRiskLevel: 'none',
    climateTags: ['typhoon', 'tropical_rain', 'hot_humid_summer'],
  }),
  rule({
    province: 'chongqing',
    aliases: ['chongqing', '\u91cd\u5e86'],
    climateRegion: 'west',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [5, 6, 7, 8, 9],
    highTempMonths: [7, 8, 9],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [6, 7, 8, 9],
    winterShutdownRiskLevel: 'low',
    climateTags: ['hot_summer', 'mountain_rain'],
  }),
  rule({
    province: 'sichuan',
    aliases: ['sichuan', '\u56db\u5ddd', '\u6210\u90fd'],
    climateRegion: 'west',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [6, 7, 8, 9],
    highTempMonths: [7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [6, 7, 8, 9],
    winterShutdownRiskLevel: 'low',
    climateTags: ['basin_humidity', 'mountain_rain'],
    mountainTerrain: true,
    terrainDifficultyLevel: 2,
    seismicIntensity: 7,
  }),
  rule({
    province: 'guizhou',
    aliases: ['guizhou', '\u8d35\u5dde', '\u8d35\u9633'],
    climateRegion: 'west',
    thermalZone: 'mild',
    rainySeasonMonths: [5, 6, 7, 8],
    highTempMonths: [7, 8],
    coldWeatherMonths: [1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [5, 6, 7, 8],
    winterShutdownRiskLevel: 'low',
    climateTags: ['mountain_rain', 'mild_climate'],
  }),
  rule({
    province: 'yunnan',
    aliases: ['yunnan', '\u4e91\u5357', '\u6606\u660e'],
    climateRegion: 'west',
    thermalZone: 'mild',
    rainySeasonMonths: [5, 6, 7, 8, 9, 10],
    highTempMonths: [5, 6, 7],
    coldWeatherMonths: [],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [6, 7, 8, 9],
    winterShutdownRiskLevel: 'none',
    climateTags: ['plateau_monsoon', 'long_rainy_season'],
  }),
  rule({
    province: 'tibet',
    aliases: ['tibet', '\u897f\u85cf', '\u62c9\u8428'],
    climateRegion: 'west',
    thermalZone: 'plateau',
    rainySeasonMonths: [6, 7, 8, 9],
    highTempMonths: [],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['plateau', 'large_diurnal_range', 'cold_winter'],
  }),
  rule({
    province: 'shaanxi',
    aliases: ['shaanxi', '\u9655\u897f', '\u897f\u5b89'],
    climateRegion: 'west',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8, 9],
    highTempMonths: [6, 7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8, 9],
    winterShutdownRiskLevel: 'medium',
    climateTags: ['cold_winter', 'summer_rain'],
  }),
  rule({
    province: 'gansu',
    aliases: ['gansu', '\u7518\u8083', '\u5170\u5dde'],
    climateRegion: 'west',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8, 9],
    highTempMonths: [7, 8],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['cold_winter', 'inland_dry', 'wind_sand'],
  }),
  rule({
    province: 'qinghai',
    aliases: ['qinghai', '\u9752\u6d77', '\u897f\u5b81'],
    climateRegion: 'west',
    thermalZone: 'plateau',
    rainySeasonMonths: [6, 7, 8],
    highTempMonths: [],
    coldWeatherMonths: [10, 11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['plateau', 'cold_winter', 'short_construction_season'],
  }),
  rule({
    province: 'ningxia',
    aliases: ['ningxia', '\u5b81\u590f', '\u94f6\u5ddd'],
    climateRegion: 'west',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [7, 8],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['cold_winter', 'inland_dry'],
  }),
  rule({
    province: 'xinjiang',
    aliases: ['xinjiang', '\u65b0\u7586', '\u4e4c\u9c81\u6728\u9f50'],
    climateRegion: 'west',
    thermalZone: 'desert',
    rainySeasonMonths: [],
    highTempMonths: [6, 7, 8],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [],
    winterShutdownRiskLevel: 'high',
    climateTags: ['desert_dry', 'large_diurnal_range', 'cold_winter'],
  }),
]

type CityClimateOverride = Partial<Pick<
  V1474RegionalClimateRule,
  | 'adminCode'
  | 'climateRegion'
  | 'thermalZone'
  | 'rainySeasonMonths'
  | 'highTempMonths'
  | 'coldWeatherMonths'
  | 'typhoonRiskLevel'
  | 'floodSeasonMonths'
  | 'winterShutdownRiskLevel'
  | 'climateTags'
  | 'softSoilLevel'
  | 'mountainTerrain'
  | 'terrainDifficultyLevel'
  | 'seismicIntensity'
>>

function cityFromProvince(input: {
  province: string
  city: string
  aliases: string[]
} & CityClimateOverride): V1474RegionalClimateRule {
  const base = V1474_PROVINCE_CLIMATE_RULE_SEED.find((item) => item.province === input.province)
  if (!base) throw new Error(`Missing province climate rule for ${input.province}`)
  return rule({
    province: base.province,
    city: input.city,
    adminCode: input.adminCode ?? null,
    aliases: input.aliases,
    climateRegion: input.climateRegion ?? base.climateRegion,
    thermalZone: input.thermalZone ?? base.thermalZone,
    rainySeasonMonths: input.rainySeasonMonths ?? base.rainySeasonMonths,
    highTempMonths: input.highTempMonths ?? base.highTempMonths,
    coldWeatherMonths: input.coldWeatherMonths ?? base.coldWeatherMonths,
    typhoonRiskLevel: input.typhoonRiskLevel ?? base.typhoonRiskLevel,
    floodSeasonMonths: input.floodSeasonMonths ?? base.floodSeasonMonths,
    winterShutdownRiskLevel: input.winterShutdownRiskLevel ?? base.winterShutdownRiskLevel,
    climateTags: input.climateTags ?? base.climateTags,
    softSoilLevel: input.softSoilLevel ?? base.softSoilLevel,
    mountainTerrain: input.mountainTerrain ?? base.mountainTerrain,
    terrainDifficultyLevel: input.terrainDifficultyLevel ?? base.terrainDifficultyLevel,
    seismicIntensity: input.seismicIntensity ?? base.seismicIntensity,
  })
}

export const V1474_MAINLAND_CORE_CITY_CLIMATE_RULE_SEED: V1474RegionalClimateRule[] = [
  cityFromProvince({ province: 'beijing', city: 'beijing', aliases: ['beijing', '\u5317\u4eac'] }),
  cityFromProvince({ province: 'tianjin', city: 'tianjin', aliases: ['tianjin', '\u5929\u6d25'] }),
  cityFromProvince({ province: 'shanghai', city: 'shanghai', aliases: ['shanghai', '\u4e0a\u6d77'] }),
  cityFromProvince({ province: 'chongqing', city: 'chongqing', aliases: ['chongqing', '\u91cd\u5e86'], climateTags: ['mountain_city', 'hot_humid_summer', 'basin_humidity'] }),
  cityFromProvince({ province: 'hebei', city: 'shijiazhuang', aliases: ['shijiazhuang', '\u77f3\u5bb6\u5e84'] }),
  cityFromProvince({ province: 'shanxi', city: 'taiyuan', aliases: ['taiyuan', '\u592a\u539f'] }),
  cityFromProvince({ province: 'inner_mongolia', city: 'hohhot', aliases: ['hohhot', 'huhehaote', '\u547c\u548c\u6d69\u7279'] }),
  cityFromProvince({ province: 'liaoning', city: 'shenyang', aliases: ['shenyang', '\u6c88\u9633'] }),
  cityFromProvince({ province: 'jilin', city: 'changchun', aliases: ['changchun', '\u957f\u6625'] }),
  cityFromProvince({ province: 'heilongjiang', city: 'harbin', aliases: ['harbin', '\u54c8\u5c14\u6ee8'] }),
  cityFromProvince({ province: 'jiangsu', city: 'nanjing', aliases: ['nanjing', '\u5357\u4eac'] }),
  cityFromProvince({ province: 'jiangsu', city: 'suzhou', aliases: ['suzhou', '\u82cf\u5dde'] }),
  cityFromProvince({ province: 'jiangsu', city: 'wuxi', aliases: ['wuxi', '\u65e0\u9521'] }),
  cityFromProvince({ province: 'jiangsu', city: 'xuzhou', aliases: ['xuzhou', '\u5f90\u5dde'], thermalZone: 'cold', winterShutdownRiskLevel: 'medium', climateTags: ['cold_winter', 'summer_rain'] }),
  cityFromProvince({
    province: 'zhejiang',
    city: 'hangzhou',
    aliases: ['hangzhou', '\u676d\u5dde'],
    typhoonRiskLevel: 'medium',
    rainySeasonMonths: [5, 6, 7, 8, 9],
    coldWeatherMonths: [11, 12, 1, 2],
    climateTags: ['plum_rain', 'typhoon_outer_band', 'hot_humid_summer'],
  }),
  cityFromProvince({ province: 'zhejiang', city: 'ningbo', aliases: ['ningbo', '\u5b81\u6ce2'], typhoonRiskLevel: 'high', climateTags: ['coastal_typhoon', 'plum_rain', 'hot_humid_summer'] }),
  cityFromProvince({ province: 'zhejiang', city: 'wenzhou', aliases: ['wenzhou', '\u6e29\u5dde'], typhoonRiskLevel: 'high', climateTags: ['coastal_typhoon', 'plum_rain', 'hot_humid_summer'] }),
  cityFromProvince({ province: 'anhui', city: 'hefei', aliases: ['hefei', '\u5408\u80a5'] }),
  cityFromProvince({ province: 'fujian', city: 'fuzhou', aliases: ['fuzhou', '\u798f\u5dde'], typhoonRiskLevel: 'high' }),
  cityFromProvince({ province: 'jiangxi', city: 'nanchang', aliases: ['nanchang', '\u5357\u660c'] }),
  cityFromProvince({ province: 'shandong', city: 'jinan', aliases: ['jinan', '\u6d4e\u5357'] }),
  cityFromProvince({ province: 'shandong', city: 'yantai', aliases: ['yantai', '\u70df\u53f0'], climateTags: ['coastal_wind', 'cold_winter', 'summer_rain'] }),
  cityFromProvince({ province: 'henan', city: 'zhengzhou', aliases: ['zhengzhou', '\u90d1\u5dde'] }),
  cityFromProvince({ province: 'henan', city: 'luoyang', aliases: ['luoyang', '\u6d1b\u9633'] }),
  cityFromProvince({ province: 'hubei', city: 'wuhan', aliases: ['wuhan', '\u6b66\u6c49'] }),
  cityFromProvince({ province: 'hubei', city: 'yichang', aliases: ['yichang', '\u5b9c\u660c'] }),
  cityFromProvince({ province: 'hunan', city: 'changsha', aliases: ['changsha', '\u957f\u6c99'] }),
  cityFromProvince({ province: 'guangdong', city: 'guangzhou', aliases: ['guangzhou', '\u5e7f\u5dde', '\u73e0\u4e09\u89d2'] }),
  cityFromProvince({ province: 'guangdong', city: 'zhuhai', aliases: ['zhuhai', '\u73e0\u6d77'], typhoonRiskLevel: 'high', climateTags: ['typhoon', 'long_rainy_season', 'hot_humid_summer', 'coastal_rain'] }),
  cityFromProvince({ province: 'guangdong', city: 'shantou', aliases: ['shantou', '\u6c55\u5934'], typhoonRiskLevel: 'high', climateTags: ['typhoon', 'coastal_rain', 'hot_humid_summer'] }),
  cityFromProvince({ province: 'guangxi', city: 'nanning', aliases: ['nanning', '\u5357\u5b81'] }),
  cityFromProvince({ province: 'guangxi', city: 'guilin', aliases: ['guilin', '\u6842\u6797'], climateTags: ['karst_mountain_rain', 'long_rainy_season', 'hot_humid_summer'] }),
  cityFromProvince({ province: 'hainan', city: 'haikou', aliases: ['haikou', '\u6d77\u53e3'], typhoonRiskLevel: 'high' }),
  cityFromProvince({ province: 'guizhou', city: 'guiyang', aliases: ['guiyang', '\u8d35\u9633'] }),
  cityFromProvince({ province: 'guizhou', city: 'zunyi', aliases: ['zunyi', '\u9075\u4e49'] }),
  cityFromProvince({ province: 'yunnan', city: 'dali', aliases: ['dali', '\u5927\u7406'], thermalZone: 'mild', climateTags: ['mild_climate', 'plateau_monsoon', 'long_rainy_season'] }),
  cityFromProvince({ province: 'yunnan', city: 'lijiang', aliases: ['lijiang', '\u4e3d\u6c5f'], thermalZone: 'plateau', highTempMonths: [], coldWeatherMonths: [11, 12, 1, 2], winterShutdownRiskLevel: 'medium', climateTags: ['plateau', 'mild_climate', 'short_construction_season'] }),
  cityFromProvince({ province: 'tibet', city: 'lhasa', aliases: ['lhasa', '\u62c9\u8428'], thermalZone: 'plateau', highTempMonths: [], coldWeatherMonths: [11, 12, 1, 2, 3], winterShutdownRiskLevel: 'high', climateTags: ['plateau', 'large_diurnal_range', 'short_construction_season'] }),
  cityFromProvince({ province: 'shaanxi', city: 'xian', aliases: ['xian', "xi'an", '\u897f\u5b89'] }),
  cityFromProvince({ province: 'gansu', city: 'lanzhou', aliases: ['lanzhou', '\u5170\u5dde'] }),
  cityFromProvince({ province: 'qinghai', city: 'xining', aliases: ['xining', '\u897f\u5b81'], thermalZone: 'plateau', highTempMonths: [], winterShutdownRiskLevel: 'high', climateTags: ['plateau', 'cold_winter', 'short_construction_season'] }),
  cityFromProvince({ province: 'ningxia', city: 'yinchuan', aliases: ['yinchuan', '\u94f6\u5ddd'] }),
  cityFromProvince({ province: 'xinjiang', city: 'kashgar', aliases: ['kashgar', 'kashi', '\u5580\u4ec0'], thermalZone: 'desert', rainySeasonMonths: [], floodSeasonMonths: [], climateTags: ['desert_dry', 'large_diurnal_range', 'cold_winter'] }),
]

export const V1474_PRIORITY_CITY_CLIMATE_RULE_SEED: V1474RegionalClimateRule[] = [
  rule({
    province: 'sichuan',
    city: 'chengdu',
    aliases: ['chengdu', '\u6210\u90fd', '\u5929\u5e9c\u65b0\u533a'],
    climateRegion: 'west',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [6, 7, 8, 9],
    highTempMonths: [7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [6, 7, 8, 9],
    winterShutdownRiskLevel: 'low',
    climateTags: ['basin_humidity', 'summer_rain', 'hot_humid_summer'],
  }),
  rule({
    province: 'sichuan',
    city: 'ganzi',
    aliases: ['ganzi', 'kangding', '\u7518\u5b5c', '\u5eb7\u5b9a', '\u5ddd\u897f'],
    climateRegion: 'west',
    thermalZone: 'plateau',
    rainySeasonMonths: [6, 7, 8, 9],
    highTempMonths: [],
    coldWeatherMonths: [10, 11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['plateau', 'cold_winter', 'short_construction_season'],
  }),
  rule({
    province: 'yunnan',
    city: 'kunming',
    aliases: ['kunming', '\u6606\u660e'],
    climateRegion: 'west',
    thermalZone: 'mild',
    rainySeasonMonths: [5, 6, 7, 8, 9, 10],
    highTempMonths: [5, 6],
    coldWeatherMonths: [],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [6, 7, 8, 9],
    winterShutdownRiskLevel: 'none',
    climateTags: ['mild_climate', 'plateau_monsoon', 'long_rainy_season'],
  }),
  rule({
    province: 'yunnan',
    city: 'diqing',
    aliases: ['diqing', 'shangri-la', '\u8fea\u5e86', '\u9999\u683c\u91cc\u62c9', '\u6ec7\u897f\u5317'],
    climateRegion: 'west',
    thermalZone: 'plateau',
    rainySeasonMonths: [6, 7, 8, 9],
    highTempMonths: [],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['plateau', 'cold_winter', 'short_construction_season'],
  }),
  rule({
    province: 'xinjiang',
    city: 'urumqi',
    aliases: ['urumqi', '\u4e4c\u9c81\u6728\u9f50'],
    climateRegion: 'west',
    thermalZone: 'desert',
    rainySeasonMonths: [],
    highTempMonths: [6, 7, 8],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [],
    winterShutdownRiskLevel: 'high',
    climateTags: ['desert_dry', 'large_diurnal_range', 'cold_winter'],
  }),
  rule({
    province: 'xinjiang',
    city: 'altay',
    aliases: ['altay', '\u963f\u52d2\u6cf0'],
    climateRegion: 'west',
    thermalZone: 'severe_cold',
    rainySeasonMonths: [6, 7, 8],
    highTempMonths: [7],
    coldWeatherMonths: [10, 11, 12, 1, 2, 3, 4],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [6, 7],
    winterShutdownRiskLevel: 'high',
    climateTags: ['severe_cold', 'short_construction_season', 'freeze_thaw'],
  }),
  rule({
    province: 'inner_mongolia',
    city: 'hulunbuir',
    aliases: ['hulunbuir', '\u547c\u4f26\u8d1d\u5c14'],
    climateRegion: 'north',
    thermalZone: 'severe_cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [7],
    coldWeatherMonths: [10, 11, 12, 1, 2, 3, 4],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'high',
    climateTags: ['severe_cold', 'wind_sand', 'short_construction_season'],
  }),
  rule({
    province: 'guangdong',
    city: 'shenzhen',
    aliases: ['shenzhen', '\u6df1\u5733', '\u73e0\u4e09\u89d2'],
    climateRegion: 'south',
    thermalZone: 'hot_summer_warm_winter',
    rainySeasonMonths: [4, 5, 6, 7, 8, 9],
    highTempMonths: [5, 6, 7, 8, 9],
    coldWeatherMonths: [],
    typhoonRiskLevel: 'high',
    floodSeasonMonths: [4, 5, 6, 7, 8, 9],
    winterShutdownRiskLevel: 'none',
    climateTags: ['typhoon', 'long_rainy_season', 'hot_humid_summer', 'coastal_rain'],
  }),
  rule({
    province: 'guangdong',
    city: 'shaoguan',
    aliases: ['shaoguan', '\u97f6\u5173', '\u7ca4\u5317'],
    climateRegion: 'south',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [4, 5, 6, 7, 8],
    highTempMonths: [6, 7, 8, 9],
    coldWeatherMonths: [1],
    typhoonRiskLevel: 'low',
    floodSeasonMonths: [4, 5, 6, 7, 8],
    winterShutdownRiskLevel: 'low',
    climateTags: ['inland_south', 'long_rainy_season', 'hot_humid_summer'],
  }),
  rule({
    province: 'fujian',
    city: 'xiamen',
    aliases: ['xiamen', '\u53a6\u95e8', '\u95fd\u5357'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_warm_winter',
    rainySeasonMonths: [5, 6, 7],
    highTempMonths: [6, 7, 8, 9],
    coldWeatherMonths: [1],
    typhoonRiskLevel: 'high',
    floodSeasonMonths: [5, 6, 7, 8, 9],
    winterShutdownRiskLevel: 'none',
    climateTags: ['typhoon', 'coastal_rain', 'hot_humid_summer'],
  }),
  rule({
    province: 'zhejiang',
    city: 'zhoushan',
    aliases: ['zhoushan', '\u821f\u5c71', '\u6d59\u6c5f\u6cbf\u6d77'],
    climateRegion: 'east',
    thermalZone: 'hot_summer_cold_winter',
    rainySeasonMonths: [5, 6, 7],
    highTempMonths: [7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'high',
    floodSeasonMonths: [6, 7, 8, 9],
    winterShutdownRiskLevel: 'low',
    climateTags: ['coastal_typhoon', 'plum_rain', 'coastal_wind'],
  }),
  rule({
    province: 'hainan',
    city: 'sanya',
    aliases: ['sanya', '\u4e09\u4e9a'],
    climateRegion: 'south',
    thermalZone: 'hot_summer_warm_winter',
    rainySeasonMonths: [5, 6, 7, 8, 9, 10],
    highTempMonths: [4, 5, 6, 7, 8, 9],
    coldWeatherMonths: [],
    typhoonRiskLevel: 'high',
    floodSeasonMonths: [5, 6, 7, 8, 9, 10],
    winterShutdownRiskLevel: 'none',
    climateTags: ['tropical_rain', 'typhoon', 'hot_humid_summer'],
  }),
  rule({
    province: 'liaoning',
    city: 'dalian',
    aliases: ['dalian', '\u5927\u8fde', '\u8fbd\u5b81\u6cbf\u6d77'],
    climateRegion: 'north',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [7, 8],
    coldWeatherMonths: [11, 12, 1, 2, 3],
    typhoonRiskLevel: 'low',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'medium',
    climateTags: ['coastal_wind', 'cold_winter', 'summer_rain'],
  }),
  rule({
    province: 'shandong',
    city: 'qingdao',
    aliases: ['qingdao', '\u9752\u5c9b', '\u5c71\u4e1c\u6cbf\u6d77'],
    climateRegion: 'east',
    thermalZone: 'cold',
    rainySeasonMonths: [7, 8],
    highTempMonths: [7, 8],
    coldWeatherMonths: [12, 1, 2],
    typhoonRiskLevel: 'low',
    floodSeasonMonths: [7, 8],
    winterShutdownRiskLevel: 'medium',
    climateTags: ['coastal_wind', 'cold_winter', 'summer_rain'],
  }),
  rule({
    province: 'guizhou',
    city: 'bijie',
    aliases: ['bijie', '\u6bd5\u8282', '\u9ed4\u897f\u5317'],
    climateRegion: 'west',
    thermalZone: 'mild',
    rainySeasonMonths: [5, 6, 7, 8],
    highTempMonths: [7, 8],
    coldWeatherMonths: [1, 2],
    typhoonRiskLevel: 'none',
    floodSeasonMonths: [5, 6, 7, 8],
    winterShutdownRiskLevel: 'low',
    climateTags: ['mountain_rain', 'mild_climate', 'fog_humidity'],
  }),
]

export const V1474_EXTENDED_COMMERCIAL_CITY_CLIMATE_RULE_SEED: V1474RegionalClimateRule[] = [
  cityFromProvince({ province: 'hebei', city: 'tangshan', aliases: ['tangshan', '\u5510\u5c71'] }),
  cityFromProvince({ province: 'hebei', city: 'baoding', aliases: ['baoding', '\u4fdd\u5b9a'] }),
  cityFromProvince({ province: 'hebei', city: 'handan', aliases: ['handan', '\u90af\u90f8'] }),
  cityFromProvince({ province: 'hebei', city: 'qinhuangdao', aliases: ['qinhuangdao', '\u79e6\u7687\u5c9b'], typhoonRiskLevel: 'low', climateTags: ['coastal_wind', 'cold_winter', 'summer_rain'] }),
  cityFromProvince({ province: 'shanxi', city: 'datong', aliases: ['datong', '\u5927\u540c'], thermalZone: 'cold', winterShutdownRiskLevel: 'high', climateTags: ['cold_winter', 'inland_dry', 'short_construction_season'] }),
  cityFromProvince({ province: 'shanxi', city: 'yuncheng', aliases: ['yuncheng', '\u8fd0\u57ce'], rainySeasonMonths: [7, 8], highTempMonths: [6, 7, 8], climateTags: ['hot_summer', 'summer_rain', 'inland_dry'] }),
  cityFromProvince({ province: 'inner_mongolia', city: 'baotou', aliases: ['baotou', '\u5305\u5934'], thermalZone: 'severe_cold', climateTags: ['severe_cold', 'wind_sand', 'short_construction_season'] }),
  cityFromProvince({ province: 'inner_mongolia', city: 'ordos', aliases: ['ordos', '\u9102\u5c14\u591a\u65af'], thermalZone: 'severe_cold', rainySeasonMonths: [7, 8], climateTags: ['severe_cold', 'wind_sand', 'inland_dry'] }),
  cityFromProvince({ province: 'inner_mongolia', city: 'chifeng', aliases: ['chifeng', '\u8d64\u5cf0'], thermalZone: 'severe_cold', climateTags: ['severe_cold', 'freeze_thaw', 'short_construction_season'] }),
  cityFromProvince({ province: 'liaoning', city: 'anshan', aliases: ['anshan', '\u978d\u5c71'] }),
  cityFromProvince({ province: 'jilin', city: 'jilin_city', aliases: ['jilin city', 'jilinshi', '\u5409\u6797'] }),
  cityFromProvince({ province: 'heilongjiang', city: 'qiqihar', aliases: ['qiqihar', '\u9f50\u9f50\u54c8\u5c14'] }),
  cityFromProvince({ province: 'heilongjiang', city: 'daqing', aliases: ['daqing', '\u5927\u5e86'] }),
  cityFromProvince({ province: 'jiangsu', city: 'changzhou', aliases: ['changzhou', '\u5e38\u5dde'] }),
  cityFromProvince({ province: 'jiangsu', city: 'nantong', aliases: ['nantong', '\u5357\u901a'], typhoonRiskLevel: 'medium', climateTags: ['plum_rain', 'hot_humid_summer', 'coastal_wind'] }),
  cityFromProvince({ province: 'jiangsu', city: 'yangzhou', aliases: ['yangzhou', '\u626c\u5dde'] }),
  cityFromProvince({ province: 'jiangsu', city: 'taizhou_jiangsu', aliases: ['taizhou jiangsu', '\u6cf0\u5dde'] }),
  cityFromProvince({ province: 'zhejiang', city: 'jiaxing', aliases: ['jiaxing', '\u5609\u5174'] }),
  cityFromProvince({ province: 'zhejiang', city: 'shaoxing', aliases: ['shaoxing', '\u7ecd\u5174'] }),
  cityFromProvince({ province: 'zhejiang', city: 'jinhua', aliases: ['jinhua', '\u91d1\u534e'], typhoonRiskLevel: 'medium' }),
  cityFromProvince({ province: 'zhejiang', city: 'taizhou_zhejiang', aliases: ['taizhou zhejiang', '\u53f0\u5dde'], typhoonRiskLevel: 'high', climateTags: ['coastal_typhoon', 'plum_rain', 'hot_humid_summer'] }),
  cityFromProvince({ province: 'anhui', city: 'wuhu', aliases: ['wuhu', '\u829c\u6e56'] }),
  cityFromProvince({ province: 'anhui', city: 'bengbu', aliases: ['bengbu', '\u868c\u57e0'], thermalZone: 'cold', winterShutdownRiskLevel: 'medium', climateTags: ['cold_winter', 'summer_rain'] }),
  cityFromProvince({ province: 'anhui', city: 'huangshan', aliases: ['huangshan', '\u9ec4\u5c71'], rainySeasonMonths: [5, 6, 7], climateTags: ['mountain_rain', 'plum_rain', 'hot_summer'] }),
  cityFromProvince({ province: 'fujian', city: 'quanzhou', aliases: ['quanzhou', '\u6cc9\u5dde'], typhoonRiskLevel: 'high' }),
  cityFromProvince({ province: 'fujian', city: 'zhangzhou', aliases: ['zhangzhou', '\u6f33\u5dde'], typhoonRiskLevel: 'high' }),
  cityFromProvince({ province: 'jiangxi', city: 'jiujiang', aliases: ['jiujiang', '\u4e5d\u6c5f'], rainySeasonMonths: [5, 6, 7], floodSeasonMonths: [5, 6, 7, 8] }),
  cityFromProvince({ province: 'jiangxi', city: 'ganzhou', aliases: ['ganzhou', '\u8d63\u5dde'], rainySeasonMonths: [4, 5, 6, 7], highTempMonths: [7, 8, 9] }),
  cityFromProvince({ province: 'shandong', city: 'weifang', aliases: ['weifang', '\u6f4d\u574a'] }),
  cityFromProvince({ province: 'shandong', city: 'linyi', aliases: ['linyi', '\u4e34\u6c82'] }),
  cityFromProvince({ province: 'henan', city: 'kaifeng', aliases: ['kaifeng', '\u5f00\u5c01'] }),
  cityFromProvince({ province: 'henan', city: 'nanyang', aliases: ['nanyang', '\u5357\u9633'], thermalZone: 'hot_summer_cold_winter', rainySeasonMonths: [6, 7, 8], highTempMonths: [6, 7, 8] }),
  cityFromProvince({ province: 'hubei', city: 'xiangyang', aliases: ['xiangyang', '\u8944\u9633'] }),
  cityFromProvince({ province: 'hubei', city: 'jingzhou', aliases: ['jingzhou', '\u8346\u5dde'] }),
  cityFromProvince({ province: 'hunan', city: 'zhuzhou', aliases: ['zhuzhou', '\u682a\u6d32'] }),
  cityFromProvince({ province: 'hunan', city: 'yueyang', aliases: ['yueyang', '\u5cb3\u9633'], rainySeasonMonths: [5, 6, 7], floodSeasonMonths: [5, 6, 7, 8] }),
  cityFromProvince({ province: 'guangdong', city: 'dongguan', aliases: ['dongguan', '\u4e1c\u839e', 'pearl river delta'], typhoonRiskLevel: 'high' }),
  cityFromProvince({ province: 'guangdong', city: 'foshan', aliases: ['foshan', '\u4f5b\u5c71', 'pearl river delta'], typhoonRiskLevel: 'medium' }),
  cityFromProvince({ province: 'guangdong', city: 'huizhou', aliases: ['huizhou', '\u60e0\u5dde'], typhoonRiskLevel: 'high', climateTags: ['typhoon', 'long_rainy_season', 'hot_humid_summer', 'coastal_rain'] }),
  cityFromProvince({ province: 'guangdong', city: 'zhongshan', aliases: ['zhongshan', '\u4e2d\u5c71', 'pearl river delta'], typhoonRiskLevel: 'high' }),
  cityFromProvince({ province: 'guangdong', city: 'zhanjiang', aliases: ['zhanjiang', '\u6e5b\u6c5f'], typhoonRiskLevel: 'high', climateTags: ['typhoon', 'long_rainy_season', 'hot_humid_summer', 'coastal_rain'] }),
  cityFromProvince({ province: 'guangxi', city: 'liuzhou', aliases: ['liuzhou', '\u67f3\u5dde'], rainySeasonMonths: [4, 5, 6, 7, 8], highTempMonths: [6, 7, 8, 9] }),
]

export const V1474_REGIONAL_CLIMATE_RULE_SEED: V1474RegionalClimateRule[] = [
  ...V1474_PROVINCE_CLIMATE_RULE_SEED,
  ...V1474_MAINLAND_CORE_CITY_CLIMATE_RULE_SEED,
  ...V1474_PRIORITY_CITY_CLIMATE_RULE_SEED,
  ...V1474_EXTENDED_COMMERCIAL_CITY_CLIMATE_RULE_SEED,
]

export const V1474_REGIONAL_CLIMATE_RULE_SEED_META = {
  seedVersion: 'v1.4.7.5-climate-profile-source-20260518',
  seedScope: 'climate_environment_fact',
  sourceStandards: ['GB50176-2016', 'CMA public climate service'],
  expectedCounts: {
    provinceRecords: V1474_PROVINCE_CLIMATE_RULE_SEED.length,
    mainlandCoreCityRecords: V1474_MAINLAND_CORE_CITY_CLIMATE_RULE_SEED.length,
    priorityCityRecords: V1474_PRIORITY_CITY_CLIMATE_RULE_SEED.length,
    extendedCommercialCityRecords: V1474_EXTENDED_COMMERCIAL_CITY_CLIMATE_RULE_SEED.length,
    cityRecords: V1474_MAINLAND_CORE_CITY_CLIMATE_RULE_SEED.length + V1474_PRIORITY_CITY_CLIMATE_RULE_SEED.length + V1474_EXTENDED_COMMERCIAL_CITY_CLIMATE_RULE_SEED.length,
    records: V1474_REGIONAL_CLIMATE_RULE_SEED.length,
  },
  evidenceSources: V1474_REGIONAL_CLIMATE_RULE_EVIDENCE_SOURCES,
  generationPolicy: 'source_backed_climate_fact_only; no productivity coefficient or duration output belongs in regional_climate_rules',
  relationshipRole: 'upstream_climate_profile_source',
  upstreamRuleTypes: [],
  downstreamRuleTypes: ['project_climate_profiles', 'seasonal_productivity', 'process_seasonal_sensitivity'],
  boundaryPolicy: [
    'mainland China housing-construction climate cold-start only; Hong Kong, Macau, Taiwan require separate regional rule packs before recommendation',
    'owns climateRegion, thermalZone, climateTags and month risk windows',
    'must not own monthly productivity coefficient',
    'must not own process-specific productivity multiplier',
  ],
  selfCalibrationPolicy: {
    candidateSource: 'project_location_observations + project_weather_forecasts',
    runtimeProfileTable: 'project_climate_profiles',
    ruleTable: 'regional_climate_rules',
    candidateTable: 'algorithm_seed_upgrade_candidates',
    candidateSeedType: 'regional_climate_rules',
    actionPolicy: 'project profile updates automatically; city/admin-code rule candidates are auto-created as candidate_only and hidden from frontend until enterprise admin governance exists',
  },
  webVerified: true,
  reviewNeeded: false,
} as const
