import type {
  CommercialControlRole,
  DocumentEvidenceRole,
  InspectionAcceptanceRole,
  ManagementControlRole,
  QualityControlRole,
  SafetyControlRole,
} from './controlRoles.js'
import type { DurationContributionMode } from './durationContributionMode.js'
import type { ExecutionNature } from './executionNature.js'

export type WbsTemplateSemanticOverride = {
  stableCode: string
  reason: string
  source: 'manual_semantic_governance'
  reviewedAt: string
  durationContributionMode: DurationContributionMode
  executionNature: ExecutionNature
  qualityControlRole: QualityControlRole
  safetyControlRole: SafetyControlRole
  inspectionAcceptanceRole: InspectionAcceptanceRole
  documentEvidenceRole: DocumentEvidenceRole
  commercialControlRole: CommercialControlRole
  managementControlRole: ManagementControlRole
}

function semanticOverride(input: Omit<WbsTemplateSemanticOverride, 'source' | 'reviewedAt'> & { reviewedAt?: string }): WbsTemplateSemanticOverride {
  return {
    source: 'manual_semantic_governance',
    reviewedAt: input.reviewedAt ?? '2026-05-21',
    ...input,
  }
}

export const WBS_TEMPLATE_SEMANTIC_OVERRIDES: WbsTemplateSemanticOverride[] = [
  ...[
    '07-04-02',
    'WPI-01-01-01',
    'FIR-02-01-01',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: 'overview item pack contains physical installation, construction, commissioning, or test execution work; acceptance/control words are cross-cutting roles and must not turn the whole package into a non-duration gate.',
    reviewedAt: '2026-05-26',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  })),
  semanticOverride({
    stableCode: 'WPI-02-01-01',
    reason: '厨卫阳台闭水移交包的概览层语义是湿区闭水复查与保护层交接释放；包内可有实体防水/保护层作业，但概览行本身不应承载普通实体施工工期。',
    reviewedAt: '2026-06-07',
    durationContributionMode: 'handover_marker',
    executionNature: 'handover_milestone',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: '01-07-01-P07',
    reason: '主体结构防水验收是质量验收门，不是普通实体施工工序。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: '03-09-01-P09',
    reason: '幕墙淋水检查和验收是实体系统试验性作业后的质量门，需承载验收/试验语义。',
    durationContributionMode: 'quality_gate',
    executionNature: 'physical_work',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'MS-01-01-07-P01',
    reason: '主体结构验收通过是验收时间轴/计划骨架投影，不反向污染普通工期族。',
    durationContributionMode: 'handover_marker',
    executionNature: 'handover_milestone',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'MS-01-01-11-P01',
    reason: '竣工验收备案完成是竣工验收时间轴的大节点投影，不作为普通任务工期样本。',
    durationContributionMode: 'handover_marker',
    executionNature: 'handover_milestone',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'completion_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-01-P02',
    reason: '深基坑专项施工方案编制是危大管理动作和审批材料准备，不承载实体施工工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'management_action',
    qualityControlRole: 'none',
    safetyControlRole: 'special_plan_control',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'approval_document',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-01-P03',
    reason: '深基坑专项施工方案审核审批是危大审批门，不进入实体施工工期族。',
    durationContributionMode: 'quality_gate',
    executionNature: 'management_action',
    qualityControlRole: 'none',
    safetyControlRole: 'special_plan_control',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'approval_document',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-01-P04',
    reason: '深基坑专家论证是法定危大治理节点，属于管理闭合而非实体施工。',
    durationContributionMode: 'quality_gate',
    executionNature: 'management_action',
    qualityControlRole: 'none',
    safetyControlRole: 'special_plan_control',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'approval_document',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-01-P07',
    reason: '深基坑第三方监测成果接收是外部监测等待和安全控制事实，不按普通施工工期处理。',
    durationContributionMode: 'external_wait',
    executionNature: 'monitoring_wait',
    qualityControlRole: 'test_control',
    safetyControlRole: 'monitoring_control',
    inspectionAcceptanceRole: 'third_party_test',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'issue_rectification',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-01-P08',
    reason: '深基坑专项验收与资料归档是安全验收门和资料闭合，不承载实体工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'safety_acceptance',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-02-P08',
    reason: '高大模板支撑专项验收是危大安全验收门，不进入普通工期族。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'safety_acceptance',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-03-P08',
    reason: '起重吊装及塔吊安装专项验收是设备安全验收门，不作为实体施工工期样本。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'safety_acceptance',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-04-P08',
    reason: '脚手架专项验收是安全验收门，应与架体搭设实体工序分离。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'safety_acceptance',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-06-P01-S02',
    reason: '临时用电实体搭设安装属于现场实体作业，同时承担临电安全控制。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'temporary_facility_safety',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-01-01-06-P03-S02',
    reason: 'TN-S接零接地和漏保测试实体搭设安装是临电实体作业和安全测试双属性节点。',
    durationContributionMode: 'quality_gate',
    executionNature: 'physical_work',
    qualityControlRole: 'test_control',
    safetyControlRole: 'temporary_facility_safety',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-02-01-01-P02-S02',
    reason: '塔吊基础钢筋模板预埋件施工是实体作业,但应保留起重机械危大安全属性。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'hidden_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'hidden_acceptance',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-02-01-01-P05-S02',
    reason: '塔吊安装顶升附着实施是实体危大作业,不能被过程监测词误判成纯等待。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'organization_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-02-01-02-P06-S02',
    reason: '施工升降机拆卸和楼层平台恢复是实体拆改作业,需保留危大安全属性。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'organization_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-02-01-03-P04-S02',
    reason: '吊篮支架配重钢丝绳安装检查是高处作业实体节点,需保留危大安全控制。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'organization_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-02-01-04-P02-S02',
    reason: '高支模立杆扫地杆剪刀撑和水平杆搭设是实体危大作业。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'organization_control',
  }),
  semanticOverride({
    stableCode: 'DANGER-02-01-04-P05-S02',
    reason: '高支模混凝土浇筑旁站和架体变形监测是实体施工叠加监测控制,不能只按监测等待处理。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'organization_control',
  }),
  semanticOverride({
    stableCode: 'QR-01-01-03-P02',
    reason: '混凝土试块留置送检是见证取样/检测等待事项,不作为普通实体工期样本。',
    durationContributionMode: 'external_wait',
    executionNature: 'inspection_test',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'material_retest',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'none',
  }),
  semanticOverride({
    stableCode: 'QR-01-01-03-P04',
    reason: '见证取样报告闭合是资料和检测报告闭合,不承载实体施工工期。',
    durationContributionMode: 'record_only',
    executionNature: 'document_record',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'material_retest',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'QR-01-01-05-P03',
    reason: '防水保温隐蔽验收是隐蔽验收门,不是防水保温实体施工。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'hidden_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'hidden_acceptance',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'QR-01-01-06-P02',
    reason: '砌体抹灰实测实量是质量实测动作,不等同于砌体或抹灰实体施工。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'issue_rectification',
  }),
  semanticOverride({
    stableCode: 'DCS-01-01-04-P01',
    reason: '月度形象进度计量申报是商务计量事项,不进入实体工期/物理依赖计算。',
    durationContributionMode: 'record_only',
    executionNature: 'management_action',
    qualityControlRole: 'none',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'commercial_document',
    commercialControlRole: 'quantity_measurement',
    managementControlRole: 'progress_control',
  }),
  semanticOverride({
    stableCode: 'DCS-01-01-05-P02',
    reason: '过程结算编制和报审是商务管理动作,不承载施工实体工期。',
    durationContributionMode: 'record_only',
    executionNature: 'management_action',
    qualityControlRole: 'none',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'commercial_document',
    commercialControlRole: 'settlement',
    managementControlRole: 'planning_control',
  }),
  semanticOverride({
    stableCode: 'FAC-02-01-02-P07',
    reason: '幕墙四性试验报告复核是检测报告闭合,不等同于幕墙实体安装。',
    durationContributionMode: 'record_only',
    executionNature: 'document_record',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'third_party_test',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'FIR-05-01-02-P07',
    reason: '消防验收备案资料补正是专项验收资料闭合,不进入普通施工工期族。',
    durationContributionMode: 'record_only',
    executionNature: 'document_record',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: '05-01-09-P05',
    reason: '末端流量压力和用水点覆盖复测是给水系统现场调试复测作业,同时承担质量测试门禁。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: '03-03-01-P06',
    reason: '闭水或淋水试验是现场试验性作业,应保留实体作业和质量门禁双属性。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: '01-02-13-P09',
    reason: '沉降观测点复核属于监测/观测控制,不作为普通实体施工工期样本。',
    durationContributionMode: 'external_wait',
    executionNature: 'monitoring_wait',
    qualityControlRole: 'test_control',
    safetyControlRole: 'monitoring_control',
    inspectionAcceptanceRole: 'third_party_test',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'progress_control',
  }),
  semanticOverride({
    stableCode: '02-01-06-P02',
    reason: '吊装方案交底是起重吊装安全技术管理动作,不是构件吊装实体工序。',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'none',
    safetyControlRole: 'special_plan_control',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'approval_document',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: '02-01-06-P04',
    reason: '构件吊装就位是实体吊装作业,需携带起重吊装安全控制属性。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'organization_control',
  }),
  semanticOverride({
    stableCode: 'SITE-05-01-01-P02',
    reason: '分包合同范围界面和总平面交底是进场界面管理动作，不应作为普通施工工期样本。',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'approval_document',
    commercialControlRole: 'none',
    managementControlRole: 'interface_coordination',
  }),
  semanticOverride({
    stableCode: 'SITE-05-01-01-P04',
    reason: '样板先行和技术质量安全交底是技术质量安全交底管理动作，不承载实体施工工期。',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'daily_safety_check',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: 'BDT-05-01-02-P07',
    reason: '样板标准做法固化和大面交底是样板评审后的技术交底和放行，不是实体施工工序。',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: 'PFB-00-01-01-P05',
    reason: '深化图版本冻结和工厂交底是装配式生产前技术管理节点，不进入普通实体施工工期。',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-01-P01',
    reason: '首批构件编号排产计划和合格资料核查是装配式首批构件进场前的计划资料核查，不进入普通施工工期。',
    durationContributionMode: 'embedded_check',
    executionNature: 'document_record',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'planning_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-01-P02',
    reason: '首批构件外观尺寸和预埋件全检在装配式首批构件链中作为验收资料事实记录，不作为实体施工工期。',
    durationContributionMode: 'embedded_check',
    executionNature: 'document_record',
    qualityControlRole: 'hidden_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'hidden_acceptance',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'none',
  }),
  semanticOverride({
    stableCode: 'PFB-00-01-03-P01',
    reason: '运输方案路线和超限报备确认是运输组织和报备管理动作，不是构件实体施工工序。',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'approval_document',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: 'PFB-00-01-03-P01-S02',
    reason: '自动补深步骤中的吊装定位或连接施工属于实体作业，应保留实体工期属性。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-00-01-03-P01-S03',
    reason: '灌浆试块和过程记录是装配式连接质量过程控制，不应被运输方案父级语义带偏为管理工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'physical_work',
    qualityControlRole: 'test_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-02-P01-S02',
    reason: '后续批次构件清单抽查下的吊装定位或连接施工是现场实体作业。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-02-P01-S03',
    reason: '后续批次构件清单抽查下的灌浆试块和过程记录是质量过程控制，不作为管理动作工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'test_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-02-P06-S03',
    reason: '构件资料和堆场台账同步下的灌浆试块和过程记录是试验记录门控，不是普通实体施工工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'test_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-05-P06',
    reason: '楼梯安装偏差和通行条件验收是安装质量验收节点，应作为质量门而非普通施工工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-05-P06-S01',
    reason: '楼梯安装验收条件核查是验收前置检查，不承载普通施工工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-05-P06-S02',
    reason: '楼梯安装现场抽查复核是质量检查动作，应作为质量门。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-05-P06-S04',
    reason: '楼梯安装验收结论签认是验收结论节点，不应进入普通施工工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-06-P01',
    reason: '外挑构件支撑和吊装方案复核是吊装前方案复核，不是实体吊装作业。',
    durationContributionMode: 'quality_gate',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'approval_document',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-06-P01-S01',
    reason: '外挑构件资料和编号复核是吊装前资料复核，不承载实体施工工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'approval_document',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-06-P01-S02',
    reason: '外挑构件吊装定位或连接施工是现场实体作业，应承载实体工期。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-06-P01-S03',
    reason: '外挑构件灌浆试块和过程记录是连接质量控制，应作为质量门。',
    durationContributionMode: 'quality_gate',
    executionNature: 'physical_work',
    qualityControlRole: 'test_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-01-01-06-P01-S04',
    reason: '外挑构件偏差复测和质量检查是质量门控，不作为普通施工工期。',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'test_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-03-01-02-P03-S02',
    reason: '示范申报资料整理下的吊装定位或连接施工应被识别为实体作业。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-03-01-02-P03-S03',
    reason: '示范申报资料整理下的灌浆试块和过程记录是质量试验控制。',
    durationContributionMode: 'quality_gate',
    executionNature: 'physical_work',
    qualityControlRole: 'test_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-03-01-03-P02-S02',
    reason: '竣工图模型资料整理下的吊装定位或连接施工是实体作业，不能被父级资料语义污染。',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-03-01-03-P02-S03',
    reason: '竣工图模型资料整理下的灌浆试块和过程记录是质量试验控制。',
    durationContributionMode: 'quality_gate',
    executionNature: 'physical_work',
    qualityControlRole: 'test_control',
    safetyControlRole: 'hazardous_work',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'site_readiness_control',
  }),
  semanticOverride({
    stableCode: 'PFB-03-01-03-P04',
    reason: '物业维保注意事项和渗漏维修接口交底是交付维保交底，不应作为普通施工工期样本。',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'interface_coordination',
  }),
  semanticOverride({
    stableCode: 'HRT-01-01-02-P09',
    reason: 'Heritage protection-plan confirmation is the final expert and trial-repair release gate before same-zone traditional restoration work, so it must remain anchorable for process-level schedule dependencies instead of being treated as an embedded preparation check.',
    reviewedAt: '2026-06-05',
    durationContributionMode: 'quality_gate',
    executionNature: 'management_action',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'approval_document',
    commercialControlRole: 'none',
    managementControlRole: 'technical_control',
  }),
  ...[
    'BDT-05-01-03-P01',
    'BDT-06-01-01-P06',
    'BDT-07-01-04-P06',
    'BDT-08-01-01-P01',
    'BDT-08-01-03-P01',
    'CMP-01-01-01-P05',
    'CMP-01-01-02-P03',
    'CMP-01-01-02-P05',
    'HRT-03-01-02-P01',
    'HRT-03-01-02-P01-S01',
    'MIC-03-01-01-P01',
    'MIC-03-01-01-P03',
    'RNV-03-01-01-P03',
    'RNV-03-01-01-P05',
    'TOD-01-01-01-P04',
    'TOD-01-01-02-P02',
    'TOD-01-01-02-P02-S01',
    'TOD-01-01-02-P02-S02',
    'TOD-01-01-02-P05',
    'TOD-03-01-01-P02',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: '组织、审批、交底、协调或确认类节点是管理控制动作；可进入计划树，但不得作为普通实体工期/依赖锚点污染规则。',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: stableCode.startsWith('TOD-01-01-02') || stableCode === 'MIC-03-01-01-P03' ? 'operation_permit' : 'none',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: stableCode.includes('审批') || stableCode.startsWith('TOD-01-01-02') ? 'approval_document' : 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: stableCode.startsWith('BDT-05') || stableCode.startsWith('BDT-06') || stableCode.startsWith('BDT-07') ? 'technical_control' : 'interface_coordination',
  })),
  semanticOverride({
    stableCode: 'IKU-01-01-01-P04',
    reason: 'IKU厨房模块样板补深后，P04已调整为柜体台面工厂试装实体作业，不再是纯BIM/协调检查节点。',
    reviewedAt: '2026-06-03',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'interface_coordination',
  }),
  ...[
    'DTC-02-01-02-P05',
    'DTC-02-02-02-P05',
    'DTC-03-01-02-P05',
    'DTC-03-01-02-P05-S01',
    'ICR-03-01-01-P05',
    'ICR-03-01-02-P05',
    'ICR-04-01-01-P05',
    'ICR-04-01-02-P05',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: '投运确认是系统交付/投运门，不是普通实体施工工期样本。',
    durationContributionMode: 'handover_marker',
    executionNature: 'handover_milestone',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  })),
  semanticOverride({
    stableCode: 'ICR-05-01-05-P07',
    reason: 'PQ连续生产批次运行是试生产放行前的连续批次现场运行工序，承载实际运行工期；最终放行门由P10承担。',
    reviewedAt: '2026-06-05',
    durationContributionMode: 'duration_bearing',
    executionNature: 'physical_work',
    qualityControlRole: 'process_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'issue_rectification',
  }),
  semanticOverride({
    stableCode: 'DTC-03-01-02-P06-S02',
    reason: '消防联动问题闭合后的现场复查复测是整改闭合质量复核，不是继续施工或普通投运里程碑；应作为质量门禁锚点承接复查记录。',
    reviewedAt: '2026-05-23',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'test_control',
    safetyControlRole: 'temporary_facility_safety',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'issue_rectification',
  }),
  semanticOverride({
    stableCode: 'DTC-03-01-02-P06-S03',
    reason: '消防联动问题整改责任确认是问题闭合管理控制动作，不直接改变现场实体，不应作为 physical_work 或普通工期锚点。',
    reviewedAt: '2026-05-23',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'temporary_facility_safety',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'issue_rectification',
  }),
  semanticOverride({
    stableCode: 'DTC-03-01-02-P06-S05',
    reason: '消防联动问题闭合记录归档是验收资料留痕，不是实体施工或工期承载节点；只保留资料证据角色。',
    reviewedAt: '2026-05-23',
    durationContributionMode: 'record_only',
    executionNature: 'document_record',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'temporary_facility_safety',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'issue_rectification',
  }),
  ...[
    'CLN-04-01-09-P07',
    'CMP-05-01-22-P03',
    'CMP-05-01-29-P02',
    'TOD-04-01-22-P03',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: '台账、钥匙、门禁、备品或回路资料移交是交付留痕/移交控制节点，不是普通实体施工工序；只能作为移交门或资料证据参与计划治理。',
    reviewedAt: '2026-05-23',
    durationContributionMode: 'handover_marker',
    executionNature: 'handover_milestone',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'completion_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  })),
  ...[
    'CLN-04-01-12-P07',
    'DTC-04-01-25-P07',
    'DTC-04-01-26-P07',
    'DTC-04-01-26-P07-S02',
    'DTC-04-01-26-P09',
    'DTC-04-01-28-P07',
    'DTC-04-01-28-P08',
    'ICR-05-01-03-P07',
    'ICR-05-01-04-P07',
    'ICR-05-01-07-P07',
    'ICR-05-01-29-P08',
    'STL-04-01-07-P07',
    'STL-04-01-21-P07',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: '报告签认、测试签认、演练签认或验收报告归档是专项验收/测试闭合节点，不应作为普通实体工期样本；保留验收门禁和报告证据角色。',
    reviewedAt: '2026-05-23',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  })),
  semanticOverride({
    stableCode: 'TOD-01-01-02-P09',
    reason: '营业线夜间天窗作业销项复核是同区转换结构施工前的运营线窗口关闭与恢复确认，应作为交接释放锚点参与 L3 跨包依赖，而不是普通实体施工工序。',
    reviewedAt: '2026-06-07',
    durationContributionMode: 'handover_marker',
    executionNature: 'handover_milestone',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'temporary_facility_safety',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'ICR-05-01-05-P07-S01',
    reason: 'PQ连续生产批次运行前的专项深化和材料设备复核是运行条件核查，不直接改变现场实体，不应作为普通实体工期样本。',
    reviewedAt: '2026-05-24',
    durationContributionMode: 'embedded_check',
    executionNature: 'technical_preparation',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'material_retest',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'resource_control',
  }),
  ...[
    'ICR-05-01-05-P10',
    'ICR-04-02-01-P09',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: 'Industrial cleanroom trial-production or production release signoff is a process handover marker that anchors same-system L3 workflow release; it is not a plain record-only archive item and must remain available for cross-item dependency generation without contributing ordinary physical-work duration.',
    reviewedAt: '2026-06-05',
    durationContributionMode: 'handover_marker',
    executionNature: 'handover_milestone',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  })),
  ...[
    'FND-06-01-05-P06',
    'FND-06-01-05-P06-S02',
    'IKU-03-01-03-P05',
    'IKU-03-01-03-P05-S02',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: '保护资料、标识资料、资料组卷和归档属于资料证据闭合，不直接改变现场实体，不应承载普通工期或生成实体依赖。',
    reviewedAt: '2026-05-23',
    durationContributionMode: 'record_only',
    executionNature: 'document_record',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: stableCode.startsWith('IKU') ? 'daily_safety_check' : 'none',
    inspectionAcceptanceRole: 'special_acceptance',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  })),
  ...[
    'HTL-02-01-02-P04',
    'BDT-06-01-03-P05',
    'CMP-04-01-01-P04-S02',
    'CMP-04-01-01-P04-S03',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: '修补、复测、整改闭合类节点直接改变现场实体或完成实体缺陷处置，应保留实体作业语义和质量门属性。',
    durationContributionMode: 'quality_gate',
    executionNature: 'physical_work',
    qualityControlRole: 'defect_rework',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'issue_rectification',
  })),
  semanticOverride({
    stableCode: 'BDT-09-01-01-P06',
    reason: '楼层穿插日清日结复盘是总包节奏管理动作，只记录问题闭合与责任分派，不直接改变实体工程，不能作为普通实体工期或依赖锚点。',
    reviewedAt: '2026-05-24',
    durationContributionMode: 'embedded_check',
    executionNature: 'management_action',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'none',
    documentEvidenceRole: 'technical_record',
    commercialControlRole: 'none',
    managementControlRole: 'interface_coordination',
  }),
  ...[
    'BDT-09-01-01-P08',
    'BDT-09-01-02-P08',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: '穿插/运维接口移交签认是界面移交和资料留痕节点，不是实体施工动作；应保留移交控制语义，避免污染普通施工工期和依赖规则。',
    reviewedAt: '2026-05-24',
    durationContributionMode: 'handover_marker',
    executionNature: 'handover_milestone',
    qualityControlRole: 'acceptance_gate',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  })),
  semanticOverride({
    stableCode: 'FIR-05-01-01-P06',
    reason: 'Fire smoke-exhaust detection configuration is retained as test-report evidence in the hotel/public-fitout closeout chain; it must not contribute ordinary physical-work duration.',
    reviewedAt: '2026-06-09',
    durationContributionMode: 'record_only',
    executionNature: 'document_record',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  }),
  semanticOverride({
    stableCode: 'OUT-05-01-01-P02',
    reason: 'External utility-interface defect rectification is a release gate before formal connection handover; it should anchor quality closure without expanding ordinary outdoor duration math.',
    reviewedAt: '2026-06-09',
    durationContributionMode: 'quality_gate',
    executionNature: 'physical_work',
    qualityControlRole: 'defect_rework',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'issue_rectification',
  }),
  semanticOverride({
    stableCode: 'STL-01-01-02-P07',
    reason: 'High-strength bolt retest and final-tightening torque sampling is governed as material/test evidence in the steel quality chain, not as a normal fabrication-duration row.',
    reviewedAt: '2026-06-09',
    durationContributionMode: 'record_only',
    executionNature: 'document_record',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'material_retest',
    documentEvidenceRole: 'test_report',
    commercialControlRole: 'none',
    managementControlRole: 'none',
  }),
  semanticOverride({
    stableCode: 'FIR-01-01-01-P06',
    reason: 'Fire pipe and valve incoming-material review is a material release gate before sprinkler installation, not a plain embedded preparation check.',
    reviewedAt: '2026-06-09',
    durationContributionMode: 'quality_gate',
    executionNature: 'inspection_test',
    qualityControlRole: 'precondition_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'material_retest',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'resource_control',
  }),
  ...[
    'INT-04-01-01-P08',
    'HVA-02-01-02-P06',
    'ELV-02-01-02-P07',
  ].map((stableCode) => semanticOverride({
    stableCode,
    reason: 'Runtime retest and tuning closeout rows protect system handover readiness; keep them as handover markers so they can anchor workflow release without inflating ordinary construction duration.',
    reviewedAt: '2026-06-09',
    durationContributionMode: 'handover_marker',
    executionNature: 'handover_milestone',
    qualityControlRole: 'test_control',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'handover_document',
    commercialControlRole: 'none',
    managementControlRole: 'handover_control',
  })),
  semanticOverride({
    stableCode: 'ELV-01-01-01-P03',
    reason: 'Elevator machine-room foundation and power-interface rectification is a civil-interface release gate before elevator installation proceeds, not a normal production-duration row.',
    reviewedAt: '2026-06-09',
    durationContributionMode: 'quality_gate',
    executionNature: 'physical_work',
    qualityControlRole: 'defect_rework',
    safetyControlRole: 'none',
    inspectionAcceptanceRole: 'self_check',
    documentEvidenceRole: 'inspection_record',
    commercialControlRole: 'none',
    managementControlRole: 'issue_rectification',
  }),
]

const SEMANTIC_OVERRIDE_BY_STABLE_CODE = new Map(
  WBS_TEMPLATE_SEMANTIC_OVERRIDES.map((override) => [override.stableCode, override]),
)

export function getWbsTemplateSemanticOverride(stableCode: string | null | undefined) {
  return SEMANTIC_OVERRIDE_BY_STABLE_CODE.get(String(stableCode ?? '').trim()) ?? null
}

export function applyWbsTemplateSemanticOverride<T extends Record<string, unknown>>(
  stableCode: string | null | undefined,
  metadata: T,
): T {
  const override = getWbsTemplateSemanticOverride(stableCode)
  if (!override) return metadata
  return {
    ...metadata,
    durationContributionMode: override.durationContributionMode,
    executionNature: override.executionNature,
    qualityControlRole: override.qualityControlRole,
    safetyControlRole: override.safetyControlRole,
    inspectionAcceptanceRole: override.inspectionAcceptanceRole,
    documentEvidenceRole: override.documentEvidenceRole,
    commercialControlRole: override.commercialControlRole,
    managementControlRole: override.managementControlRole,
    semanticOverrideSource: override.source,
    semanticOverrideReason: override.reason,
    semanticOverrideReviewedAt: override.reviewedAt,
  }
}
