import type { WbsTemplateProjectRecommendationKey } from './wbsTemplateProjectRecommendations.js'

export type WbsTemplateRealProjectCoverageMatrixEntry = {
  projectCode: string
  reportSection: string
  projectName: string
  recommendationKey: WbsTemplateProjectRecommendationKey
  requiredTemplateIds: string[]
  requiredStableCodePrefixes: string[]
  expectedRowCountRange: [number, number]
  expectedRuntimeReplayRowCountRange?: [number, number]
  expectedDurationDaysRange: [number, number]
  engineRequirements?: Array<'split_by_phase'>
}

export const WBS_TEMPLATE_REAL_PROJECT_COVERAGE_MATRIX: WbsTemplateRealProjectCoverageMatrixEntry[] = [
  {
    projectCode: 'A',
    reportSection: '2.5',
    projectName: 'cast_in_situ_residential_with_basement',
    recommendationKey: 'residential',
    requiredTemplateIds: [
      'china-gb55032-2022',
      'china-building-site-management',
      'china-dangerous-subproject-control',
      'china-quality-responsibility-acceptance',
      'china-project-milestone-handover',
      'china-waterproof-insulation',
      'china-jgj-tianjin-decoration',
      'china-plumbing-heating-system',
      'china-electrical-system',
      'china-building-fine-detail',
    ],
    requiredStableCodePrefixes: ['01', '02', '03', 'SITE', 'DANGER', 'QR', 'MS', 'WPI', 'DEC', 'PLU', 'ELE', 'BDT'],
    expectedRowCountRange: [2200, 2800],
    expectedRuntimeReplayRowCountRange: [3150, 3250],
    expectedDurationDaysRange: [1020, 1200],
    engineRequirements: ['split_by_phase'],
  },
  {
    projectCode: 'B',
    reportSection: '3.6',
    projectName: 'prefabricated_residential',
    recommendationKey: 'prefab_residential',
    requiredTemplateIds: ['china-gb55032-2022', 'china-prefabricated-assembly', 'china-dangerous-subproject-control', 'china-building-fine-detail'],
    requiredStableCodePrefixes: ['PFB-00', 'PFB-01', 'PFB-02', 'BDT', 'DANGER'],
    expectedRowCountRange: [2800, 3500],
    expectedRuntimeReplayRowCountRange: [1200, 1280],
    expectedDurationDaysRange: [960, 1110],
  },
  {
    projectCode: 'C',
    reportSection: '4.6',
    projectName: 'tertiary_hospital',
    recommendationKey: 'hospital',
    requiredTemplateIds: ['china-cleanroom-medical-specialty', 'china-hvac-system', 'china-cecs-fire-system', 'china-intelligent-building-system', 'china-electrical-system'],
    requiredStableCodePrefixes: ['CLN', 'HVA', 'FIR', 'INT', 'ELE', 'MS'],
    expectedRowCountRange: [3500, 4500],
    expectedRuntimeReplayRowCountRange: [1750, 1900],
    expectedDurationDaysRange: [1080, 1440],
  },
  {
    projectCode: 'D',
    reportSection: '5.6',
    projectName: 'data_center_idc',
    recommendationKey: 'data_center',
    requiredTemplateIds: ['china-data-center-specialty', 'china-electrical-system', 'china-hvac-system', 'china-cecs-fire-system', 'china-intelligent-building-system'],
    requiredStableCodePrefixes: ['DTC', 'ELE', 'HVA', 'FIR', 'INT'],
    expectedRowCountRange: [3000, 4000],
    expectedRuntimeReplayRowCountRange: [1080, 1180],
    expectedDurationDaysRange: [720, 1080],
  },
  {
    projectCode: 'E',
    reportSection: '6.6',
    projectName: 'industrial_cleanroom_factory',
    recommendationKey: 'clean_industrial',
    requiredTemplateIds: ['china-industrial-cleanroom-specialty', 'china-hvac-system', 'china-electrical-system', 'china-cecs-fire-system'],
    requiredStableCodePrefixes: ['ICR', 'HVA', 'ELE', 'FIR'],
    expectedRowCountRange: [3500, 4500],
    expectedRuntimeReplayRowCountRange: [930, 1030],
    expectedDurationDaysRange: [720, 1080],
  },
  {
    projectCode: 'F',
    reportSection: '7.6',
    projectName: 'large_span_steel_public_building',
    recommendationKey: 'large_span_steel_public',
    requiredTemplateIds: ['china-steel-structure-specialty', 'china-dangerous-subproject-control', 'china-document-commercial-support'],
    requiredStableCodePrefixes: ['STL', 'DANGER', 'DCS', 'MS'],
    expectedRowCountRange: [3000, 3800],
    expectedRuntimeReplayRowCountRange: [1130, 1230],
    expectedDurationDaysRange: [540, 900],
  },
  {
    projectCode: 'G1',
    reportSection: '8.6',
    projectName: 'existing_building_renovation',
    recommendationKey: 'renovation',
    requiredTemplateIds: ['china-renovation-retrofit-specialty', 'china-building-fine-detail', 'china-dangerous-subproject-control'],
    requiredStableCodePrefixes: ['RNV', 'BDT', 'DANGER', 'FIR'],
    expectedRowCountRange: [2800, 3500],
    expectedRuntimeReplayRowCountRange: [1080, 1180],
    expectedDurationDaysRange: [240, 540],
  },
  {
    projectCode: 'G2',
    reportSection: '8.6',
    projectName: 'heritage_preservation',
    recommendationKey: 'heritage',
    requiredTemplateIds: ['china-heritage-preservation-specialty', 'china-document-commercial-support', 'china-building-fine-detail'],
    requiredStableCodePrefixes: ['HRT', 'DCS', 'BDT'],
    expectedRowCountRange: [2800, 3500],
    expectedRuntimeReplayRowCountRange: [660, 760],
    expectedDurationDaysRange: [360, 720],
  },
  {
    projectCode: 'H',
    reportSection: '9.6',
    projectName: 'university_campus',
    recommendationKey: 'campus',
    requiredTemplateIds: ['china-campus-specialty', 'china-gb55032-2022-outdoor', 'china-intelligent-building-system'],
    requiredStableCodePrefixes: ['CMP', 'OUT', 'INT', 'MS'],
    expectedRowCountRange: [3500, 4500],
    expectedRuntimeReplayRowCountRange: [1080, 1180],
    expectedDurationDaysRange: [540, 900],
    engineRequirements: ['split_by_phase'],
  },
  {
    projectCode: 'I',
    reportSection: '10.6',
    projectName: 'tod_upper_cover',
    recommendationKey: 'tod',
    requiredTemplateIds: ['china-tod-upper-cover-specialty', 'china-steel-structure-specialty', 'china-document-commercial-support'],
    requiredStableCodePrefixes: ['TOD', 'STL', 'DCS', 'DANGER'],
    expectedRowCountRange: [3000, 3800],
    expectedRuntimeReplayRowCountRange: [800, 900],
    expectedDurationDaysRange: [900, 1500],
  },
  {
    projectCode: 'J',
    reportSection: '11.6',
    projectName: 'mic_modular_building',
    recommendationKey: 'modular_construction',
    requiredTemplateIds: ['china-modular-mic-specialty', 'china-prefab-bathroom-specialty', 'china-prefab-kitchen-specialty'],
    requiredStableCodePrefixes: ['MIC', 'IBU', 'IKU', 'DANGER'],
    expectedRowCountRange: [2500, 3200],
    expectedRuntimeReplayRowCountRange: [900, 1000],
    expectedDurationDaysRange: [180, 360],
  },
  {
    projectCode: 'K',
    reportSection: '12.6',
    projectName: 'luxury_hotel_complex',
    recommendationKey: 'luxury_hotel',
    requiredTemplateIds: ['china-hotel-specialty', 'china-jgj-tianjin-decoration', 'china-cecs-fire-system', 'china-hvac-system'],
    requiredStableCodePrefixes: ['HTL', 'DEC', 'FIR', 'HVA', 'PLU'],
    expectedRowCountRange: [3500, 4500],
    expectedRuntimeReplayRowCountRange: [990, 1100],
    expectedDurationDaysRange: [900, 1350],
  },
  {
    projectCode: 'L',
    reportSection: '13.6',
    projectName: 'deep_foundation_project',
    recommendationKey: 'deep_foundation',
    requiredTemplateIds: ['china-foundation-pit-pile', 'china-dangerous-subproject-control', 'china-waterproof-insulation'],
    requiredStableCodePrefixes: ['FND', 'DANGER-01-01-01', 'WPI'],
    expectedRowCountRange: [2200, 2800],
    expectedRuntimeReplayRowCountRange: [600, 700],
    expectedDurationDaysRange: [360, 720],
  },
]
